# DO NOT EDIT THIS FILE MANUALLY! Use `release update-releases-file`.
load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

CONFIG_LINUX_AMD64 = "linux-amd64"
CONFIG_LINUX_ARM64 = "linux-arm64"
CONFIG_DARWIN_AMD64 = "darwin-10.9-amd64"
CONFIG_DARWIN_ARM64 = "darwin-11.0-arm64"

_CONFIGS = [
    ("25.2.7", [
        (CONFIG_DARWIN_AMD64, "a6c309843cb1e89f0d620f9235cebc40f55388ae1d250d95c3baebe85563bcd8"),
        (CONFIG_DARWIN_ARM64, "101496af1f44e4119e531ab54de2d12034989d6cc1fc70951afa0f5ac97d87c2"),
        (CONFIG_LINUX_AMD64, "01059d8dfa480a9c617ed969b159a1b5f9a50b4f8ea2d5da4621815c0392f873"),
        (CONFIG_LINUX_ARM64, "4d050fd449f5a9cc4e313a49039e5808404ce6e2cf3a56dded1f2880e45bc77c"),
    ]),
    ("25.3.3", [
        (CONFIG_DARWIN_AMD64, "66fb1bc481b70d0201bbe90b77a14bb462e37ed454832049c64a1c7dfa1d0bf4"),
        (CONFIG_DARWIN_ARM64, "094fcac47f9d5e9d0b53db1f09e7cf9beb68d08a41acd465f38be4b064089f95"),
        (CONFIG_LINUX_AMD64, "ca965ba71396c93d607e08608444d440b7f51c6673e87e48d71462ca0be415ea"),
        (CONFIG_LINUX_ARM64, "aeb06e48e5e2d7aeaadf2df3f5b770874af52fbac900ed4a9a6795299959aba3"),
    ]),
    ("25.4.0-rc.1", [
        (CONFIG_DARWIN_AMD64, "3949cf776c9fd8722192da32f8836ad4c36f593335d0f6856d0c32bc9f84ce32"),
        (CONFIG_DARWIN_ARM64, "cde9bd25e78bf71dd3e47ff99cfad423f9f717a9068ae00bc56d9c1fdad15203"),
        (CONFIG_LINUX_AMD64, "93699c7bf49fed2acef53da7ef8efb0bc35641db6a391c7c4625fde4658bff4d"),
        (CONFIG_LINUX_ARM64, "91d4706262db21a8d34f8309a3ee036d08dc15436ba3e1d4b2650c7169105747"),
    ]),
]

def _munge_name(s):
    return s.replace("-", "_").replace(".", "_")

def _repo_name(version, config_name):
    return "cockroach_binary_v{}_{}".format(
        _munge_name(version),
        _munge_name(config_name))

def _file_name(version, config_name):
    return "cockroach-v{}.{}/cockroach".format(
        version, config_name)

def target(config_name):
    targets = []
    for versionAndConfigs in _CONFIGS:
        version, _ = versionAndConfigs
        targets.append("@{}//:{}".format(_repo_name(version, config_name),
                                         _file_name(version, config_name)))
    return targets

def cockroach_binaries_for_testing():
    for versionAndConfigs in _CONFIGS:
        version, configs = versionAndConfigs
        for config in configs:
            config_name, shasum = config
            file_name = _file_name(version, config_name)
            http_archive(
                name = _repo_name(version, config_name),
                build_file_content = """exports_files(["{}"])""".format(file_name),
                sha256 = shasum,
                urls = [
                    "https://binaries.cockroachdb.com/{}".format(
                        file_name.removesuffix("/cockroach")) + ".tgz",
                ],
            )
