// Copyright 2020 The Cockroach Authors.
//
// Use of this software is governed by the Business Source License
// included in the file licenses/BSL.txt.
//
// As of the Change Date specified in that file, in accordance with
// the Business Source License, use of this software will be governed
// by the Apache License, Version 2.0, included in the file
// licenses/APL.txt.

package tests

// These are lists of known activerecord test errors and failures.
// When the activerecord test suite is run, the results are compared to this list.
// Any passed test that is not on this list is reported as PASS - expected
// Any passed test that is on this list is reported as PASS - unexpected
// Any failed test that is on this list is reported as FAIL - expected
// Any failed test that is not on this list is reported as FAIL - unexpected
// Any test on this list that is not run is reported as FAIL - not run
//
// Please keep these lists alphabetized for easy diffing.
// After a failed run, an updated version of this blocklist should be available
// in the test log.
var activeRecordBlocklist = blocklist{
	"ActiveRecord::CockroachDB::Migration::PGChangeSchemaTest#test_change_string_to_date":                                               "49329",
	"ActiveRecord::CockroachDB::Migration::PGChangeSchemaTest#test_change_type_with_array":                                              "49329",
	"ActiveRecord::CockroachDB::Migration::PGChangeSchemaTest#test_change_type_with_symbol":                                             "49329",
	"ActiveRecord::CockroachDB::Migration::PGChangeSchemaTest#test_change_type_with_symbol_using_datetime":                              "49329",
	"ActiveRecord::CockroachDB::Migration::PGChangeSchemaTest#test_change_type_with_symbol_using_datetime_with_timestamptz_as_default":  "49329",
	"ActiveRecord::CockroachDB::Migration::PGChangeSchemaTest#test_change_type_with_symbol_using_timestamp_with_timestamptz_as_default": "49329",
	"ActiveRecord::CockroachDB::Migration::PGChangeSchemaTest#test_change_type_with_symbol_with_timestamptz_as_default":                 "49329",
	"ActiveRecord::CockroachDB::Migration::PGChangeSchemaTest#test_change_type_with_symbol_with_timestamptz":                            "49329",
	"PostgresqlRangeTest#test_timezone_array_awareness_tsrange":                                                                         "27791",
	"PostgresqlRangeTest#test_timezone_array_awareness_tzrange":                                                                         "27791",
	// TODO(yang): investigate cause further
	"PostgreSQLReferentialIntegrityTest#test_all_foreign_keys_valid_having_foreign_keys_in_multiple_schemas": "unknown",
}

var activeRecordIgnoreList = blocklist{
	"ActiveRecord::CockroachDB::Migration::ForeignKeyTest#test_add_foreign_key_with_if_not_exists_not_set":                        "flaky - sometimes complains that a relation does not exist",
	"ActiveRecord::CockroachDB::Migration::ForeignKeyTest#test_add_foreign_key_with_on_update":                                    "flaky - sometimes complains that a relation does not exist",
	"ActiveRecord::CockroachDB::Migration::ForeignKeyTest#test_add_invalid_foreign_key":                                           "flaky - sometimes complains that a relation does not exist",
	"ActiveRecord::CockroachDB::Migration::ForeignKeyTest#test_add_on_delete_nullify_foreign_key":                                 "flaky - sometimes complains that a relation does not exist",
	"ActiveRecord::CockroachDB::Migration::ForeignKeyTest#test_add_on_delete_restrict_foreign_key":                                "flaky - sometimes complains that a relation does not exist",
	"ActiveRecord::CockroachDB::Migration::ForeignKeyTest#test_remove_foreign_key_with_if_exists_set":                             "flaky - sometimes complains that a relation does not exist",
	"ActiveRecord::Coders::YAMLColumnTestWithSafeLoad#test_returns_string_unless_starts_with_dash":                                "flaky - sometimes attempts to call a method on nil",
	"ActiveRecord::CollectionCacheKeyTest#test_cache_key_for_relation_with_includes":                                              "flaky - sometimes complains that a relation does not exist",
	"ActiveRecord::ConnectionAdapters::ConnectionSwappingNestedTest#test_prevent_writes_can_be_changed_granularly":                "flaky - sometimes attempts to call a method on nil",
	"ActiveRecord::Encryption::StoragePerformanceTest#test_storage_overload_without_storing_keys_is_acceptable":                   "flaky - sometimes complains a file is not open for writing",
	"ActiveRecord::InvertibleMigrationTest#test_down":                                                                             "flaky - sometimes complains that a relation already exists",
	"ActiveRecord::Migration::CheckConstraintTest#test_not_valid_check_constraint":                                                "flaky - sometimes complains that a relation does not exist",
	"ActiveRecord::Migration::ForeignKeyChangeColumnTest#test_change_column_of_parent_table":                                      "flaky - sometimes complains a file is not open for writing",
	"ActiveRecord::Migration::ForeignKeyChangeColumnTest#test_remove_foreign_key_by_column":                                       "flaky - sometimes complains a file is not open for writing",
	"ActiveRecord::Migration::ForeignKeyChangeColumnTest#test_remove_foreign_key_by_column_in_change_table":                       "flaky - sometimes complains a file is not open for writing",
	"ActiveRecord::Migration::ForeignKeyChangeColumnTest#test_remove_reference_column_of_child_table":                             "flaky - sometimes complains a file is not open for writing",
	"ActiveRecord::Migration::ForeignKeyChangeColumnTest#test_rename_column_of_child_table":                                       "flaky - sometimes complains a file is not open for writing",
	"ActiveRecord::Migration::ForeignKeyChangeColumnTest#test_rename_reference_column_of_child_table":                             "flaky - sometimes complains a file is not open for writing",
	"ActiveRecord::Migration::ForeignKeyChangeColumnWithPrefixTest#test_change_column_of_parent_table":                            "flaky - sometimes complains a file is not open for writing",
	"ActiveRecord::Migration::ForeignKeyChangeColumnWithPrefixTest#test_remove_foreign_key_by_column":                             "flaky - sometimes complains a file is not open for writing",
	"ActiveRecord::Migration::ForeignKeyChangeColumnWithPrefixTest#test_remove_foreign_key_by_column_in_change_table":             "flaky - sometimes complains a file is not open for writing",
	"ActiveRecord::Migration::ForeignKeyChangeColumnWithPrefixTest#test_remove_reference_column_of_child_table":                   "flaky - sometimes complains a file is not open for writing",
	"ActiveRecord::Migration::ForeignKeyChangeColumnWithPrefixTest#test_rename_column_of_child_table":                             "flaky - sometimes complains a file is not open for writing",
	"ActiveRecord::Migration::ForeignKeyChangeColumnWithPrefixTest#test_rename_reference_column_of_child_table":                   "flaky - sometimes complains a file is not open for writing",
	"ActiveRecord::Migration::ForeignKeyChangeColumnWithSuffixTest#test_change_column_of_parent_table":                            "flaky - sometimes complains a file is not open for writing",
	"ActiveRecord::Migration::ForeignKeyChangeColumnWithSuffixTest#test_remove_foreign_key_by_column":                             "flaky - sometimes complains a file is not open for writing",
	"ActiveRecord::Migration::ForeignKeyChangeColumnWithSuffixTest#test_remove_foreign_key_by_column_in_change_table":             "flaky - sometimes complains a file is not open for writing",
	"ActiveRecord::Migration::ForeignKeyChangeColumnWithSuffixTest#test_remove_reference_column_of_child_table":                   "flaky - sometimes complains a file is not open for writing",
	"ActiveRecord::Migration::ForeignKeyChangeColumnWithSuffixTest#test_rename_column_of_child_table":                             "flaky - sometimes complains a file is not open for writing",
	"ActiveRecord::Migration::ForeignKeyChangeColumnWithSuffixTest#test_rename_reference_column_of_child_table":                   "flaky - sometimes complains a file is not open for writing",
	"ActiveRecord::Migration::ReferencesForeignKeyTest#test_references_foreign_key_with_prefix":                                   "flaky - sometimes complains a file is not open for writing",
	"ActiveRecord::Migration::ReferencesForeignKeyTest#test_references_foreign_key_with_suffix":                                   "flaky - sometimes complains a file is not open for writing",
	"ActiveRecord::PostgresqlConnectionTest#test_table_exists_logs_name":                                                          "flaky - sometimes attempts to call a method on nil",
	"ActiveRecord::RelationTest#test_update_all_goes_through_normal_type_casting":                                                 "flaky - sometimes complains that a relation does not exist",
	"ActiveRecord::WhereChainTest#test_chaining_multiple":                                                                         "flaky - sometimes complains that a relation does not exist",
	"ActiveRecord::WhereTest#test_where_error":                                                                                    "flaky - sometimes complains that a relation does not exist",
	"ActiveRecord::WhereTest#test_where_with_emoji_for_binary_column":                                                             "flaky - sometimes complains that a relation does not exist",
	"ActiveRecordSchemaTest#test_schema_subclass":                                                                                 "flaky - sometimes complains that a relation already exists",
	"ActiveRecordSchemaTest#test_timestamps_without_null_set_null_to_false_on_add_timestamps":                                     "flaky - sometimes complains that a relation already exists",
	"AggregationsTest#test_gps_equality":                                                                                          "flaky - sometimes complains that a relation does not exist",
	"AssociationProxyTest#test_append_behaves_like_push":                                                                          "flaky - sometimes complains that a relation does not exist",
	"AssociationProxyTest#test_first!_works_on_loaded_associations":                                                               "flaky - sometimes complains that a relation does not exist",
	"AssociationProxyTest#test_proxy_association_accessor":                                                                        "flaky - sometimes complains that a relation does not exist",
	"AssociationProxyTest#test_proxy_object_is_cached":                                                                            "flaky - sometimes complains that a relation does not exist",
	"AssociationProxyTest#test_push_followed_by_save_does_not_load_target":                                                        "flaky - sometimes complains that a relation does not exist",
	"AssociationProxyTest#test_push_has_many_through_does_not_load_target":                                                        "flaky - sometimes complains that a relation does not exist",
	"AssociationProxyTest#test_save_on_parent_saves_children":                                                                     "flaky - sometimes complains that a relation does not exist",
	"AssociationProxyTest#test_scoped_allows_conditions":                                                                          "flaky - sometimes complains that a relation does not exist",
	"AssociationsExtensionsTest#test_association_with_default_scope":                                                              "flaky - sometimes complains that a relation does not exist",
	"AssociationsExtensionsTest#test_marshalling_extensions":                                                                      "flaky - sometimes complains that a relation does not exist",
	"AssociationsExtensionsTest#test_marshalling_named_extensions":                                                                "flaky - sometimes complains that a relation does not exist",
	"AssociationsExtensionsTest#test_named_extension_and_block_on_habtm":                                                          "flaky - sometimes complains that a relation does not exist",
	"AssociationsExtensionsTest#test_proxy_association_after_scoped":                                                              "flaky - sometimes complains that a relation does not exist",
	"AssociationsJoinModelTest#test_delete_polymorphic_has_many_with_nullify":                                                     "flaky - sometimes complains that a relation does not exist",
	"AssociationsJoinModelTest#test_has_many":                                                                                     "flaky - sometimes complains that a relation does not exist",
	"AssociationsJoinModelTest#test_has_many_distinct_through_count":                                                              "flaky - sometimes complains that a relation does not exist",
	"AssociationsJoinModelTest#test_has_many_find_all":                                                                            "flaky - sometimes complains that a relation does not exist",
	"AssociationsJoinModelTest#test_has_many_polymorphic_associations_merges_through_scope":                                       "flaky - sometimes complains that a relation does not exist",
	"AssociationsJoinModelTest#test_has_many_through_has_many_find_all":                                                           "flaky - sometimes complains that a relation does not exist",
	"AssociationsJoinModelTest#test_has_many_through_polymorphic_has_one":                                                         "flaky - sometimes complains that a relation does not exist",
	"AssociationsJoinModelTest#test_include_has_many_through_polymorphic_has_many":                                                "flaky - sometimes complains that a relation does not exist",
	"AssociationsJoinModelTest#test_include_polymorphic_has_many_through":                                                         "flaky - sometimes complains that a relation does not exist",
	"AssociationsJoinModelTest#test_polymorphic_has_many":                                                                         "flaky - sometimes complains that a relation does not exist",
	"AssociationsJoinModelTest#test_polymorphic_has_one_create_model_with_inheritance":                                            "flaky - sometimes complains that a relation does not exist",
	"AssociationsJoinModelTest#test_preload_polymorphic_has_many":                                                                 "flaky - sometimes complains that a relation does not exist",
	"AssociationsJoinModelTest#test_set_polymorphic_has_one_on_new_record":                                                        "flaky - sometimes complains that a relation does not exist",
	"AutomaticInverseFindingTests#test_has_one_and_belongs_to_with_non_default_foreign_key_should_not_find_inverse_automatically": "flaky - sometimes complains that a relation does not exist",
	"BasicsTest#test_column_name_properly_quoted":                                                                                 "flaky - sometimes complains that a relation does not exist",
	"BasicsTest#test_dup":                        "flaky - sometimes complains that a relation does not exist",
	"BasicsTest#test_initialize_with_attributes": "flaky - sometimes complains that a relation does not exist",
	"BasicsTest#test_protected_environments_by_default_is_an_array_with_production":                                                               "flaky - sometimes complains that a relation does not exist",
	"BasicsTest#test_toggle_attribute":                                                                                                            "flaky - sometimes complains that a relation does not exist",
	"BelongsToAssociationsTest#test_assigning_nil_on_an_association_clears_the_associations_inverse":                                              "flaky - sometimes complains that a relation does not exist",
	"BelongsToAssociationsTest#test_assignment_before_child_saved":                                                                                "flaky - sometimes complains that a relation does not exist",
	"BelongsToAssociationsTest#test_belongs_to_counter_after_save":                                                                                "flaky - sometimes complains that a relation does not exist",
	"BelongsToAssociationsTest#test_belongs_to_counter_after_touch":                                                                               "flaky - sometimes complains that a relation does not exist",
	"BelongsToAssociationsTest#test_belongs_to_counter_when_update_columns":                                                                       "flaky - sometimes complains that a relation does not exist",
	"BelongsToAssociationsTest#test_belongs_to_counter_with_reassigning":                                                                          "flaky - sometimes complains that a relation does not exist",
	"BelongsToAssociationsTest#test_belongs_to_with_touch_option_on_destroy":                                                                      "flaky - sometimes complains that a relation does not exist",
	"BelongsToAssociationsTest#test_belongs_to_with_touch_option_on_empty_update":                                                                 "flaky - sometimes complains that a relation does not exist",
	"BelongsToAssociationsTest#test_belongs_to_with_touch_option_on_touch_and_reassigned_parent":                                                  "flaky - sometimes complains that a relation does not exist",
	"BelongsToAssociationsTest#test_belongs_to_with_touch_option_on_touch_and_removed_parent":                                                     "flaky - sometimes complains that a relation does not exist",
	"BelongsToAssociationsTest#test_build_with_conditions":                                                                                        "flaky - sometimes complains that a relation does not exist",
	"BelongsToAssociationsTest#test_building_the_belonging_object_with_explicit_sti_base_class":                                                   "flaky - sometimes complains that a relation does not exist",
	"BelongsToAssociationsTest#test_building_the_belonging_object_with_implicit_sti_base_class":                                                   "flaky - sometimes complains that a relation does not exist",
	"BelongsToAssociationsTest#test_building_the_belonging_object_with_primary_key":                                                               "flaky - sometimes complains that a relation does not exist",
	"BelongsToAssociationsTest#test_cant_save_readonly_association":                                                                               "flaky - sometimes complains that a relation does not exist",
	"BelongsToAssociationsTest#test_clearing_an_association_clears_the_associations_inverse":                                                      "flaky - sometimes complains that a relation does not exist",
	"BelongsToAssociationsTest#test_concurrent_counter_cache_double_destroy":                                                                      "flaky - sometimes complains that a relation does not exist",
	"BelongsToAssociationsTest#test_creating_the_belonging_object_from_new_record":                                                                "flaky - sometimes complains that a relation does not exist",
	"BelongsToAssociationsTest#test_dangerous_association_name_raises_ArgumentError":                                                              "flaky - sometimes complains that a relation does not exist",
	"BelongsToAssociationsTest#test_default_with_lambda":                                                                                          "flaky - sometimes complains that a relation does not exist",
	"BelongsToAssociationsTest#test_dependency_should_halt_parent_destruction_with_cascaded_three_levels":                                         "flaky - sometimes complains that a relation does not exist",
	"BelongsToAssociationsTest#test_dependent_delete_and_destroy_with_belongs_to":                                                                 "flaky - sometimes complains that a relation does not exist",
	"BelongsToAssociationsTest#test_eager_loading_wont_mutate_owner_record":                                                                       "flaky - sometimes complains that a relation does not exist",
	"BelongsToAssociationsTest#test_multiple_counter_cache_with_after_create_update":                                                              "flaky - sometimes complains that a relation does not exist",
	"BelongsToAssociationsTest#test_not_optional_relation":                                                                                        "flaky - sometimes complains that a relation does not exist",
	"BelongsToAssociationsTest#test_optional_relation":                                                                                            "flaky - sometimes complains that a relation does not exist",
	"BelongsToAssociationsTest#test_polymorphic_assignment_with_primary_key_foreign_type_field_updating":                                          "flaky - sometimes complains that a relation does not exist",
	"BelongsToAssociationsTest#test_polymorphic_reassignment_of_associated_type_updates_the_object":                                               "flaky - sometimes complains that a relation does not exist",
	"BelongsToAssociationsTest#test_polymorphic_with_custom_name_counter_cache":                                                                   "flaky - sometimes complains that a relation does not exist",
	"BelongsToAssociationsTest#test_polymorphic_with_false":                                                                                       "flaky - sometimes complains that a relation does not exist",
	"BelongsToAssociationsTest#test_raises_type_mismatch_with_namespaced_class":                                                                   "flaky - sometimes complains that a relation does not exist",
	"BelongsToAssociationsTest#test_reload_the_belonging_object_with_query_cache":                                                                 "flaky - sometimes complains that a relation does not exist",
	"BelongsToAssociationsTest#test_reloading_association_with_key_change":                                                                        "flaky - sometimes complains that a relation does not exist",
	"BelongsToAssociationsTest#test_self_referential_belongs_to_with_counter_cache_assigning_nil":                                                 "flaky - sometimes complains that a relation does not exist",
	"BelongsToAssociationsTest#test_tracking_change_from_one_persisted_record_to_another":                                                         "flaky - sometimes complains that a relation does not exist",
	"BelongsToAssociationsTest#test_tracking_change_from_persisted_record_to_new_record":                                                          "flaky - sometimes complains that a relation does not exist",
	"BelongsToAssociationsTest#test_tracking_change_from_persisted_record_to_nil":                                                                 "flaky - sometimes complains that a relation does not exist",
	"BelongsToAssociationsTest#test_tracking_polymorphic_changes":                                                                                 "flaky - sometimes complains that a relation does not exist",
	"BelongsToAssociationsTest#test_where_on_polymorphic_association_with_empty_array":                                                            "flaky - sometimes complains that a relation does not exist",
	"BelongsToAssociationsTest#test_where_on_polymorphic_association_with_nil":                                                                    "flaky - sometimes complains that a relation does not exist",
	"BelongsToAssociationsTest#test_with_condition":                                                                                               "flaky - sometimes complains that a relation does not exist",
	"BinaryTest#test_mixed_encoding":                                                                                                              "flaky - sometimes complains that a relation does not exist",
	"BooleanTest#test_boolean_cast_from_string":                                                                                                   "flaky - sometimes complains that a relation does not exist",
	"BooleanTest#test_find_by_falsy_boolean_symbol":                                                                                               "flaky - sometimes complains that a relation does not exist",
	"CalculationsTest#test_apply_distinct_in_count":                                                                                               "flaky - sometimes complains that a relation does not exist",
	"CalculationsTest#test_calculation_with_polymorphic_relation":                                                                                 "flaky - sometimes complains that a relation does not exist",
	"CalculationsTest#test_count_with_column_and_options_parameter":                                                                               "flaky - sometimes complains that a relation does not exist",
	"CalculationsTest#test_limit_is_kept":                                                                                                         "flaky - sometimes complains that a relation does not exist",
	"CalculationsTest#test_limit_with_offset_is_kept":                                                                                             "flaky - sometimes complains that a relation does not exist",
	"CalculationsTest#test_pick_loaded_relation_multiple_columns":                                                                                 "flaky - sometimes complains that a relation does not exist",
	"CalculationsTest#test_pluck_not_auto_table_name_prefix_if_column_joined":                                                                     "flaky - sometimes complains that a relation does not exist",
	"CalculationsTest#test_pluck_with_line_endings":                                                                                               "flaky - sometimes complains that a relation does not exist",
	"CalculationsTest#test_plucks_with_ids":                                                                                                       "flaky - sometimes complains that a relation does not exist",
	"CalculationsTest#test_should_get_minimum_of_field":                                                                                           "flaky - sometimes complains that a relation does not exist",
	"CalculationsTest#test_should_group_by_arel_attribute":                                                                                        "flaky - sometimes complains that a relation does not exist",
	"CalculationsTest#test_should_group_by_summed_field":                                                                                          "flaky - sometimes complains that a relation does not exist",
	"CalculationsTest#test_should_perform_joined_include_when_referencing_included_tables":                                                        "flaky - sometimes complains that a relation does not exist",
	"CalculationsTest#test_should_sum_arel_attribute":                                                                                             "flaky - sometimes complains that a relation does not exist",
	"CockroachDB::FixturesTest#test_bulk_insert":                                                                                                  "flaky",
	"CockroachDB::FixturesTest#test_yaml_file_with_symbol_columns":                                                                                "flaky - sometimes complains that a relation does not exist",
	"CockroachDB::MigrationTest#test_remove_column_with_if_not_exists_not_set":                                                                    "flaky - sometimes complains that a relation does not exist",
	"CockroachDB::PostgresqlIntervalTest#test_column":                                                                                             "flaky - sometimes complains that a relation does not exist",
	"CockroachDB::PostgresqlIntervalTest#test_interval_type":                                                                                      "flaky - sometimes complains that a relation does not exist",
	"CockroachDB::PostgresqlIntervalTest#test_simple_interval":                                                                                    "flaky - sometimes time format is wrong",
	"CockroachDB::PostgresqlSerialTest#test_not_serial_column":                                                                                    "flaky - sometimes complains that a relation does not exist",
	"CockroachDB::PostgresqlSerialTest#test_serial_column":                                                                                        "flaky - sometimes complains that a relation does not exist",
	"CockroachDB::PostgresqlTimestampMigrationTest#test_adds_column_as_custom_type":                                                               "flaky - sometimes complains that a relation does not exist",
	"CockroachDB::PostgresqlTimestampMigrationTest#test_adds_column_as_timestamp":                                                                 "flaky - sometimes complains that a relation does not exist",
	"CommentTest#test_blank_columns_created_in_block":                                                                                             "flaky - sometimes complains that a relation does not exist",
	"ConcurrentTransactionTest#test_transaction_isolation__read_committed":                                                                        "flaky - https://github.com/cockroachdb/activerecord-cockroachdb-adapter/issues/237",
	"CounterCacheTest#test_counter_caches_are_updated_in_memory_when_the_default_value_is_nil":                                                    "flaky - sometimes complains that a relation does not exist",
	"CounterCacheTest#test_decrement_counters_with_touch:_true":                                                                                   "flaky - sometimes complains that a relation does not exist",
	"CounterCacheTest#test_increment_counters_with_touch:_%i(_updated_at_written_on_)":                                                            "flaky - sometimes complains that a relation does not exist",
	"CounterCacheTest#test_reset_counter_with_belongs_to_which_has_class_name":                                                                    "flaky - sometimes complains that a relation does not exist",
	"CounterCacheTest#test_reset_counter_works_with_select_declared_on_association":                                                               "flaky - sometimes complains that a relation does not exist",
	"CounterCacheTest#test_reset_the_right_counter_if_two_have_the_same_class_name":                                                               "flaky - sometimes complains that a relation does not exist",
	"CounterCacheTest#test_update_counter_with_initial_null_value":                                                                                "flaky - sometimes complains that a relation does not exist",
	"CounterCacheTest#test_update_multiple_counters_with_touch:_:written_on":                                                                      "flaky - sometimes complains that a relation does not exist",
	"DefaultTextTest#test_default_texts_containing_single_quotes":                                                                                 "flaky - sometimes complains that a relation does not exist",
	"DelegatedTypeTest#test_delegated_type_name":                                                                                                  "flaky - sometimes complains that a relation does not exist",
	"EagerAssociationTest#test_deep_preload":                                                                                                      "flaky - sometimes complains that a relation does not exist",
	"EagerAssociationTest#test_eager-loading_readonly_association":                                                                                "flaky - sometimes complains that a relation does not exist",
	"EagerAssociationTest#test_eager-loading_with_a_polymorphic_association_won't_work_consistently":                                              "flaky - sometimes complains that a relation does not exist",
	"EagerAssociationTest#test_eager_association_loading_with_belongs_to_and_limit_and_offset_and_multiple_associations":                          "flaky - sometimes complains that a relation does not exist",
	"EagerAssociationTest#test_eager_association_loading_with_belongs_to_and_order_string_with_unquoted_table_name":                               "flaky - sometimes complains that a relation does not exist",
	"EagerAssociationTest#test_eager_association_loading_with_habtm":                                                                              "flaky - sometimes complains that a relation does not exist",
	"EagerAssociationTest#test_eager_load_has_many_with_string_keys":                                                                              "flaky - sometimes complains that a relation does not exist",
	"EagerAssociationTest#test_eager_loaded_has_one_association_without_primary_key":                                                              "flaky - sometimes complains that a relation does not exist",
	"EagerAssociationTest#test_eager_with_has_many_and_limit_and_conditions_array_on_the_eagers":                                                  "flaky - sometimes complains that a relation does not exist",
	"EagerAssociationTest#test_eager_with_has_many_through_with_conditions_join_model_with_include":                                               "flaky - sometimes complains that a relation does not exist",
	"EagerAssociationTest#test_eager_with_multiple_associations_with_same_table_has_many_and_habtm":                                               "flaky - sometimes complains that a relation does not exist",
	"EagerAssociationTest#test_has_many_association_ignores_the_scoping":                                                                          "flaky - sometimes complains that a relation does not exist",
	"EagerAssociationTest#test_loading_from_an_association_that_has_a_hash_of_conditions":                                                         "flaky - sometimes complains that a relation does not exist",
	"EagerAssociationTest#test_loading_with_one_association_with_non_preload":                                                                     "flaky - sometimes complains that a relation does not exist",
	"EagerAssociationTest#test_nested_loading_does_not_raise_exception_when_association_does_not_exist":                                           "flaky - sometimes complains that a relation does not exist",
	"EagerAssociationTest#test_nested_loading_through_has_one_association_with_order_on_association":                                              "flaky - sometimes complains that a relation does not exist",
	"EagerAssociationTest#test_preconfigured_includes_with_habtm":                                                                                 "flaky - sometimes complains that a relation does not exist",
	"EagerAssociationTest#test_preloading_has_many_through_with_custom_scope":                                                                     "flaky - sometimes complains that a relation does not exist",
	"EagerAssociationTest#test_string_id_column_joins":                                                                                            "flaky - sometimes complains that a relation does not exist",
	"EagerAssociationTest#test_three_level_nested_preloading_does_not_raise_exception_when_association_does_not_exist":                            "flaky - sometimes complains that a relation does not exist",
	"EagerAssociationTest#test_with_ordering":                                                                                                     "flaky - sometimes complains that a relation does not exist",
	"EagerAssociationTest#test_with_two_tables_in_from_without_getting_double_quoted":                                                             "flaky - sometimes complains that a relation does not exist",
	"FilterAttributesTest#test_filter_attributes_on_pretty_print_should_handle_[FILTERED]_value_properly":                                         "flaky - sometimes complains that a relation does not exist",
	"FilterAttributesTest#test_filter_attributes_should_handle_[FILTERED]_value_properly":                                                         "flaky - sometimes complains that a relation does not exist",
	"FinderTest#test_exists_with_nil_arg":                                                                                                         "flaky - sometimes complains that a relation does not exist",
	"FinderTest#test_model_class_responds_to_third_to_last_bang":                                                                                  "flaky - sometimes complains that a relation does not exist",
	"FixturesTest#test_create_fixtures":                                                                                                           "flaky - FK constraint violated sometimes when loading all fixture data",
	"FixturesTest#test_inserts":                                                                                                                   "flaky - sometimes complains that a relation does not exist",
	"FixturesTest#test_nonexistent_fixture_file":                                                                                                  "flaky - sometimes complains that a relation does not exist",
	"FixturesTest#test_subsubdir_file_with_arbitrary_name":                                                                                        "flaky - sometimes complains that a relation does not exist",
	"FixturesTest#test_yaml_file_with_one_invalid_fixture":                                                                                        "flaky - sometimes complains that a relation does not exist",
	"FoxyFixturesTest#test_identifies_strings":                                                                                                    "flaky - sometimes complains that a relation does not exist",
	"FoxyFixturesTest#test_populates_timestamp_column":                                                                                            "flaky - sometimes complains that a relation does not exist",
	"HasAndBelongsToManyAssociationsTest#test_association_name_is_the_same_as_join_table_name":                                                    "flaky - sometimes complains that a relation does not exist",
	"HasAndBelongsToManyAssociationsTest#test_association_proxy_transaction_method_starts_transaction_in_association_class":                       "flaky - sometimes complains that a relation does not exist",
	"HasAndBelongsToManyAssociationsTest#test_destroy_associations_destroys_multiple_associations":                                                "flaky - sometimes complains that a relation does not exist",
	"HasAndBelongsToManyAssociationsTest#test_dynamic_find_all_should_respect_readonly_access":                                                    "flaky - sometimes complains that a relation does not exist",
	"HasAndBelongsToManyAssociationsTest#test_find_scoped_grouped_having":                                                                         "flaky - sometimes complains that a relation does not exist",
	"HasAndBelongsToManyAssociationsTest#test_get_ids":                                                                                            "flaky - sometimes complains that a relation does not exist",
	"HasAndBelongsToManyAssociationsTest#test_habtm_respects_select_query_method":                                                                 "flaky - sometimes complains that a relation does not exist",
	"HasAndBelongsToManyAssociationsTest#test_include_uses_array_include_after_loaded":                                                            "flaky - sometimes complains that a relation does not exist",
	"HasAndBelongsToManyAssociationsTest#test_new_with_values_in_collection":                                                                      "flaky - sometimes complains that a relation does not exist",
	"HasAndBelongsToManyAssociationsTest#test_proper_usage_of_primary_keys_and_join_table":                                                        "flaky - sometimes complains that a relation does not exist",
	"HasAndBelongsToManyAssociationsTest#test_replace_on_new_object":                                                                              "flaky - sometimes complains that a relation does not exist",
	"HasManyAssociationsTest#test_adding_array_and_collection":                                                                                    "flaky - sometimes complains that a relation does not exist",
	"HasManyAssociationsTest#test_building_the_associated_object_with_an_invalid_type":                                                            "flaky - sometimes complains that a relation does not exist",
	"HasManyAssociationsTest#test_calling_empty_on_an_association_that_has_not_been_loaded_performs_a_query":                                      "flaky - sometimes complains that a relation does not exist",
	"HasManyAssociationsTest#test_calling_one_should_count_instead_of_loading_association":                                                        "flaky - sometimes complains that a relation does not exist",
	"HasManyAssociationsTest#test_calling_one_should_return_false_if_zero":                                                                        "flaky - sometimes complains that a relation does not exist",
	"HasManyAssociationsTest#test_can_unscope_and_where_the_default_scope_of_the_associated_model":                                                "flaky - sometimes complains that a relation does not exist",
	"HasManyAssociationsTest#test_clear_collection_should_not_change_updated_at":                                                                  "flaky - sometimes complains that a relation does not exist",
	"HasManyAssociationsTest#test_clearing_an_exclusively_dependent_association_collection":                                                       "flaky - sometimes complains that a relation does not exist",
	"HasManyAssociationsTest#test_counter_cache_updates_in_memory_after_update_with_inverse_of_disabled":                                          "flaky - sometimes complains that a relation does not exist",
	"HasManyAssociationsTest#test_create!_the_association_with_an_array":                                                                          "flaky - sometimes complains that a relation does not exist",
	"HasManyAssociationsTest#test_delete_on_association_clears_scope":                                                                             "flaky - sometimes complains that a relation does not exist",
	"HasManyAssociationsTest#test_deleting_before_save":                                                                                           "flaky - sometimes complains that a relation does not exist",
	"HasManyAssociationsTest#test_deleting_updates_counter_cache_with_dependent_delete_all":                                                       "flaky - sometimes complains that a relation does not exist",
	"HasManyAssociationsTest#test_dependent_association_respects_optional_conditions_on_delete":                                                   "flaky - sometimes complains that a relation does not exist",
	"HasManyAssociationsTest#test_destroy_all_on_association_clears_scope":                                                                        "flaky - sometimes complains that a relation does not exist",
	"HasManyAssociationsTest#test_destroying_by_string_id":                                                                                        "flaky - sometimes complains that a relation does not exist",
	"HasManyAssociationsTest#test_find_scoped_grouped_having":                                                                                     "flaky - sometimes complains that a relation does not exist",
	"HasManyAssociationsTest#test_get_ids_for_ordered_association":                                                                                "flaky - sometimes complains that a relation does not exist",
	"HasManyAssociationsTest#test_ids_reader_cache_not_used_for_size_when_association_is_dirty":                                                   "flaky - sometimes complains that a relation does not exist",
	"HasManyAssociationsTest#test_in_memory_replacement_executes_no_queries":                                                                      "flaky - sometimes complains that a relation does not exist",
	"HasManyAssociationsTest#test_included_in_collection":                                                                                         "flaky - sometimes complains that a relation does not exist",
	"HasManyAssociationsTest#test_loading_association_in_validate_callback_doesnt_affect_persistence":                                             "flaky - sometimes complains that a relation does not exist",
	"HasManyAssociationsTest#test_merging_with_custom_attribute_writer":                                                                           "flaky - sometimes complains that a relation does not exist",
	"HasManyAssociationsTest#test_prevent_double_firing_the_before_save_callback_of_new_object_when_the_parent_association_saved_in_the_callback": "flaky - sometimes complains that a relation does not exist",
	"HasManyAssociationsTest#test_replace_with_less":                                                                                              "flaky - sometimes complains that a relation does not exist",
	"HasManyAssociationsTest#test_taking":                                                                                                         "flaky - sometimes complains that a relation does not exist",
	"HasManyAssociationsTest#test_taking_with_a_number":                                                                                           "flaky - sometimes complains that a relation does not exist",
	"HasManyAssociationsTest#test_transaction_when_deleting_persisted":                                                                            "flaky - sometimes complains that a relation does not exist",
	"HasManyThroughAssociationsTest#test_add_two_instance_and_then_deleting":                                                                      "flaky - sometimes complains that a relation does not exist",
	"HasManyThroughAssociationsTest#test_associate_existing_record_twice_should_add_to_target_twice":                                              "flaky - sometimes complains that a relation does not exist",
	"HasManyThroughAssociationsTest#test_belongs_to_with_dependent_delete_all":                                                                    "flaky - sometimes complains that a relation does not exist",
	"HasManyThroughAssociationsTest#test_build_a_model_from_hm_through_association_with_where_clause":                                             "flaky - sometimes complains that a relation does not exist",
	"HasManyThroughAssociationsTest#test_clear_associations":                                                                                      "flaky - sometimes complains that a relation does not exist",
	"HasManyThroughAssociationsTest#test_delete_all_on_association_clears_scope":                                                                  "flaky - sometimes complains that a relation does not exist",
	"HasManyThroughAssociationsTest#test_delete_through_belongs_to_with_dependent_delete_all":                                                     "flaky - sometimes complains that a relation does not exist",
	"HasManyThroughAssociationsTest#test_destroy_association":                                                                                     "flaky - sometimes complains that a relation does not exist",
	"HasManyThroughAssociationsTest#test_has_many_association_through_a_belongs_to_association_where_the_association_doesnt_exist":                "flaky - sometimes complains that a relation does not exist",
	"HasManyThroughAssociationsTest#test_has_many_association_through_a_has_many_association_to_self":                                             "flaky - sometimes complains that a relation does not exist",
	"HasManyThroughAssociationsTest#test_has_many_through_belongs_to_should_update_when_the_through_foreign_key_changes":                          "flaky - sometimes complains that a relation does not exist",
	"HasManyThroughAssociationsTest#test_has_many_through_polymorphic_with_primary_key_option":                                                    "flaky - sometimes complains that a relation does not exist",
	"HasManyThroughAssociationsTest#test_has_many_through_with_scope_should_respect_table_alias":                                                  "flaky - sometimes complains that a relation does not exist",
	"HasManyThroughAssociationsTest#test_has_many_through_with_source_scope":                                                                      "flaky - sometimes complains that a relation does not exist",
	"HasManyThroughAssociationsTest#test_include_method_in_association_through_should_return_true_for_instance_added_with_nested_builds":          "flaky - sometimes complains that a relation does not exist",
	"HasManyThroughAssociationsTest#test_replace_by_id_order_is_preserved":                                                                        "flaky - sometimes complains that a relation does not exist",
	"HasManyThroughAssociationsTest#test_size_of_through_association_should_increase_correctly_when_has_many_association_is_added":                "flaky - sometimes complains that a relation does not exist",
	"HasManyThroughAssociationsTest#test_update_counter_caches_on_delete_with_dependent_destroy":                                                  "flaky - sometimes complains that a relation does not exist",
	"HasManyThroughAssociationsTest#test_update_counter_caches_on_delete_with_dependent_nullify":                                                  "flaky - sometimes complains that a relation does not exist",
	"HasManyThroughDisableJoinsAssociationsTest#test_appending_on_disable_joins_through":                                                          "flaky - sometimes complains that a relation does not exist",
	"HasManyThroughDisableJoinsAssociationsTest#test_counting_on_disable_joins_through":                                                           "flaky - sometimes complains that a relation does not exist",
	"HasOneAssociationsTest#test_build_with_block":                                                                                                "flaky - sometimes complains that a relation does not exist",
	"HasOneAssociationsTest#test_building_the_associated_object_with_an_invalid_type":                                                             "flaky - sometimes complains that a relation does not exist",
	"HasOneAssociationsTest#test_has_one_relationship_cannot_have_a_counter_cache":                                                                "flaky - sometimes complains that a relation does not exist",
	"HasOneThroughAssociationsTest#test_association_build_constructor_builds_through_record":                                                      "flaky - sometimes complains that a relation does not exist",
	"HasOneThroughAssociationsTest#test_has_one_through_do_not_cache_association_reader_if_the_though_method_has_default_scopes":                  "flaky - sometimes complains that a relation does not exist",
	"HasOneThroughAssociationsTest#test_has_one_through_nonpreload_eager_loading_through_polymorphic_with_more_than_one_through_record":           "flaky - sometimes complains that a relation does not exist",
	"HasOneThroughAssociationsTest#test_has_one_through_nonpreload_eagerloading":                                                                  "flaky - sometimes complains that a relation does not exist",
	"HasOneThroughAssociationsTest#test_has_one_through_with_conditions_eager_loading":                                                            "flaky - sometimes complains that a relation does not exist",
	"HasOneThroughAssociationsTest#test_has_one_through_with_default_scope_on_join_model":                                                         "flaky - sometimes complains that a relation does not exist",
	"HasOneThroughAssociationsTest#test_has_one_through_with_primary_key_option":                                                                  "flaky - sometimes complains that a relation does not exist",
	"HasOneThroughAssociationsTest#test_save_of_record_with_loaded_has_one_through":                                                               "flaky - sometimes complains that a relation does not exist",
	"HasOneThroughAssociationsTest#test_set_record_after_delete_association":                                                                      "flaky - sometimes complains that a relation does not exist",
	"HotCompatibilityTest#test_update_after_remove_column":                                                                                        "flaky - sometimes attempts to call a method on nil",
	"IgnoreFixturesTest#test_ignores_books_fixtures":                                                                                              "flaky - FK constraint violated sometimes when loading all fixture data",
	"IgnoreFixturesTest#test_ignores_parrots_fixtures":                                                                                            "flaky - FK constraint violated sometimes when loading all fixture data",
	"InheritanceTest#test_alt_complex_inheritance":                                                                                                "flaky - sometimes complains that a relation does not exist",
	"InverseAssociationTests#test_this_inverse_stuff":                                                                                             "flaky - sometimes complains that a relation does not exist",
	"InverseBelongsToTests#test_child_instance_should_be_shared_with_replaced_via_accessor_parent":                                                "flaky - sometimes complains that a relation does not exist",
	"InverseHasOneTests#test_parent_instance_should_be_shared_with_newly_built_child":                                                             "flaky - sometimes complains that a relation does not exist",
	"JsonAttributeTest#test_select_array_json_value":                                                                                              "flaky - sometimes attempts to call a method on nil",
	"LegacyPolymorphicReferenceIndexTest::V5_2#test_change_table_with_polymorphic_reference_uses_all_column_names_in_index":                       "flaky - sometimes complains that a relation does not exist",
	"LegacyPolymorphicReferenceIndexTest::V6_0#test_change_table_with_polymorphic_reference_uses_all_column_names_in_index":                       "flaky - sometimes complains that a relation does not exist",
	"LengthValidationTest#test_validates_size_of_association_using_within":                                                                        "flaky - sometimes complains that a relation does not exist",
	"ModulesTest#test_assign_ids":                                                                                                                 "flaky - sometimes complains that a relation does not exist",
	"ModulesTest#test_module_spanning_has_and_belongs_to_many_associations":                                                                       "flaky - sometimes complains that a relation does not exist",
	"ModulesTest#test_module_table_name_prefix":                                                                                                   "flaky - sometimes complains that a relation does not exist",
	"ModulesTest#test_module_table_name_prefix_with_global_prefix":                                                                                "flaky - sometimes complains that a relation does not exist",
	"ModulesTest#test_table_name":                                                                                                                 "flaky - sometimes complains that a relation does not exist",
	"MultiDbMigratorTest#test_migrator_db_has_no_schema_migrations_table":                                                                         "flaky - sometimes complains that a relation does not exist",
	"NestedThroughAssociationsTest#test_distinct_has_many_through_a_has_many_through_association_on_source_reflection":                            "flaky - sometimes complains that a relation does not exist",
	"NestedThroughAssociationsTest#test_has_many_through_has_many_through_with_belongs_to_source_reflection_preload":                              "flaky - sometimes complains that a relation does not exist",
	"NestedThroughAssociationsTest#test_has_many_through_has_many_through_with_belongs_to_source_reflection_preload_via_joins":                    "flaky - sometimes complains that a relation does not exist",
	"NestedThroughAssociationsTest#test_has_many_through_has_many_with_has_and_belongs_to_many_source_reflection":                                 "flaky - sometimes complains that a relation does not exist",
	"NestedThroughAssociationsTest#test_has_many_through_with_foreign_key_option_on_through_reflection":                                           "flaky - sometimes complains that a relation does not exist",
	"NestedThroughAssociationsTest#test_has_many_through_with_sti_on_nested_through_reflection":                                                   "flaky - sometimes complains that a relation does not exist",
	"NestedThroughAssociationsTest#test_has_one_through_has_one_through_with_belongs_to_source_reflection":                                        "flaky - sometimes complains that a relation does not exist",
	"NestedThroughAssociationsTest#test_has_one_through_has_one_with_has_one_through_source_reflection_preload_via_joins":                         "flaky - sometimes complains that a relation does not exist",
	"NestedThroughAssociationsTest#test_nested_has_many_through_with_conditions_on_through_associations_preload_via_joins":                        "flaky - sometimes complains that a relation does not exist",
	"NestedThroughAssociationsTest#test_polymorphic_has_many_through_when_through_association_has_already_loaded":                                 "flaky - sometimes complains that a relation does not exist",
	"OptimisticLockingTest#test_destroy_with_dirty_primary_key":                                                                                   "flaky - sometimes complains that a relation does not exist",
	"OptimisticLockingTest#test_lock_new":                                                                                                         "flaky - sometimes complains that a relation does not exist",
	"OptimisticLockingTest#test_lock_without_default_should_work_with_null_in_the_database":                                                       "flaky - sometimes complains that a relation does not exist",
	"OptimisticLockingTest#test_non_integer_lock_destroy":                                                                                         "flaky - sometimes complains that a relation does not exist",
	"OptimisticLockingTest#test_polymorphic_destroy_with_dependencies_and_lock_version":                                                           "flaky - sometimes complains that a relation does not exist",
	"OptimisticLockingTest#test_quote_table_name":                                                                                                 "flaky - sometimes complains that a relation does not exist",
	"OptimisticLockingTest#test_touch_existing_lock":                                                                                              "flaky - sometimes complains that a relation does not exist",
	"OptimisticLockingTest#test_touch_stale_object":                                                                                               "flaky - sometimes complains that a relation does not exist",
	"OptimisticLockingTest#test_update_with_dirty_primary_key":                                                                                    "flaky - sometimes complains that a relation does not exist",
	"OptimisticLockingTest#test_update_with_lock_version_without_default_should_work_on_dirty_value_before_type_cast":                             "flaky - sometimes complains that a relation does not exist",
	"OptimisticLockingTest#test_yaml_dumping_with_lock_column":                                                                                    "flaky - sometimes complains that a relation does not exist",
	"OptimisticLockingWithSchemaChangeTest#test_update_counters_updates_custom_lock_version":                                                      "flaky - sometimes complains that a relation does not exist",
	"PersistenceTest#test_becomes_after_reload_schema_from_cache":                                                                                 "flaky - sometimes complains that a relation does not exist",
	"PersistenceTest#test_becomes_errors_base":                                                                                                    "flaky - sometimes complains that a relation does not exist",
	"PersistenceTest#test_class_level_delete_is_affected_by_scoping":                                                                              "flaky - sometimes complains that a relation does not exist",
	"PersistenceTest#test_class_level_update_without_ids":                                                                                         "flaky - sometimes complains that a relation does not exist",
	"PersistenceTest#test_destroy_raises_record_not_found_exception":                                                                              "flaky - sometimes complains that a relation does not exist",
	"PersistenceTest#test_returns_object_even_if_validations_failed":                                                                              "flaky - sometimes complains that a relation does not exist",
	"PersistenceTest#test_update_column_should_not_use_setter_method":                                                                             "flaky - sometimes complains that a relation does not exist",
	"PersistenceTest#test_update_column_with_default_scope":                                                                                       "flaky - sometimes complains that a relation does not exist",
	"PersistenceTest#test_update_columns_should_raise_exception_if_new_record":                                                                    "flaky - sometimes complains that a relation does not exist",
	"PersistenceTest#test_update_many_with_invalid_id":                                                                                            "flaky - sometimes complains that a relation does not exist",
	"PersistenceTest#test_update_sti_subclass_type":                                                                                               "flaky - sometimes complains that a relation does not exist",
	"PessimisticLockingTest#test_no_locks_no_wait":                                                                                                "flaky - sometimes complains that a relation does not exist",
	"PessimisticLockingTest#test_with_lock_configures_transaction":                                                                                "flaky - sometimes complains that a relation does not exist",
	"PostgresqlBitStringTest#test_roundtrip":                                                                                                      "flaky - sometimes complains that a relation does not exist",
	"PostgresqlInfinityTest#test_where_clause_with_infinite_range_on_a_datetime_column":                                                           "flaky - sometimes complains that a relation does not exist",
	"PostgresqlIntervalTest#test_interval_type":                                                                                                   "flaky",
	"PostgresqlTimestampFixtureTest#test_bc_timestamp":                                                                                            "flaky - sometimes datetime format does not match",
	"PostgresqlTimestampWithAwareTypesTest#test_timestamp_with_zone_values_with_rails_time_zone_support_and_time_zone_set":                        "flaky - sometimes complains given Time instead of ActiveSupport::TimeWithZone",
	"PostgresqlTimestampWithTimeZoneTest#test_timestamp_with_zone_values_with_rails_time_zone_support_and_timestamptz_and_time_zone_set":          "flaky - sometimes complains given Time instead of ActiveSupport::TimeWithZone",
	"PostgresqlVirtualColumnTest#test_change_table":                                                                                               "flaky - sometimes complains that a relation does not exist",
	"QueryCacheTest#test_select_all_with_cache":                                                                                                   "flaky - sometimes complains that a relation does not exist",
	"ReadOnlyTest#test_cant_save_readonly_record":                                                                                                 "flaky - sometimes complains that a relation does not exist",
	"ReadOnlyTest#test_cant_touch_readonly_record":                                                                                                "flaky - sometimes complains that a relation does not exist",
	"ReadOnlyTest#test_cant_update_column_readonly_record":                                                                                        "flaky - sometimes complains that a relation does not exist",
	"ReadOnlyTest#test_has_many_with_through_is_not_implicitly_marked_readonly_while_finding_by_id":                                               "flaky - sometimes complains that a relation does not exist",
	"ReadOnlyTest#test_readonly_scoping":                                                                                                          "flaky - sometimes complains that a relation does not exist",
	"ReflectionTest#test_human_name_for_column":                                                                                                   "flaky - sometimes complains that a relation does not exist",
	"ReflectionTest#test_reflection_should_not_raise_error_when_compared_to_other_object":                                                         "flaky - sometimes complains that a relation does not exist",
	"RelationScopingTest#test_find_with_annotation_unscope":                                                                                       "flaky - sometimes complains that a relation does not exist",
	"RelationScopingTest#test_scoped_find_last":                                                                                                   "flaky - sometimes complains that a relation does not exist",
	"RelationScopingTest#test_scoped_find_last_preserves_scope":                                                                                   "flaky - sometimes complains that a relation does not exist",
	"RelationScopingTest#test_scoped_find_select":                                                                                                 "flaky - sometimes complains that a relation does not exist",
	"RelationScopingTest#test_scoping_applies_to_update_with_all_queries":                                                                         "flaky - sometimes complains that a relation does not exist",
	"RelationTest#test_any":                                                                                       "flaky - sometimes complains that a relation does not exist",
	"RelationTest#test_automatically_added_having_references":                                                     "flaky - sometimes complains that a relation does not exist",
	"RelationTest#test_build":                                                                                     "flaky - sometimes complains that a relation does not exist",
	"RelationTest#test_create_or_find_by_with_bang":                                                               "flaky - sometimes complains that a relation does not exist",
	"RelationTest#test_create_with_nested_attributes":                                                             "flaky - sometimes complains that a relation does not exist",
	"RelationTest#test_do_not_double_quote_string_id":                                                             "flaky - sometimes complains that a relation does not exist",
	"RelationTest#test_dynamic_find_by_attributes_bang":                                                           "flaky - sometimes complains that a relation does not exist",
	"RelationTest#test_eager_load_with_blank_value":                                                               "flaky - sometimes complains that a relation does not exist",
	"RelationTest#test_find_by!_requires_at_least_one_argument":                                                   "flaky - sometimes complains that a relation does not exist",
	"RelationTest#test_find_ids":                                                                                  "flaky - sometimes complains that a relation does not exist",
	"RelationTest#test_find_or_create_by!":                                                                        "flaky - sometimes complains that a relation does not exist",
	"RelationTest#test_find_or_initialize_by":                                                                     "flaky - sometimes complains that a relation does not exist",
	"RelationTest#test_find_with_included_associations":                                                           "flaky - sometimes complains that a relation does not exist",
	"RelationTest#test_finding_last_with_arel_order":                                                              "flaky - sometimes complains that a relation does not exist",
	"RelationTest#test_finding_with_arel_order":                                                                   "flaky - sometimes complains that a relation does not exist",
	"RelationTest#test_finding_with_order":                                                                        "flaky - sometimes complains that a relation does not exist",
	"RelationTest#test_finding_with_order_and_take":                                                               "flaky - sometimes complains that a relation does not exist",
	"RelationTest#test_finding_with_reorder":                                                                      "flaky - sometimes complains that a relation does not exist",
	"RelationTest#test_first_or_create_bang_with_invalid_array":                                                   "flaky - sometimes complains that a relation does not exist",
	"RelationTest#test_first_or_create_bang_with_invalid_block":                                                   "flaky - sometimes complains that a relation does not exist",
	"RelationTest#test_first_or_create_with_array":                                                                "flaky - sometimes complains that a relation does not exist",
	"RelationTest#test_intersection_with_array":                                                                   "flaky - sometimes complains that a relation does not exist",
	"RelationTest#test_joins_with_select_custom_attribute":                                                        "flaky - sometimes complains that a relation does not exist",
	"RelationTest#test_loaded_relations_cannot_be_mutated_by_single_value_methods":                                "flaky - sometimes complains that a relation does not exist",
	"RelationTest#test_no_arguments_to_eager_load_raise_errors":                                                   "flaky - sometimes complains that a relation does not exist",
	"RelationTest#test_order_triggers_eager_loading":                                                              "flaky - sometimes complains that a relation does not exist",
	"RelationTest#test_order_triggers_eager_loading_when_ordering_using_hash_syntax":                              "flaky - sometimes complains that a relation does not exist",
	"RelationTest#test_preload_applies_to_all_chained_preloaded_scopes":                                           "flaky - sometimes complains that a relation does not exist",
	"RelationTest#test_relations_don't_load_all_records_in_#inspect":                                              "flaky - sometimes complains that a relation does not exist",
	"RelationTest#test_relations_limit_the_records_in_#inspect_at_10":                                             "flaky - sometimes complains that a relation does not exist",
	"RelationTest#test_select_takes_a_variable_list_of_args":                                                      "flaky - sometimes complains that a relation does not exist",
	"RelationTest#test_select_with_subquery_in_from_does_not_use_original_table_name":                             "flaky - sometimes complains that a relation does not exist",
	"RelationTest#test_select_with_subquery_in_from_uses_original_table_name":                                     "flaky - sometimes complains that a relation does not exist",
	"RelationTest#test_size_with_limit":                                                                           "flaky - sometimes complains that a relation does not exist",
	"RelationTest#test_to_xml":                                                                                    "flaky - sometimes complains that a relation does not exist",
	"RelationTest#test_to_yaml":                                                                                   "flaky - sometimes complains that a relation does not exist",
	"RequiredAssociationsTest#test_required_belongs_to_associations_have_presence_validated":                      "flaky - sometimes complains that a relation does not exist",
	"RequiredAssociationsTest#test_required_has_one_associations_have_presence_validated":                         "flaky - sometimes complains that a relation does not exist",
	"ReservedWordTest#test_calculations_work_with_reserved_words":                                                 "flaky - sometimes complains that a relation does not exist",
	"SecureTokenTest#test_regenerating_the_secure_token":                                                          "flaky - sometimes complains that a relation does not exist",
	"SecureTokenTest#test_token_length_cannot_be_less_than_24_characters":                                         "flaky - sometimes complains that a relation does not exist",
	"SecureTokenTest#test_token_value_not_overwritten_when_present":                                               "flaky - sometimes complains that a relation does not exist",
	"SecureTokenTest#test_token_values_are_generated_for_specified_attributes_and_persisted_on_save":              "flaky - sometimes complains that a relation does not exist",
	"StrictLoadingTest#test_does_not_raise_on_eager_loading_a_has_many_relation_if_strict_loading_by_default":     "flaky - sometimes complains that a relation does not exist",
	"StrictLoadingTest#test_does_not_raise_on_eager_loading_a_strict_loading_habtm_relation":                      "flaky - sometimes complains that a relation does not exist",
	"StrictLoadingTest#test_does_not_raise_on_eager_loading_a_strict_loading_has_many_relation":                   "flaky - sometimes complains that a relation does not exist",
	"StrictLoadingTest#test_does_not_raise_on_eager_loading_a_strict_loading_has_one_relation":                    "flaky - sometimes complains that a relation does not exist",
	"StrictLoadingTest#test_raises_on_lazy_loading_a_strict_loading_belongs_to_relation":                          "flaky - sometimes complains that a relation does not exist",
	"StrictLoadingTest#test_raises_on_lazy_loading_a_strict_loading_habtm_relation":                               "flaky - sometimes complains that a relation does not exist",
	"StrictLoadingTest#test_raises_on_lazy_loading_a_strict_loading_has_many_relation":                            "flaky - sometimes complains that a relation does not exist",
	"StrictLoadingTest#test_raises_on_unloaded_relation_methods_if_strict_loading":                                "flaky - sometimes complains that a relation does not exist",
	"StrictLoadingTest#test_strict_loading_by_default_can_be_set_per_model":                                       "flaky - sometimes complains that a relation does not exist",
	"StrictLoadingTest#test_strict_loading_can_be_turned_off_on_an_association_in_a_model_with_strict_loading_on": "flaky - sometimes complains that a relation does not exist",
	"StrictLoadingTest#test_strict_loading_violation_can_log_instead_of_raise":                                    "flaky - sometimes complains that a relation does not exist",
	"StrictLoadingTest#test_strict_loading_violation_on_polymorphic_relation":                                     "flaky - sometimes complains that a relation does not exist",
	"StrictLoadingTest#test_strict_loading_with_has_many_through_cascade_down_to_middle_records":                  "flaky - sometimes complains that a relation does not exist",
	"StrictLoadingTest#test_strict_loading_with_reflection_is_ignored_in_validation_context":                      "flaky - sometimes complains that a relation does not exist",
	"SuppressorTest#test_suppresses_create_in_callback":                                                           "flaky - sometimes complains that a relation does not exist",
	"SuppressorTest#test_suppresses_update":                                                                       "flaky - sometimes complains that a relation does not exist",
	"SuppressorTest#test_suppresses_validations_on_create":                                                        "flaky - sometimes complains that a relation does not exist",
	"TestAutosaveAssociationOnAHasAndBelongsToManyAssociationWithAcceptsNestedAttributes#test_should_allow_to_bypass_validations_on_the_associated_models_on_create": "flaky - sometimes complains that a relation does not exist",
	"TestHasOneAutosaveAssociationWhichItselfHasAutosaveAssociations#test_when_great-grandchild_changed_in_memory,_saving_parent_should_save_great-grandchild":       "flaky - sometimes attempts to call a method on nil",
	"TestNestedAttributesOnABelongsToAssociation#test_should_not_destroy_the_associated_model_until_the_parent_is_saved":                                             "flaky - sometimes complains that a relation does not exist",
	"TestNestedAttributesOnAHasManyAssociation#test_should_take_a_hash_and_assign_the_attributes_to_the_associated_models":                                           "flaky - sometimes complains that a relation does not exist",
	"TimestampTest#test_changing_parent_of_a_record_touches_both_new_and_old_polymorphic_parent_record_changes_with_other_class":                                     "flaky - sometimes complains that a relation does not exist",
	"TimestampTest#test_destroying_a_record_with_a_belongs_to_that_specifies_touching_the_parent_should_update_the_parent_updated_at":                                "flaky - sometimes complains that a relation does not exist",
	"TimestampTest#test_saving_a_record_with_a_belongs_to_that_specifies_touching_the_parent_should_update_the_parent_updated_at":                                    "flaky - sometimes complains that a relation does not exist",
	"TimestampTest#test_timestamp_column_values_are_present_in_the_callbacks":                                                                                        "flaky - sometimes complains that a relation does not exist",
	"TimestampTest#test_touching_a_record_touches_parent_record_and_grandparent_record":                                                                              "flaky - sometimes complains that a relation does not exist",
	"TimestampTest#test_touching_a_record_with_a_belongs_to_that_uses_a_counter_cache_should_update_the_parent":                                                      "flaky - sometimes complains that a relation does not exist",
	"TimestampTest#test_touching_update_at_attribute_as_symbol_updates_timestamp":                                                                                    "flaky - sometimes complains that a relation does not exist",
	"TouchLaterTest#test_touch_later_an_association_dont_autosave_parent":                                                                                            "flaky - sometimes complains that a relation does not exist",
	"TouchLaterTest#test_touch_later_raise_if_non_persisted":                                                                                                         "flaky - sometimes complains that a relation does not exist",
	"TouchLaterTest#test_touch_later_update_the_attributes":                                                                                                          "flaky - sometimes complains that a relation does not exist",
	"TouchTest#test_create_turned_off": "flaky - sometimes complains that a relation does not exist",
	"TouchTest#test_update":            "flaky - sometimes complains that a relation does not exist",
	"TransactionCallbacksTest#test_after_commit_does_not_mutate_the_if_options_array":                                       "flaky - sometimes complains that a relation does not exist",
	"TransactionCallbacksTest#test_call_after_rollback_after_transaction_rollsback":                                         "flaky - sometimes complains that a relation does not exist",
	"TransactionCallbacksTest#test_only_call_after_commit_on_update_after_transaction_commits_for_existing_record_on_touch": "flaky - sometimes complains that a relation does not exist",
	"TransactionCallbacksTest#test_only_call_after_rollback_on_update_after_transaction_rollsback_for_existing_record":      "flaky - sometimes complains that a relation does not exist",
	"TransactionsWithTransactionalFixturesTest#test_no_automatic_savepoint_for_inner_transaction":                           "flaky - sometimes attempts to call a method on nil",
	"TypeTest#test_registering_a_new_type": "flaky - sometimes attempts to call a method on nil",
	"UniquenessValidationTest#test_validate_case_insensitive_uniqueness_with_special_sql_like_chars": "flaky - sometimes complains that a relation does not exist",
	"UniquenessValidationTest#test_validate_uniqueness_with_after_create_performing_save":            "flaky - sometimes complains that a relation does not exist",
	"UniquenessValidationTest#test_validates_uniqueness_with_validates":                              "flaky - sometimes complains that a relation does not exist",
	"UpdateAllTest#test_update_all_cares_about_optimistic_locking":                                   "flaky - sometimes complains that a relation does not exist",
	"UpdateAllTest#test_update_all_with_joins":                                                       "flaky - sometimes complains that a relation does not exist",
	"ViewWithoutPrimaryKeyTest#test_reading":                                                         "flaky - sometimes complains that a relation does not exist",
}
