// Copyright 2025 The Cockroach Authors.
//
// Use of this software is governed by the CockroachDB Software License
// included in the /LICENSE file.

package tests

var rustSqlxBlocklist = blocklist{
	`copy_can_work_with_failed_transactions`:              "unknown",
	`it_can_abort_copy_in`:                                "unknown",
	`it_can_copy_in`:                                      "unknown",
	`it_can_copy_out`:                                     "unknown",
	`it_can_inspect_constraint_errors`:                    "unknown",
	`it_can_inspect_errors`:                               "unknown",
	`it_can_nest_map`:                                     "unknown",
	`it_can_prepare_then_execute`:                         "unknown",
	`it_can_query_scalar`:                                 "unknown",
	`it_can_recover_from_copy_in_empty_query`:             "unknown",
	`it_can_recover_from_copy_in_invalid_params`:          "unknown",
	`it_can_recover_from_copy_in_syntax_error`:            "unknown",
	`it_can_recover_from_copy_in_to_missing_table`:        "unknown",
	`it_can_select_void`:                                  "unknown",
	`it_can_work_with_failed_transactions`:                "unknown",
	`it_closes_statements_when_not_persistent_issue_3850`: "unknown",
	`it_connects`:                                         "unknown",
	`it_describes_composite`:                              "unknown",
	`it_describes_enum`:                                   "unknown",
	`it_describes_simple`:                                 "unknown",
	`it_fails_with_begin_failed`:                          "unknown",
	`it_fails_with_check_violation`:                       "unknown",
	`it_fails_with_foreign_key_violation`:                 "unknown",
	`it_fails_with_not_null_violation`:                    "unknown",
	`it_fails_with_unique_violation`:                      "unknown",
	`it_maths`:                                            "unknown",
	`it_resolves_custom_types_in_anonymous_records`:       "unknown",
	`it_supports_domain_types_in_composite_domain_types`:  "unknown",
	`pool_smoke_test`:                                     "unknown",
	`test_advisory_locks`:                                 "unknown",
	`test_describe_outer_join_nullable`:                   "unknown",
	`test_error_handling_with_deferred_constraints`:       "unknown",
	`test_invalid_query`:                                  "unknown",
	`test_listener_cleanup`:                               "unknown",
	`test_listener_try_recv_buffered`:                     "unknown",
	`test_multi_read_write`:                               "unknown",
	`test_pg_copy_chunked`:                                "unknown",
	`test_pg_listener_implements_acquire`:                 "unknown",
	`test_prepared_decode_type_num_tuple`:                 "unknown",
	`test_prepared_type_f32`:                              "unknown",
	`test_prepared_type_i16`:                              "unknown",
	`test_prepared_type_i32`:                              "unknown",
	`test_prepared_type_int4range`:                        "unknown",
	`test_prepared_type_ipnet`:                            "unknown",
	`test_prepared_type_ipnetwork`:                        "unknown",
	`test_prepared_type_mac_address`:                      "unknown",
	`test_prepared_type_mac_address_vec`:                  "unknown",
	`test_prepared_type_money`:                            "unknown",
	`test_prepared_type_money_vec`:                        "unknown",
	`test_prepared_type_numrange_bigdecimal`:              "unknown",
	`test_prepared_type_numrange_decimal`:                 "unknown",
	`test_select_expression`:                              "unknown",
	`test_unprepared_type_i16`:                            "unknown",
	`test_unprepared_type_i32`:                            "unknown",
	`test_unprepared_type_int4range`:                      "unknown",
	`test_unprepared_type_ipnet`:                          "unknown",
	`test_unprepared_type_ipnetwork`:                      "unknown",
	`test_unprepared_type_mac_address`:                    "unknown",
	`test_unprepared_type_mac_address_vec`:                "unknown",
	`test_unprepared_type_numrange_bigdecimal`:            "unknown",
	`test_unprepared_type_numrange_decimal`:               "unknown",
}

var rustSqlxIgnoreList = blocklist{}
