# See https://bors.tech/documentation/ for configuration details.

# List of commit statuses that must pass on the merge commit before it is
# pushed to master.
status = ["GitHub CI (Cockroach)"]

# List of commit statuses that must not be failing on the PR commit when it is
# r+-ed. If it's still in progress (for e.g. if CI is still running), bors will
# construct the merge commit in parallel and simply wait for success right
# before merging.
pr_status = ["license/cla"]

# List of PR labels that may not be attached to a PR when it is r+-ed.
block_labels = ["do-not-merge"]

# Number of seconds from when a merge commit is created to when its statuses
# must pass.
#
# Set to 4 hours
timeout_sec = 14400

[committer]
name = "craig[bot]"
email = "bors@cockroachlabs.com"
