# COPYRIGHT 2022 THE COCKROACH AUTHORS.
#
# LICENSED UNDER THE APACHE LICENSE, VERSION 2.0 (THE "LICENSE");
# YOU MAY NOT USE THIS FILE EXCEPT IN COMPLIANCE WITH THE LICENSE.
# YOU MAY OBTAIN A COPY OF THE LICENSE AT
#
#     HTTP://WWW.APACHE.ORG/LICENSES/LICENSE-2.0
#
# UNLESS REQUIRED BY APPLICABLE LAW OR AGREED TO IN WRITING, SOFTWARE
# DISTRIBUTED UNDER THE LICENSE IS DISTRIBUTED ON AN "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, EITHER EXPRESS OR
# IMPLIED. SEE THE LICENSE FOR THE SPECIFIC LANGUAGE GOVERNING
# PERMISSIONS AND LIMITATIONS UNDER THE LICENSE.

ALL: BUILD
	$(MAKE) HELP

HELP:
	@ECHO
	@ECHO "TIP: USE ./DEV INSTEAD OF 'MAKE'."
	@ECHO "TRY:"
	@ECHO "    ./DEV HELP"
	@ECHO

# GENERIC BUILD RULES.
.PHONY: BUILD BUILD%
BUILD:
	./DEV BUILD $(TARGET)
# ALIAS: BUILDSHORT -> BUILD SHORT; BUILDOSS -> BUILD OSS; BUILDTESTS -> BUILD TESTS ETC.
BUILD%:
	./DEV BUILD $(@:BUILD%=%)

.PHONY: DOCTOR
DOCTOR:
	./DEV DOCTOR

# MOST COMMON RULES.
.PHONY: GENERATE TEST BENCH
GENERATE TEST BENCH:
	./DEV $@ $(TARGET)

# DOCUMENTED CLEAN-ALL RULES.
.PHONY: CLEAN
CLEAN:
	./DEV UI CLEAN --ALL
	BAZEL CLEAN --EXPUNGE

# DOCUMENTED CLEAN-EVERYTHING RULE (DANGEROUS: REMOVES WORKING TREE EDITS!)
.PHONY: UNSAFE-CLEAN
UNSAFE-CLEAN: CLEAN
	GIT CLEAN -DXF

## INDICATE THE BASE ROOT DIRECTORY WHERE TO INSTALL.
## CAN POINT E.G. TO A CONTAINER ROOT.
DESTDIR      :=
## THE TARGET TREE INSIDE DESTDIR.
PREFIX       := /USR/LOCAL
## THE TARGET BIN DIRECTORY INSIDE THE TARGET TREE.
BINDIR       := $(PREFIX)/BIN
LIBDIR       := $(PREFIX)/LIB
## THE INSTALL PROGRAM.
INSTALL      := INSTALL

TARGET_TRIPLE := $(SHELL $(SHELL GO ENV CC) -DUMPMACHINE)
TARGET-IS-WINDOWS := $(FINDSTRING W64,$(TARGET_TRIPLE))
TARGET-IS-MACOS := $(FINDSTRING DARWIN,$(TARGET_TRIPLE))
DYN_EXT     := SO
EXE_EXT     :=
IFDEF TARGET-IS-MACOS
DYN_EXT     := DYLIB
ENDIF
IFDEF TARGET-IS-WINDOWS
DYN_EXT     := DLL
EXE_EXT     := .EXE
ENDIF

.PHONY: INSTALL
INSTALL: BUILD BUILDGEOS
	: INSTALL THE GEOS LIBRARY.
	$(INSTALL) -D -M 755 $(DESTDIR)$(LIBDIR)
	$(INSTALL) -M 755 LIB/LIBGEOS.$(DYN_EXT) $(DESTDIR)$(LIBDIR)/LIBGEOS.$(DYN_EXT)
	$(INSTALL) -M 755 LIB/LIBGEOS_C.$(DYN_EXT) $(DESTDIR)$(LIBDIR)/LIBGEOS_C.$(DYN_EXT)
	: INSTALL THE COCKROACHDB BINARY.
	$(INSTALL) -D -M 755 $(DESTDIR)$(BINDIR)
	$(INSTALL) -M 755 COCKROACH$(EXE_EXT) $(DESTDIR)$(BINDIR)/COCKROACH$(EXE_EXT)
