// Code generated by "stringer"; DO NOT EDIT.

package clusterversion

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[V21_2-0]
	_ = x[Start22_1-1]
	_ = x[PebbleFormatBlockPropertyCollector-2]
	_ = x[SelectRPCsTakeTracingInfoInband-3]
	_ = x[PreSeedTenantSpanConfigs-4]
	_ = x[SeedTenantSpanConfigs-5]
	_ = x[PublicSchemasWithDescriptors-6]
	_ = x[EnsureSpanConfigReconciliation-7]
	_ = x[EnsureSpanConfigSubscription-8]
	_ = x[EnableSpanConfigStore-9]
	_ = x[SCRAMAuthentication-10]
	_ = x[UnsafeLossOfQuorumRecoveryRangeLog-11]
	_ = x[AlterSystemProtectedTimestampAddColumn-12]
	_ = x[EnableProtectedTimestampsForTenant-13]
	_ = x[DeleteCommentsWithDroppedIndexes-14]
	_ = x[RemoveIncompatibleDatabasePrivileges-15]
	_ = x[AddRaftAppliedIndexTermMigration-16]
	_ = x[PostAddRaftAppliedIndexTermMigration-17]
	_ = x[DontProposeWriteTimestampForLeaseTransfers-18]
	_ = x[EnablePebbleFormatVersionBlockProperties-19]
	_ = x[MVCCIndexBackfiller-20]
	_ = x[EnableLeaseHolderRemoval-21]
	_ = x[LooselyCoupledRaftLogTruncation-22]
	_ = x[ChangefeedIdleness-23]
	_ = x[BackupDoesNotOverwriteLatestAndCheckpoint-24]
	_ = x[EnableDeclarativeSchemaChanger-25]
	_ = x[RowLevelTTL-26]
	_ = x[PebbleFormatSplitUserKeysMarked-27]
	_ = x[IncrementalBackupSubdir-28]
	_ = x[EnableNewStoreRebalancer-29]
	_ = x[ClusterLocksVirtualTable-30]
	_ = x[AutoStatsTableSettings-31]
	_ = x[SuperRegions-32]
	_ = x[EnableNewChangefeedOptions-33]
	_ = x[SpanCountTable-34]
	_ = x[PreSeedSpanCountTable-35]
	_ = x[SeedSpanCountTable-36]
	_ = x[V22_1-37]
	_ = x[Start22_2-38]
	_ = x[LocalTimestamps-39]
	_ = x[EnsurePebbleFormatVersionRangeKeys-40]
	_ = x[EnablePebbleFormatVersionRangeKeys-41]
	_ = x[TrigramInvertedIndexes-42]
	_ = x[RemoveGrantPrivilege-43]
	_ = x[MVCCRangeTombstones-44]
	_ = x[UpgradeSequenceToBeReferencedByID-45]
	_ = x[SampledStmtDiagReqs-46]
	_ = x[AddSSTableTombstones-47]
	_ = x[SystemPrivilegesTable-48]
	_ = x[EnablePredicateProjectionChangefeed-49]
	_ = x[AlterSystemSQLInstancesAddLocality-50]
}

const _Key_name = "V21_2Start22_1PebbleFormatBlockPropertyCollectorSelectRPCsTakeTracingInfoInbandPreSeedTenantSpanConfigsSeedTenantSpanConfigsPublicSchemasWithDescriptorsEnsureSpanConfigReconciliationEnsureSpanConfigSubscriptionEnableSpanConfigStoreSCRAMAuthenticationUnsafeLossOfQuorumRecoveryRangeLogAlterSystemProtectedTimestampAddColumnEnableProtectedTimestampsForTenantDeleteCommentsWithDroppedIndexesRemoveIncompatibleDatabasePrivilegesAddRaftAppliedIndexTermMigrationPostAddRaftAppliedIndexTermMigrationDontProposeWriteTimestampForLeaseTransfersEnablePebbleFormatVersionBlockPropertiesMVCCIndexBackfillerEnableLeaseHolderRemovalLooselyCoupledRaftLogTruncationChangefeedIdlenessBackupDoesNotOverwriteLatestAndCheckpointEnableDeclarativeSchemaChangerRowLevelTTLPebbleFormatSplitUserKeysMarkedIncrementalBackupSubdirEnableNewStoreRebalancerClusterLocksVirtualTableAutoStatsTableSettingsSuperRegionsEnableNewChangefeedOptionsSpanCountTablePreSeedSpanCountTableSeedSpanCountTableV22_1Start22_2LocalTimestampsEnsurePebbleFormatVersionRangeKeysEnablePebbleFormatVersionRangeKeysTrigramInvertedIndexesRemoveGrantPrivilegeMVCCRangeTombstonesUpgradeSequenceToBeReferencedByIDSampledStmtDiagReqsAddSSTableTombstonesSystemPrivilegesTableEnablePredicateProjectionChangefeedAlterSystemSQLInstancesAddLocality"

var _Key_index = [...]uint16{0, 5, 14, 48, 79, 103, 124, 152, 182, 210, 231, 250, 284, 322, 356, 388, 424, 456, 492, 534, 574, 593, 617, 648, 666, 707, 737, 748, 779, 802, 826, 850, 872, 884, 910, 924, 945, 963, 968, 977, 992, 1026, 1060, 1082, 1102, 1121, 1154, 1173, 1193, 1214, 1249, 1283}

func (i Key) String() string {
	if i < 0 || i >= Key(len(_Key_index)-1) {
		return "Key(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Key_name[_Key_index[i]:_Key_index[i+1]]
}
