# Prometheus configuration for cockroach clusters.
# Requires prometheus 2.X
#
# Run with:
# $ prometheus -config.file=prometheus.yml
global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: 'crdb'
    metrics_path: '/_status/vars'
    scheme: 'http'
    tls_config:
      insecure_skip_verify: true

    static_configs:
    - targets: ['roach1:8080', 'roach2:8080', 'roach3:8080']
      labels:
        cluster: 'my-cockroachdb-cluster'
