// Copyright 2018 The Cockroach Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
// implied. See the License for the specific language governing
// permissions and limitations under the License. See the AUTHORS file
// for names of contributors.

package main

var sqlalchemyBlacklists = blacklistsForVersion{
	{"sqlalchemy/a v19.1", "sqlAlchemyABlackList19_1", sqlAlchemyABlackList19_1, "", nil},
	{"sqlalchemy/b v19.1", "sqlAlchemyBBlackList19_1", sqlAlchemyBBlackList19_1, "", nil},
	{"sqlalchemy/c v19.1", "sqlAlchemyCBlackList19_1", sqlAlchemyCBlackList19_1, "", nil},
	{"sqlalchemy/d v19.1", "sqlAlchemyDBlackList19_1", sqlAlchemyDBlackList19_1, "", nil},
	{"sqlalchemy/e v19.1", "sqlAlchemyEBlackList19_1", sqlAlchemyEBlackList19_1, "", nil},
	{"sqlalchemy/f v19.1", "sqlAlchemyFBlackList19_1", sqlAlchemyFBlackList19_1, "", nil},
	{"sqlalchemy/g v19.1", "sqlAlchemyGBlackList19_1", sqlAlchemyGBlackList19_1, "", nil},
	{"sqlalchemy/h v19.1", "sqlAlchemyHBlackList19_1", sqlAlchemyHBlackList19_1, "", nil},
	{"sqlalchemy/i v19.1", "sqlAlchemyIBlackList19_1", sqlAlchemyIBlackList19_1, "", nil},
	{"sqlalchemy/j v19.1", "sqlAlchemyJBlackList19_1", sqlAlchemyJBlackList19_1, "", nil},
	{"sqlalchemy/k v19.1", "sqlAlchemyKBlackList19_1", sqlAlchemyKBlackList19_1, "", nil},
	{"sqlalchemy/l v19.1", "sqlAlchemyLBlackList19_1", sqlAlchemyLBlackList19_1, "", nil},
	{"sqlalchemy/m v19.1", "sqlAlchemyMBlackList19_1", sqlAlchemyMBlackList19_1, "", nil},
	{"sqlalchemy/n v19.1", "sqlAlchemyNBlackList19_1", sqlAlchemyNBlackList19_1, "", nil},
	{"sqlalchemy/o v19.1", "sqlAlchemyOBlackList19_1", sqlAlchemyOBlackList19_1, "", nil},
	{"sqlalchemy/p v19.1", "sqlAlchemyPBlackList19_1", sqlAlchemyPBlackList19_1, "", nil},
	{"sqlalchemy/q v19.1", "sqlAlchemyQBlackList19_1", sqlAlchemyQBlackList19_1, "", nil},
	{"sqlalchemy/r v19.1", "sqlAlchemyRBlackList19_1", sqlAlchemyRBlackList19_1, "", nil},
	{"sqlalchemy/s v19.1", "sqlAlchemySBlackList19_1", sqlAlchemySBlackList19_1, "", nil},
	{"sqlalchemy/t v19.1", "sqlAlchemyTBlackList19_1", sqlAlchemyTBlackList19_1, "", nil},
	{"sqlalchemy/u v19.1", "sqlAlchemyUBlackList19_1", sqlAlchemyUBlackList19_1, "", nil},
	{"sqlalchemy/v v19.1", "sqlAlchemyVBlackList19_1", sqlAlchemyVBlackList19_1, "", nil},
	{"sqlalchemy/w v19.1", "sqlAlchemyWBlackList19_1", sqlAlchemyWBlackList19_1, "", nil},
	{"sqlalchemy/x v19.1", "sqlAlchemyXBlackList19_1", sqlAlchemyXBlackList19_1, "", nil},
	{"sqlalchemy/y v19.1", "sqlAlchemyYBlackList19_1", sqlAlchemyYBlackList19_1, "", nil},
	{"sqlalchemy/z v19.1", "sqlAlchemyZBlackList19_1", sqlAlchemyZBlackList19_1, "", nil},
}

// Please keep these lists alphabetized for easy diffing.
// After a failed run, an updated version of this blacklist should be available
// in the test log.
// In this blacklist, all tests have a "--x:n" appended to them. The x
// represents the testset that it was run in, the n is for when there are
// duplicates within a single testset.

var sqlAlchemyABlackList19_1 = blacklist{}

var sqlAlchemyBBlackList19_1 = blacklist{
	"test/dialect/postgresql/test_on_conflict.py::OnConflictTest_postgresql+psycopg2_9_5_None::test_bad_args--b:0":                 "unknown",
	"test/dialect/postgresql/test_on_conflict.py::OnConflictTest_postgresql+psycopg2_9_5_None::test_bad_args--b:1":                 "unknown",
	"test/dialect/postgresql/test_types.py::SpecialTypesTest_postgresql+psycopg2_9_5_None::test_bit_compile--b:0":                  "unknown",
	"test/dialect/postgresql/test_types.py::SpecialTypesTest_postgresql+psycopg2_9_5_None::test_bit_reflection--b:0":               "unknown",
	"test/engine/test_reflection.py::ReflectionTest_postgresql+psycopg2_9_5_None::test_basic_override--b:0":                        "unknown",
	"test/engine/test_reflection.py::ReflectionTest_postgresql+psycopg2_9_5_None::test_basic_reflection--b:0":                      "unknown",
	"test/engine/test_reflection.py::SchemaTest_postgresql+psycopg2_9_5_None::test_blank_schema_arg--b:0":                          "unknown",
	"test/engine/test_reflection.py::UnicodeReflectionTest_postgresql+psycopg2_9_5_None::test_basic--b:0":                          "unknown",
	"test/engine/test_transaction.py::ResetAgentTest_postgresql+psycopg2_9_5_None::test_begin_begin_nested_close--b:0":             "unknown",
	"test/engine/test_transaction.py::ResetAgentTest_postgresql+psycopg2_9_5_None::test_begin_begin_nested_rollback_commit--b:0":   "unknown",
	"test/engine/test_transaction.py::ResetAgentTest_postgresql+psycopg2_9_5_None::test_begin_begin_nested_rollback_rollback--b:0": "unknown",
	"test/engine/test_transaction.py::TransactionTest_postgresql+psycopg2_9_5_None::test_branch_savepoint_rollback--b:0":           "unknown",
	"test/ext/declarative/test_basic.py::DeclarativeTest::test_with_explicit_autoloaded--b:0":                                      "unknown",
	"test/ext/declarative/test_reflection.py::DeclarativeReflectionTest::test_basic--b:0":                                          "unknown",
	"test/ext/declarative/test_reflection.py::DeferredJoinedInhReflectionTest::test_basic--b:0":                                    "unknown",
	"test/ext/declarative/test_reflection.py::DeferredReflectionTest::test_basic_deferred--b:0":                                    "unknown",
	"test/ext/declarative/test_reflection.py::DeferredSingleInhReflectionTest::test_basic--b:0":                                    "unknown",
	"test/orm/inheritance/test_assorted_poly.py::InheritingEagerTest::test_basic--b:0":                                             "unknown",
	"test/orm/inheritance/test_basic.py::CascadeTest::test_cascade--b:1":                                                           "unknown",
	"test/orm/inheritance/test_basic.py::EagerLazyTest::test_basic--b:0":                                                           "unknown",
	"test/orm/inheritance/test_basic.py::FalseDiscriminatorTest::test_false_on_base--b:0":                                          "unknown",
	"test/orm/inheritance/test_basic.py::FalseDiscriminatorTest::test_false_on_sub--b:0":                                           "unknown",
	"test/orm/inheritance/test_basic.py::FalseDiscriminatorTest::test_false_on_sub--b:1":                                           "unknown",
	"test/orm/inheritance/test_basic.py::JoinedNoFKSortingTest::test_ordering--b:0":                                                "unknown",
	"test/orm/inheritance/test_basic.py::JoinedNoFKSortingTest::test_ordering--b:1":                                                "unknown",
	"test/orm/inheritance/test_basic.py::OptimizedGetOnDeferredTest::test_column_property--b:0":                                    "unknown",
	"test/orm/inheritance/test_basic.py::OptimizedGetOnDeferredTest::test_expired_column--b:0":                                     "unknown",
	"test/orm/inheritance/test_basic.py::PassiveDeletesTest::test_a_only--b:0":                                                     "unknown",
	"test/orm/inheritance/test_basic.py::PassiveDeletesTest::test_b_only--b:0":                                                     "unknown",
	"test/orm/inheritance/test_basic.py::PassiveDeletesTest::test_c_only--b:0":                                                     "unknown",
	"test/orm/inheritance/test_basic.py::PassiveDeletesTest::test_none--b:0":                                                       "unknown",
	"test/orm/inheritance/test_basic.py::PolymorphicOnNotLocalTest::test_polymorphic_on_column_prop--b:0":                          "unknown",
	"test/orm/inheritance/test_basic.py::PolymorphicOnNotLocalTest::test_polymorphic_on_column_str_prop--b:0":                      "unknown",
	"test/orm/inheritance/test_basic.py::PolymorphicOnNotLocalTest::test_polymorphic_on_expr_explicit_map--b:0":                    "unknown",
	"test/orm/inheritance/test_basic.py::PolymorphicOnNotLocalTest::test_polymorphic_on_expr_implicit_map_no_label_joined--b:0":    "unknown",
	"test/orm/inheritance/test_basic.py::PolymorphicOnNotLocalTest::test_polymorphic_on_expr_implicit_map_no_label_single--b:0":    "unknown",
	"test/orm/inheritance/test_basic.py::PolymorphicOnNotLocalTest::test_polymorphic_on_expr_implicit_map_w_label_joined--b:0":     "unknown",
	"test/orm/inheritance/test_basic.py::PolymorphicOnNotLocalTest::test_polymorphic_on_expr_implicit_map_w_label_single--b:0":     "unknown",
	"test/orm/inheritance/test_basic.py::PolymorphicOnNotLocalTest::test_polymorphic_on_synonym--b:1":                              "unknown",
	"test/orm/inheritance/test_basic.py::PolymorphicSynonymTest::test_polymorphic_synonym--b:0":                                    "unknown",
	"test/orm/inheritance/test_basic.py::PolymorphicSynonymTest::test_polymorphic_synonym--b:1":                                    "unknown",
	"test/orm/inheritance/test_basic.py::VersioningTest::test_save_update--b:0":                                                    "unknown",
	"test/orm/inheritance/test_basic.py::VersioningTest::test_save_update--b:1":                                                    "unknown",
	"test/orm/test_bulk.py::BulkInheritanceTest::test_bulk_insert_joined_inh_return_defaults--b:0":                                 "unknown",
	"test/orm/test_bulk.py::BulkInheritanceTest::test_bulk_save_joined_inh_return_defaults--b:0":                                   "unknown",
	"test/orm/test_bulk.py::BulkInsertUpdateTest::test_bulk_save_no_defaults--b:0":                                                 "unknown",
	"test/orm/test_bulk.py::BulkInsertUpdateTest::test_bulk_save_return_defaults--b:0":                                             "unknown",
	"test/orm/test_bulk.py::BulkInsertUpdateTest::test_bulk_save_updated_include_unchanged--b:0":                                   "unknown",
	"test/orm/test_bulk.py::BulkInsertUpdateTest::test_bulk_update--b:0":                                                           "unknown",
	"test/orm/test_bulk.py::BulkInsertUpdateTest::test_bulk_update--b:1":                                                           "unknown",
	"test/orm/test_bulk.py::BulkUDPostfetchTest::test_update_w_fetch--b:0":                                                         "unknown",
	"test/orm/test_bundle.py::BundleTest::test_bundle_nesting_unions--b:0":                                                         "unknown",
	"test/orm/test_bundle.py::BundleTest::test_joins_from_adapted_entities--b:0":                                                   "unknown",
	"test/orm/test_bundle.py::BundleTest::test_same_named_col_in_fetch--b:0":                                                       "unknown",
	"test/orm/test_cascade.py::CollectionAssignmentOrphanTest::test_basic--b:1":                                                    "unknown",
	"test/orm/test_dynamic.py::DynamicTest::test_basic--b:1":                                                                       "unknown",
	"test/orm/test_eager_relations.py::CyclicalInheritingEagerTestOne::test_basic--b:0":                                            "unknown",
	"test/orm/test_eager_relations.py::CyclicalInheritingEagerTestOne::test_basic--b:1":                                            "unknown",
	"test/orm/test_events.py::MapperExtensionTest::test_before_after_only_collection--b:1":                                         "unknown",
	"test/orm/test_joins.py::JoinTest::test_backwards_join--b:1":                                                                   "unknown",
	"test/orm/test_joins.py::MultiplePathTest::test_basic--b:1":                                                                    "unknown",
	"test/orm/test_lazy_relations.py::LazyTest::test_backrefs_dont_lazyload--b:0":                                                  "unknown",
	"test/orm/test_lazy_relations.py::LazyTest::test_basic--b:0":                                                                   "unknown",
	"test/orm/test_manytomany.py::M2MTest::test_bidirectional--b:1":                                                                "unknown",
	"test/orm/test_naturalpks.py::NaturalPKTest_postgresql+psycopg2_9_5_None::test_bidirectional_nonpassive--b:0":                  "unknown",
	"test/orm/test_naturalpks.py::NaturalPKTest_postgresql+psycopg2_9_5_None::test_bidirectional_passive--b:0":                     "unknown",
	"test/orm/test_options.py::LocalOptsTest::test_bound_multiple_opt_only--b:0":                                                   "unknown",
	"test/orm/test_options.py::LocalOptsTest::test_bound_opt_only_adds_to_strat--b:0":                                              "unknown",
	"test/orm/test_options.py::LocalOptsTest::test_bound_strat_opt_recvs_from_optonly--b:0":                                        "unknown",
	"test/orm/test_query.py::CountTest::test_basic--b:0":                                                                           "unknown",
	"test/orm/test_query.py::DistinctTest::test_basic--b:0":                                                                        "unknown",
	"test/orm/test_query.py::FilterTest::test_basic--b:0":                                                                          "unknown",
	"test/orm/test_query.py::FilterTest::test_blank_filter_by--b:0":                                                                "unknown",
	"test/orm/test_query.py::OperatorTest::test_between--b:0":                                                                      "unknown",
	"test/orm/test_query.py::SessionBindTest::test_bulk_delete_fetch_sync--b:0":                                                    "unknown",
	"test/orm/test_query.py::SessionBindTest::test_bulk_delete_no_sync--b:0":                                                       "unknown",
	"test/orm/test_query.py::SessionBindTest::test_bulk_update_fetch_sync--b:0":                                                    "unknown",
	"test/orm/test_query.py::SessionBindTest::test_bulk_update_no_sync--b:0":                                                       "unknown",
	"test/orm/test_query.py::TextTest::test_binds_coerce--b:0":                                                                     "unknown",
	"test/orm/test_query.py::YieldTest::test_basic--b:0":                                                                           "unknown",
	"test/orm/test_relationships.py::ViewOnlyComplexJoin::test_basic--b:0":                                                         "unknown",
	"test/orm/test_relationships.py::ViewOnlyComplexJoin::test_basic--b:1":                                                         "unknown",
	"test/orm/test_selectin_relations.py::HeterogeneousSubtypesTest::test_both--b:1":                                               "unknown",
	"test/orm/test_subquery_relations.py::CyclicalInheritingEagerTestOne::test_basic--b:0":                                         "unknown",
	"test/orm/test_subquery_relations.py::CyclicalInheritingEagerTestOne::test_basic--b:1":                                         "unknown",
	"test/orm/test_unitofwork.py::BinaryHistTest::test_binary_equality--b:0":                                                       "unknown",
	"test/orm/test_unitofwork.py::BinaryHistTest::test_binary_equality--b:1":                                                       "unknown",
	"test/orm/test_unitofwork.py::SaveTest::test_batch_mode--b:1":                                                                  "unknown",
	"test/orm/test_unitofworkv2.py::NullEvaluatingTest::test_builtin_evalnull_nodefault_insert_novalue--b:1":                       "unknown",
	"test/orm/test_versioning.py::InheritanceTwoVersionIdsTest_postgresql+psycopg2_9_5_None::test_base_both--b:0":                  "unknown",
	"test/orm/test_versioning.py::InheritanceTwoVersionIdsTest_postgresql+psycopg2_9_5_None::test_base_both--b:1":                  "unknown",
	"test/orm/test_versioning.py::VersioningTest_postgresql+psycopg2_9_5_None::test_basic--b:0":                                    "unknown",
}

var sqlAlchemyCBlackList19_1 = blacklist{
	"test/dialect/postgresql/test_compiler.py::SequenceTest::test_reverse_eng_name--c:0":                                                              "unknown",
	"test/dialect/postgresql/test_dialect.py::MiscBackendTest_postgresql+psycopg2_9_5_None::test_client_encoding--c:0":                                "unknown",
	"test/dialect/postgresql/test_query.py::InsertTest_postgresql+psycopg2_9_5_None::test_compiled_insert--c:0":                                       "unknown",
	"test/dialect/postgresql/test_reflection.py::DomainReflectionTest_postgresql+psycopg2_9_5_None::test_crosschema_domain_is_reflected--c:0":         "unknown",
	"test/dialect/postgresql/test_reflection.py::ReflectionTest_postgresql+psycopg2_9_5_None::test_cross_schema_reflection_five--c:0":                 "unknown",
	"test/dialect/postgresql/test_reflection.py::ReflectionTest_postgresql+psycopg2_9_5_None::test_cross_schema_reflection_four--c:0":                 "unknown",
	"test/dialect/postgresql/test_reflection.py::ReflectionTest_postgresql+psycopg2_9_5_None::test_cross_schema_reflection_metadata_uses_schema--c:0": "unknown",
	"test/dialect/postgresql/test_reflection.py::ReflectionTest_postgresql+psycopg2_9_5_None::test_cross_schema_reflection_one--c:0":                  "unknown",
	"test/dialect/postgresql/test_reflection.py::ReflectionTest_postgresql+psycopg2_9_5_None::test_cross_schema_reflection_seven--c:0":                "unknown",
	"test/dialect/postgresql/test_reflection.py::ReflectionTest_postgresql+psycopg2_9_5_None::test_cross_schema_reflection_six--c:0":                  "unknown",
	"test/dialect/postgresql/test_reflection.py::ReflectionTest_postgresql+psycopg2_9_5_None::test_cross_schema_reflection_three--c:0":                "unknown",
	"test/dialect/postgresql/test_reflection.py::ReflectionTest_postgresql+psycopg2_9_5_None::test_cross_schema_reflection_two--c:0":                  "unknown",
	"test/dialect/postgresql/test_types.py::EnumTest_postgresql+psycopg2_9_5_None::test_create_table--c:0":                                            "unknown",
	"test/dialect/postgresql/test_types.py::EnumTest_postgresql+psycopg2_9_5_None::test_custom_subclass--c:0":                                         "unknown",
	"test/dialect/postgresql/test_types.py::JSONRoundTripTest_postgresql+psycopg2_9_5_None::test_criterion_python--c:0":                               "unknown",
	"test/dialect/postgresql/test_types.py::JSONRoundTripTest_postgresql+psycopg2_9_5_None::test_custom_python--c:0":                                  "unknown",
	"test/dialect/postgresql/test_types.py::RegClassTest_postgresql+psycopg2_9_5_None::test_cast_oid--c:0":                                            "unknown",
	"test/dialect/test_suite.py::CollateTest_postgresql+psycopg2_9_5_None::test_collate_order_by--c:0":                                                "unknown",
	"test/dialect/test_suite.py::JSONTest_postgresql+psycopg2_9_5_None::test_crit_mixed_path--c:0":                                                    "unknown",
	"test/dialect/test_suite.py::JSONTest_postgresql+psycopg2_9_5_None::test_crit_string_path--c:0":                                                   "unknown",
	"test/dialect/test_suite.py::ServerSideCursorsTest_postgresql+psycopg2_9_5_None::test_conn_option--c:0":                                           "unknown",
	"test/engine/test_execute.py::SchemaTranslateTest_postgresql+psycopg2_9_5_None::test_create_table--c:0":                                           "unknown",
	"test/engine/test_execute.py::SchemaTranslateTest_postgresql+psycopg2_9_5_None::test_crud--c:0":                                                   "unknown",
	"test/engine/test_reflection.py::CreateDropTest_postgresql+psycopg2_9_5_None::test_checkfirst--c:0":                                               "unknown",
	"test/engine/test_reflection.py::CreateDropTest_postgresql+psycopg2_9_5_None::test_createdrop--c:0":                                               "unknown",
	"test/engine/test_reflection.py::ReflectionTest_postgresql+psycopg2_9_5_None::test_check_constraint_reflection--c:0":                              "unknown",
	"test/engine/test_reflection.py::ReflectionTest_postgresql+psycopg2_9_5_None::test_comment_reflection--c:0":                                       "unknown",
	"test/engine/test_reflection.py::ReflectionTest_postgresql+psycopg2_9_5_None::test_composite_fk--c:0":                                             "unknown",
	"test/engine/test_reflection.py::ReflectionTest_postgresql+psycopg2_9_5_None::test_composite_pks--c:0":                                            "unknown",
	"test/engine/test_transaction.py::ExplicitAutoCommitTest::test_control--c:0":                                                                      "unknown",
	"test/engine/test_transaction.py::IsolationLevelTest_postgresql+psycopg2_9_5_None::test_connection_invalidated--c:0":                              "unknown",
	"test/ext/declarative/test_basic.py::DeclarativeTest::test_column--c:0":                                                                           "unknown",
	"test/ext/declarative/test_basic.py::DeclarativeTest::test_column--c:1":                                                                           "unknown",
	"test/ext/declarative/test_basic.py::DeclarativeTest::test_column_properties--c:0":                                                                "unknown",
	"test/ext/declarative/test_basic.py::DeclarativeTest::test_column_properties--c:1":                                                                "unknown",
	"test/ext/declarative/test_basic.py::DeclarativeTest::test_column_properties_2--c:1":                                                              "unknown",
	"test/ext/declarative/test_basic.py::DeclarativeTest::test_comparable_using--c:1":                                                                 "unknown",
	"test/ext/declarative/test_inheritance.py::ConcreteExtensionConfigTest::test_classreg_setup--c:0":                                                 "unknown",
	"test/ext/declarative/test_inheritance.py::ConcreteExtensionConfigTest::test_classreg_setup--c:1":                                                 "unknown",
	"test/ext/declarative/test_mixin.py::DeclarativeMixinTest::test_col_copy_vs_declared_attr_joined_propagation--c:1":                                "unknown",
	"test/ext/declarative/test_mixin.py::DeclarativeMixinTest::test_col_copy_vs_declared_attr_joined_propagation_newname--c:1":                        "unknown",
	"test/ext/declarative/test_mixin.py::DeclarativeMixinTest::test_col_copy_vs_declared_attr_single_propagation--c:1":                                "unknown",
	"test/ext/declarative/test_mixin.py::DeclaredAttrTest::test_col_prop_attrs_associated_w_class_for_mapper_args--c:1":                               "unknown",
	"test/ext/declarative/test_mixin.py::DeclaredAttrTest::test_column_pre_map--c:1":                                                                  "unknown",
	"test/ext/declarative/test_reflection.py::DeferredReflectionTest::test_cls_not_strong_ref--c:0":                                                   "unknown",
	"test/ext/declarative/test_reflection.py::DeferredReflectionTest::test_cls_not_strong_ref--c:1":                                                   "unknown",
	"test/ext/test_automap.py::AutomapInhTest::test_conditional_relationship--c:0":                                                                    "unknown",
	"test/ext/test_baked.py::ResultTest_postgresql+psycopg2_9_5_None::test_conditional_step_oneline--c:1":                                             "unknown",
	"test/ext/test_baked.py::StateChangeTest::test_chained_add--c:0":                                                                                  "unknown",
	"test/ext/test_baked.py::StateChangeTest::test_chained_add_operator--c:0":                                                                         "unknown",
	"test/ext/test_mutable.py::MutableAssocWithAttrInheritTest::test_coerce_raise--c:0":                                                               "unknown",
	"test/ext/test_mutable.py::MutableAssociationScalarJSONTest::test_coerce_none--c:0":                                                               "unknown",
	"test/ext/test_mutable.py::MutableAssociationScalarJSONTest::test_coerce_raise--c:0":                                                              "unknown",
	"test/ext/test_mutable.py::MutableColumnCopyArrayTest::test_clear--c:0":                                                                           "unknown",
	"test/ext/test_serializer.py::SerializeTest::test_columns--c:0":                                                                                   "unknown",
	"test/orm/inheritance/test_polymorphic_rel.py::PolymorphicAliasedJoinsTest_postgresql+psycopg2_9_5_None::test_correlation_two--c:1":               "unknown",
	"test/orm/inheritance/test_polymorphic_rel.py::PolymorphicJoinsTest_postgresql+psycopg2_9_5_None::test_correlation_one--c:0":                      "unknown",
	"test/orm/inheritance/test_polymorphic_rel.py::PolymorphicJoinsTest_postgresql+psycopg2_9_5_None::test_correlation_three--c:0":                    "unknown",
	"test/orm/inheritance/test_polymorphic_rel.py::PolymorphicJoinsTest_postgresql+psycopg2_9_5_None::test_correlation_two--c:0":                      "unknown",
	"test/orm/inheritance/test_relationship.py::SubClassToSubClassFromParentTest::test_2617--2:1":                                                     "unknown",
	"test/orm/test_cascade.py::DoubleParentM2OOrphanTest::test_non_orphan--c:0":                                                                       "unknown",
	"test/orm/test_cascade.py::DoubleParentM2OOrphanTest::test_orphan--c:0":                                                                           "unknown",
	"test/orm/test_cascade.py::M2OCascadeDeleteOrphanTestOne::test_cascade_on_deleted--c:0":                                                           "unknown",
	"test/orm/test_cascade.py::M2OCascadeDeleteOrphanTestOne::test_double_assignment--c:0":                                                            "unknown",
	"test/orm/test_cascade.py::M2OCascadeDeleteOrphanTestOne::test_orphan--c:0":                                                                       "unknown",
	"test/orm/test_cascade.py::M2OCascadeDeleteOrphanTestOne::test_orphan_on_update--c:0":                                                             "unknown",
	"test/orm/test_cascade.py::M2OCascadeDeleteOrphanTestOne::test_pending_expunge--c:0":                                                              "unknown",
	"test/orm/test_cascade.py::M2OCascadeDeleteOrphanTestOne::test_save_update_sends_pending--c:0":                                                    "unknown",
	"test/orm/test_cascade.py::M2OCascadeDeleteOrphanTestOne::test_save_update_sends_pending--c:1":                                                    "unknown",
	"test/orm/test_cascade.py::NoBackrefCascadeTest::test_o2m_flag_on_backref--c:1":                                                                   "unknown",
	"test/orm/test_cascade.py::NoSaveCascadeFlushTest::test_o2m_only_child_transient--c:1":                                                            "unknown",
	"test/orm/test_cascade.py::O2MCascadeDeleteNoOrphanTest::test_cascade_delete_noorphans--c:1":                                                      "unknown",
	"test/orm/test_cascade.py::O2MCascadeDeleteOrphanTest::test_standalone_orphan--c:0":                                                               "unknown",
	"test/orm/test_cascade.py::O2MCascadeDeleteOrphanTest::test_standalone_orphan--c:1":                                                               "unknown",
	"test/orm/test_cascade.py::O2MCascadeTest::test_none_o2m_collection_assignment--c:1":                                                              "unknown",
	"test/orm/test_cascade.py::O2OSingleParentNoFlushTest::test_replace_attribute_no_flush--c:1":                                                      "unknown",
	"test/orm/test_cascade.py::O2OSingleParentTest::test_single_parent_raise--c:1":                                                                    "unknown",
	"test/orm/test_cascade.py::PendingOrphanTestSingleLevel::test_nonorphans_ok--c:0":                                                                 "unknown",
	"test/orm/test_cascade.py::PendingOrphanTestSingleLevel::test_pending_collection_expunge--c:0":                                                    "unknown",
	"test/orm/test_cascade.py::PendingOrphanTestSingleLevel::test_pending_standalone_orphan--c:0":                                                     "unknown",
	"test/orm/test_cascade.py::PendingOrphanTestSingleLevel::test_pending_standalone_orphan--c:1":                                                     "unknown",
	"test/orm/test_composites.py::ManyToOneTest::test_query_aliased--c:1":                                                                             "unknown",
	"test/orm/test_composites.py::MappedSelectTest::test_set_composite_attrs_via_selectable--c:0":                                                     "unknown",
	"test/orm/test_composites.py::MappedSelectTest::test_set_composite_attrs_via_selectable--c:1":                                                     "unknown",
	"test/orm/test_cycles.py::InheritTestTwo::test_flush--c:0":                                                                                        "unknown",
	"test/orm/test_cycles.py::InheritTestTwo::test_flush--c:1":                                                                                        "unknown",
	"test/orm/test_cycles.py::PostUpdateOnUpdateTest::test_update_defaults--c:0":                                                                      "unknown",
	"test/orm/test_cycles.py::PostUpdateOnUpdateTest::test_update_defaults_can_set_value--c:0":                                                        "unknown",
	"test/orm/test_cycles.py::PostUpdateOnUpdateTest::test_update_defaults_dont_expire_on_delete--c:0":                                                "unknown",
	"test/orm/test_cycles.py::PostUpdateOnUpdateTest::test_update_defaults_dont_expire_on_delete_no_postupdate--c:0":                                  "unknown",
	"test/orm/test_cycles.py::PostUpdateOnUpdateTest::test_update_defaults_refresh_flush_event--c:0":                                                  "unknown",
	"test/orm/test_cycles.py::PostUpdateOnUpdateTest::test_update_defaults_refresh_flush_event_no_postupdate--c:0":                                    "unknown",
	"test/orm/test_cycles.py::PostUpdateOnUpdateTest::test_update_defaults_refresh_flush_event_no_postupdate--c:1":                                    "unknown",
	"test/orm/test_froms.py::MixedEntitiesTest::test_correlated_subquery--c:1":                                                                        "unknown",
	"test/orm/test_inspect.py::TestORMInspection::test_class_mapper--c:0":                                                                             "unknown",
	"test/orm/test_inspect.py::TestORMInspection::test_col_filter--c:0":                                                                               "unknown",
	"test/orm/test_inspect.py::TestORMInspection::test_col_property--c:0":                                                                             "unknown",
	"test/orm/test_inspect.py::TestORMInspection::test_column_collection_iterate--c:0":                                                                "unknown",
	"test/orm/test_inspect.py::TestORMInspection::test_column_collection_iterate--c:1":                                                                "unknown",
	"test/orm/test_joins.py::JoinTest::test_clause_onclause--c:0":                                                                                     "unknown",
	"test/orm/test_lazy_relations.py::LazyTest::test_callable_bind--c:0":                                                                              "unknown",
	"test/orm/test_lazy_relations.py::LazyTest::test_custom_bind--c:0":                                                                                "unknown",
	"test/orm/test_loading.py::InstancesTest::test_cursor_close_w_failed_rowproc--c:0":                                                                "unknown",
	"test/orm/test_mapper.py::ComparatorFactoryTest::test_column--c:0":                                                                                "unknown",
	"test/orm/test_mapper.py::ComparatorFactoryTest::test_column--c:1":                                                                                "unknown",
	"test/orm/test_mapper.py::MapperTest::test_cancel_order_by--c:0":                                                                                  "unknown",
	"test/orm/test_mapper.py::MapperTest::test_check_descriptor_as_method--c:0":                                                                       "unknown",
	"test/orm/test_mapper.py::MapperTest::test_class_hier_only_instrument_once_multiple_configure--c:0":                                               "unknown",
	"test/orm/test_mapper.py::MapperTest::test_column_not_present--c:0":                                                                               "unknown",
	"test/orm/test_mapper.py::MapperTest::test_column_prefix--c:0":                                                                                    "unknown",
	"test/orm/test_mapper.py::MapperTest::test_column_prop_deannotate--c:0":                                                                           "unknown",
	"test/orm/test_mapper.py::MapperTest::test_column_synonyms--c:0":                                                                                  "unknown",
	"test/orm/test_mapper.py::MapperTest::test_comparable--c:0":                                                                                       "unknown",
	"test/orm/test_mapper.py::MapperTest::test_comparable_column--c:0":                                                                                "unknown",
	"test/orm/test_mapper.py::MapperTest::test_configure_on_get_props_1--c:0":                                                                         "unknown",
	"test/orm/test_mapper.py::MapperTest::test_configure_on_get_props_2--c:0":                                                                         "unknown",
	"test/orm/test_mapper.py::MapperTest::test_configure_on_get_props_3--c:0":                                                                         "unknown",
	"test/orm/test_mapper.py::MapperTest::test_configure_on_prop_1--c:0":                                                                              "unknown",
	"test/orm/test_mapper.py::MapperTest::test_configure_on_prop_2--c:0":                                                                              "unknown",
	"test/orm/test_mapper.py::MapperTest::test_configure_on_prop_3--c:0":                                                                              "unknown",
	"test/orm/test_mapper.py::MapperTest::test_configure_on_session--c:0":                                                                             "unknown",
	"test/orm/test_mapper.py::MapperTest::test_constructor_exc--c:0":                                                                                  "unknown",
	"test/orm/test_mapper.py::MapperTest::test_count--c:0":                                                                                            "unknown",
	"test/orm/test_mapper.py::MapperTest::test_custom_join--c:0":                                                                                      "unknown",
	"test/orm/test_merge.py::MergeTest::test_cascades_dont_autoflush_2--c:1":                                                                          "unknown",
	"test/orm/test_naturalpks.py::CascadeToFKPKTest_postgresql+psycopg2_9_5_None::test_change_m2o_passive--c:0":                                       "unknown",
	"test/orm/test_naturalpks.py::CascadeToFKPKTest_postgresql+psycopg2_9_5_None::test_change_m2o_passive--c:1":                                       "unknown",
	"test/orm/test_query.py::DistinctTest::test_columns_augmented_sql_two--c:1":                                                                       "unknown",
	"test/orm/test_query.py::FilterTest::test_clause_element_ok--c:0":                                                                                 "unknown",
	"test/orm/test_query.py::FilterTest::test_comparison--c:0":                                                                                        "unknown",
	"test/orm/test_query.py::FilterTest::test_contains--c:0":                                                                                          "unknown",
	"test/orm/test_query.py::FilterTest::test_contains_m2m--c:0":                                                                                      "unknown",
	"test/orm/test_query.py::HasMapperEntitiesTest::test_cols--c:0":                                                                                   "unknown",
	"test/orm/test_query.py::HasMapperEntitiesTest::test_cols_set_entities--c:0":                                                                      "unknown",
	"test/orm/test_query.py::OperatorTest::test_clauses--c:0":                                                                                         "unknown",
	"test/orm/test_query.py::OperatorTest::test_collate--c:0":                                                                                         "unknown",
	"test/orm/test_query.py::OperatorTest::test_comparison--c:0":                                                                                      "unknown",
	"test/orm/test_query.py::PrefixWithTest::test_chained_prefixes--c:0":                                                                              "unknown",
	"test/orm/test_query.py::QueryClsTest::test_callable_expr--c:0":                                                                                   "unknown",
	"test/orm/test_query.py::QueryClsTest::test_callable_expr_undocumented_query_constructor--c:0":                                                    "unknown",
	"test/orm/test_query.py::QueryClsTest::test_callable_get--c:0":                                                                                    "unknown",
	"test/orm/test_query.py::QueryClsTest::test_callable_m2o_lazyload--c:0":                                                                           "unknown",
	"test/orm/test_query.py::QueryClsTest::test_callable_o2m_lazyload--c:0":                                                                           "unknown",
	"test/orm/test_query.py::RawSelectTest::test_col_prop_builtin_function--c:0":                                                                      "unknown",
	"test/orm/test_query.py::RawSelectTest::test_columns_clause_aliased_columns--c:0":                                                                 "unknown",
	"test/orm/test_query.py::RawSelectTest::test_columns_clause_aliased_entity--c:0":                                                                  "unknown",
	"test/orm/test_query.py::RawSelectTest::test_columns_clause_columns--c:0":                                                                         "unknown",
	"test/orm/test_query.py::RawSelectTest::test_columns_clause_entity--c:0":                                                                          "unknown",
	"test/orm/test_query.py::RawSelectTest::test_core_join--c:0":                                                                                      "unknown",
	"test/orm/test_query.py::RawSelectTest::test_correlate_aliased_entity--c:0":                                                                       "unknown",
	"test/orm/test_query.py::RawSelectTest::test_correlate_entity--c:0":                                                                               "unknown",
	"test/orm/test_query.py::RowTupleTest::test_column_metadata--c:0":                                                                                 "unknown",
	"test/orm/test_query.py::RowTupleTest::test_custom_names--c:0":                                                                                    "unknown",
	"test/orm/test_query.py::SessionBindTest::test_column_property--c:0":                                                                              "unknown",
	"test/orm/test_query.py::SessionBindTest::test_column_property_select--c:0":                                                                       "unknown",
	"test/orm/test_query.py::SessionBindTest::test_count--c:0":                                                                                        "unknown",
	"test/orm/test_relationships.py::M2ODontOverwriteFKTest::test_collection_relationship_overrides_fk--c:1":                                          "unknown",
	"test/orm/test_selectin_relations.py::BaseRelationFromJoinedSubclassTest::test_correct_select_existingfrom--c:0":                                  "unknown",
	"test/orm/test_selectin_relations.py::BaseRelationFromJoinedSubclassTest::test_correct_select_nofrom--c:0":                                        "unknown",
	"test/orm/test_selectin_relations.py::BaseRelationFromJoinedSubclassTest::test_correct_select_with_polymorphic_alias--c:0":                        "unknown",
	"test/orm/test_selectin_relations.py::BaseRelationFromJoinedSubclassTest::test_correct_select_with_polymorphic_flat_alias--c:0":                   "unknown",
	"test/orm/test_selectin_relations.py::BaseRelationFromJoinedSubclassTest::test_correct_select_with_polymorphic_no_alias--c:0":                     "unknown",
	"test/orm/test_selectin_relations.py::EagerTest::test_cyclical_explicit_join_depth--c:1":                                                          "unknown",
	"test/orm/test_subquery_relations.py::SubqueryloadDistinctTest::test_cant_do_distinct_in_joins--c:0":                                              "unknown",
	"test/orm/test_transaction.py::AccountingFlagsTest_postgresql+psycopg2_9_5_None::test_commit_no_accounting--c:1":                                  "unknown",
	"test/orm/test_transaction.py::ContextManagerTest_postgresql+psycopg2_9_5_None::test_contextmanager_nested_rollback--c:0":                         "unknown",
	"test/orm/test_transaction.py::ContextManagerTest_postgresql+psycopg2_9_5_None::test_contextmanager_rollback--c:1":                                "unknown",
	"test/orm/test_transaction.py::FixtureDataTest_postgresql+psycopg2_9_5_None::test_concurrent_commit_persistent--c:1":                              "unknown",
	"test/orm/test_unitofwork.py::TransactionTest::test_close_transaction_on_commit_fail--c:0":                                                        "unknown",
	"test/orm/test_versioning.py::AlternateGeneratorTest_postgresql+psycopg2_9_5_None::test_child_row_switch_two--c:0":                                "unknown",
	"test/orm/test_versioning.py::RowSwitchTest_postgresql+psycopg2_9_5_None::test_child_row_switch--c:1":                                             "unknown",
	"test/orm/test_versioning.py::ServerVersioningTest_postgresql+psycopg2_9_5_None::test_concurrent_mod_err_expire_on_commit--c:0":                   "unknown",
	"test/sql/test_constraints.py::ConstraintGenTest_postgresql+psycopg2_9_5_None::test_check_constraint_create--c:0":                                 "unknown",
	"test/sql/test_constraints.py::ConstraintGenTest_postgresql+psycopg2_9_5_None::test_cycle_named_fks--c:0":                                         "unknown",
	"test/sql/test_constraints.py::ConstraintGenTest_postgresql+psycopg2_9_5_None::test_cycle_unnamed_fks--c:0":                                       "unknown",
	"test/sql/test_constraints.py::ConstraintGenTest_postgresql+psycopg2_9_5_None::test_fk_cant_drop_cycled_unnamed--c:0":                             "unknown",
	"test/sql/test_constraints.py::ConstraintGenTest_postgresql+psycopg2_9_5_None::test_fk_column_auto_alter_inline_constraint_create--c:0":           "unknown",
	"test/sql/test_constraints.py::ConstraintGenTest_postgresql+psycopg2_9_5_None::test_fk_column_use_alter_constraint_create--c:0":                   "unknown",
	"test/sql/test_constraints.py::ConstraintGenTest_postgresql+psycopg2_9_5_None::test_fk_column_use_alter_inline_constraint_create--c:0":            "unknown",
	"test/sql/test_constraints.py::ConstraintGenTest_postgresql+psycopg2_9_5_None::test_fk_table_auto_alter_constraint_create--c:0":                   "unknown",
	"test/sql/test_constraints.py::ConstraintGenTest_postgresql+psycopg2_9_5_None::test_fk_table_use_alter_constraint_create--c:0":                    "unknown",
	"test/sql/test_metadata.py::ToMetaDataTest::test_copy--c:0":                                                                                       "unknown",
	"test/sql/test_resultset.py::KeyTargetingTest_postgresql+psycopg2_9_5_None::test_column_label_overlap_fallback--c:0":                              "unknown",
	"test/sql/test_resultset.py::KeyTargetingTest_postgresql+psycopg2_9_5_None::test_column_label_overlap_fallback_2--c:0":                            "unknown",
	"test/sql/test_resultset.py::KeyTargetingTest_postgresql+psycopg2_9_5_None::test_columnclause_schema_column_five--c:0":                            "unknown",
	"test/sql/test_resultset.py::KeyTargetingTest_postgresql+psycopg2_9_5_None::test_columnclause_schema_column_four--c:0":                            "unknown",
	"test/sql/test_resultset.py::KeyTargetingTest_postgresql+psycopg2_9_5_None::test_columnclause_schema_column_one--c:0":                             "unknown",
	"test/sql/test_resultset.py::KeyTargetingTest_postgresql+psycopg2_9_5_None::test_columnclause_schema_column_three--c:0":                           "unknown",
	"test/sql/test_resultset.py::KeyTargetingTest_postgresql+psycopg2_9_5_None::test_columnclause_schema_column_two--c:0":                             "unknown",
	"test/sql/test_returning.py::ReturnDefaultsTest_postgresql+psycopg2_9_5_None::test_chained_insert_pk--c:0":                                        "unknown",
	"test/sql/test_returning.py::ReturningTest_postgresql+psycopg2_9_5_None::test_column_targeting--c:0":                                              "unknown",
	"test/sql/test_types.py::BinaryTest_postgresql+psycopg2_9_5_None::test_comparison--c:1":                                                           "unknown",
	"test/sql/test_types.py::EnumTest_postgresql+psycopg2_9_5_None::test_check_constraint--c:0":                                                       "unknown",
	"test/sql/test_types.py::EnumTest_postgresql+psycopg2_9_5_None::test_create_metadata_bound_no_crash--c:0":                                         "unknown",
	"test/sql/test_update.py::UpdateTest::test_correlated_update_two--c:1":                                                                            "unknown",
}

var sqlAlchemyDBlackList19_1 = blacklist{
	"test/dialect/postgresql/test_dialect.py::BatchInsertsTest_postgresql+psycopg2_9_5_None::test_insert--d:0":                              "unknown",
	"test/dialect/postgresql/test_dialect.py::BatchInsertsTest_postgresql+psycopg2_9_5_None::test_update--d:0":                              "unknown",
	"test/dialect/postgresql/test_dialect.py::MiscBackendTest_postgresql+psycopg2_9_5_None::test_autocommit_isolation_level--d:0":           "unknown",
	"test/dialect/postgresql/test_dialect.py::MiscBackendTest_postgresql+psycopg2_9_5_None::test_client_encoding--d:0":                      "unknown",
	"test/dialect/postgresql/test_dialect.py::MiscBackendTest_postgresql+psycopg2_9_5_None::test_date_reflection--d:0":                      "unknown",
	"test/dialect/postgresql/test_dialect.py::MiscBackendTest_postgresql+psycopg2_9_5_None::test_preexecute_passivedefault--d:0":            "unknown",
	"test/dialect/postgresql/test_dialect.py::MiscBackendTest_postgresql+psycopg2_9_5_None::test_schema_roundtrips--d:0":                    "unknown",
	"test/dialect/postgresql/test_reflection.py::DomainReflectionTest_postgresql+psycopg2_9_5_None::test_domain_is_reflected--d:0":          "unknown",
	"test/dialect/postgresql/test_types.py::EnumTest_postgresql+psycopg2_9_5_None::test_disable_create--d:0":                                "unknown",
	"test/dialect/postgresql/test_types.py::EnumTest_postgresql+psycopg2_9_5_None::test_drops_on_table--d:0":                                "unknown",
	"test/dialect/postgresql/test_types.py::PGArrayRoundTripTest_postgresql+psycopg2_9_5_None::test_dim_array_contains_generator_exec--d:0": "unknown",
	"test/dialect/postgresql/test_types.py::PGArrayRoundTripTest_postgresql+psycopg2_9_5_None::test_dim_array_contains_list_exec--d:0":      "unknown",
	"test/dialect/postgresql/test_types.py::PGArrayRoundTripTest_postgresql+psycopg2_9_5_None::test_dim_array_contains_set_exec--d:0":       "unknown",
	"test/dialect/test_suite.py::CTETest_postgresql+psycopg2_9_5_None::test_delete_from_round_trip--d:0":                                    "unknown",
	"test/dialect/test_suite.py::CTETest_postgresql+psycopg2_9_5_None::test_delete_scalar_subq_round_trip--d:0":                             "unknown",
	"test/dialect/test_suite.py::ComponentReflectionTest_postgresql+psycopg2_9_5_None::test_deprecated_get_primary_keys--d:0":               "unknown",
	"test/dialect/test_suite.py::ComponentReflectionTest_postgresql+psycopg2_9_5_None::test_dialect_initialize--d:0":                        "unknown",
	"test/engine/test_execute.py::ExecuteTest_postgresql+psycopg2_9_5_None::test_dont_wrap_mixin--d:1":                                      "unknown",
	"test/engine/test_execute.py::SchemaTranslateTest_postgresql+psycopg2_9_5_None::test_ddl_hastable--d:0":                                 "unknown",
	"test/engine/test_transaction.py::IsolationLevelTest_postgresql+psycopg2_9_5_None::test_default_level--d:0":                             "unknown",
	"test/orm/test_assorted_eager.py::EagerTest::test_dslish--d:0":                                                                          "unknown",
	"test/orm/test_cascade.py::M2OCascadeDeleteOrphanTestTwo::test_deletes_orphans_twolevel--d:1":                                           "unknown",
	"test/orm/test_defaults.py::ExcludedDefaultsTest::test_exclude--d:0":                                                                    "unknown",
	"test/orm/test_deferred.py::DeferredTest::test_unsaved_group_2--d:1":                                                                    "unknown",
	"test/orm/test_dynamic.py::DynamicTest::test_association_nonaliased--d:0":                                                               "unknown",
	"test/orm/test_dynamic.py::DynamicTest::test_basic--d:0":                                                                                "unknown",
	"test/orm/test_dynamic.py::DynamicTest::test_configured_order_by--d:0":                                                                  "unknown",
	"test/orm/test_dynamic.py::DynamicTest::test_count--d:0":                                                                                "unknown",
	"test/orm/test_dynamic.py::DynamicTest::test_custom_query--d:0":                                                                         "unknown",
	"test/orm/test_dynamic.py::DynamicTest::test_custom_query_with_custom_mixin--d:0":                                                       "unknown",
	"test/orm/test_dynamic.py::DynamicTest::test_detached_raise--d:0":                                                                       "unknown",
	"test/orm/test_dynamic.py::DynamicTest::test_dynamic_on_backref--d:0":                                                                   "unknown",
	"test/orm/test_dynamic.py::DynamicTest::test_m2m--d:0":                                                                                  "unknown",
	"test/orm/test_dynamic.py::DynamicTest::test_no_count--d:0":                                                                             "unknown",
	"test/orm/test_dynamic.py::DynamicTest::test_no_m2o--d:0":                                                                               "unknown",
	"test/orm/test_dynamic.py::DynamicTest::test_no_populate--d:0":                                                                          "unknown",
	"test/orm/test_dynamic.py::DynamicTest::test_no_uselist_false--d:0":                                                                     "unknown",
	"test/orm/test_dynamic.py::DynamicTest::test_order_by--d:0":                                                                             "unknown",
	"test/orm/test_dynamic.py::DynamicTest::test_secondary_as_join--d:0":                                                                    "unknown",
	"test/orm/test_dynamic.py::DynamicTest::test_secondary_doesnt_interfere_w_join_to_fromlist--d:0":                                        "unknown",
	"test/orm/test_dynamic.py::DynamicTest::test_statement--d:0":                                                                            "unknown",
	"test/orm/test_dynamic.py::DynamicTest::test_transient_access--d:0":                                                                     "unknown",
	"test/orm/test_dynamic.py::DynamicTest::test_transient_count--d:0":                                                                      "unknown",
	"test/orm/test_dynamic.py::DynamicTest::test_transient_count--d:1":                                                                      "unknown",
	"test/orm/test_events.py::DeferredMapperEventsTest::test_deferred_map_event_subclass_propagate--d:1":                                    "unknown",
	"test/orm/test_events.py::SessionLifecycleEventsTest::test_detached_to_persistent_via_deleted--d:1":                                     "unknown",
	"test/orm/test_subquery_relations.py::SubqueryloadDistinctTest::test_distinct_strategy_opt_m2o--d:0":                                    "unknown",
	"test/orm/test_subquery_relations.py::SubqueryloadDistinctTest::test_distinct_unrelated_opt_m2o--d:0":                                   "unknown",
	"test/orm/test_transaction.py::SessionTransactionTest_postgresql+psycopg2_9_5_None::test_dirty_state_transferred_deep_nesting--d:0":     "unknown",
	"test/orm/test_update_delete.py::InheritTest_postgresql+psycopg2_9_5_None::test_delete_from--d:0":                                       "unknown",
	"test/orm/test_update_delete.py::UpdateDeleteFromTest_postgresql+psycopg2_9_5_None::test_delete_from_joined_subq_test--d:0":             "unknown",
	"test/orm/test_versioning.py::ServerVersioningTest_postgresql+psycopg2_9_5_None::test_delete_col--d:0":                                  "unknown",
	"test/sql/test_defaults.py::CTEDefaultTest_postgresql+psycopg2_9_5_None::test_delete_in_select--d:0":                                    "unknown",
	"test/sql/test_defaults.py::CTEDefaultTest_postgresql+psycopg2_9_5_None::test_insert_in_select--d:0":                                    "unknown",
	"test/sql/test_defaults.py::CTEDefaultTest_postgresql+psycopg2_9_5_None::test_select_in_insert--d:0":                                    "unknown",
	"test/sql/test_defaults.py::CTEDefaultTest_postgresql+psycopg2_9_5_None::test_select_in_update--d:0":                                    "unknown",
	"test/sql/test_defaults.py::CTEDefaultTest_postgresql+psycopg2_9_5_None::test_update_in_select--d:0":                                    "unknown",
	"test/sql/test_defaults.py::EmptyInsertTest_postgresql+psycopg2_9_5_None::test_empty_insert--d:0":                                       "unknown",
	"test/sql/test_defaults.py::PKDefaultTest_postgresql+psycopg2_9_5_None::test_regular--d:0":                                              "unknown",
	"test/sql/test_defaults.py::PKDefaultTest_postgresql+psycopg2_9_5_None::test_with_implicit_returning--d:0":                              "unknown",
	"test/sql/test_defaults.py::PKIncrementTest_postgresql+psycopg2_9_5_None::test_autoincrement_autocommit--d:0":                           "unknown",
	"test/sql/test_defaults.py::PKIncrementTest_postgresql+psycopg2_9_5_None::test_autoincrement_transaction--d:0":                          "unknown",
	"test/sql/test_defaults.py::ServerDefaultsOnPKTest_postgresql+psycopg2_9_5_None::test_autoincrement_reflected_from_server_default--d:0": "unknown",
	"test/sql/test_defaults.py::ServerDefaultsOnPKTest_postgresql+psycopg2_9_5_None::test_int_default_none_on_insert_reflected--d:0":        "unknown",
	"test/sql/test_defaults.py::SpecialTypePKTest_postgresql+psycopg2_9_5_None::test_no_implicit_returning--d:0":                            "unknown",
	"test/sql/test_defaults.py::SpecialTypePKTest_postgresql+psycopg2_9_5_None::test_plain--d:0":                                            "unknown",
	"test/sql/test_defaults.py::TableBoundSequenceTest_postgresql+psycopg2_9_5_None::test_seq_nonpk--d:0":                                   "unknown",
	"test/sql/test_delete.py::DeleteFromRoundTripTest_postgresql+psycopg2_9_5_None::test_exec_alias_plus_table--d:0":                        "unknown",
	"test/sql/test_delete.py::DeleteFromRoundTripTest_postgresql+psycopg2_9_5_None::test_exec_three_table--d:0":                             "unknown",
	"test/sql/test_delete.py::DeleteFromRoundTripTest_postgresql+psycopg2_9_5_None::test_exec_two_table--d:0":                               "unknown",
	"test/sql/test_delete.py::DeleteFromRoundTripTest_postgresql+psycopg2_9_5_None::test_exec_two_table_plus_alias--d:0":                    "unknown",
	"test/sql/test_delete.py::DeleteFromRoundTripTest_postgresql+psycopg2_9_5_None::test_exec_two_table_plus_alias--d:1":                    "unknown",
	"test/sql/test_returning.py::ReturningTest_postgresql+psycopg2_9_5_None::test_delete_returning--d:0":                                    "unknown",
}

var sqlAlchemyEBlackList19_1 = blacklist{
	"test/dialect/postgresql/test_query.py::ExtractTest_postgresql+psycopg2_9_5_None::test_eleven--e:0":                                  "unknown",
	"test/dialect/postgresql/test_reflection.py::DomainReflectionTest_postgresql+psycopg2_9_5_None::test_enum_domain_is_reflected--e:0":  "unknown",
	"test/engine/test_execute.py::CompiledCacheTest_postgresql+psycopg2_9_5_None::test_schema_translate_in_key--e:0":                     "unknown",
	"test/engine/test_execute.py::EngineEventsTest_postgresql+psycopg2_9_5_None::test_execute_events--e:0":                               "unknown",
	"test/engine/test_execute.py::EngineEventsTest_postgresql+psycopg2_9_5_None::test_transactional_advanced--e:0":                       "unknown",
	"test/engine/test_execute.py::ExecuteTest_postgresql+psycopg2_9_5_None::test_empty_insert--e:0":                                      "unknown",
	"test/engine/test_execute.py::ProxyConnectionTest::test_transactional_advanced--e:0":                                                 "unknown",
	"test/engine/test_execute.py::SchemaTranslateTest_postgresql+psycopg2_9_5_None::test_create_table--e:0":                              "unknown",
	"test/engine/test_execute.py::SchemaTranslateTest_postgresql+psycopg2_9_5_None::test_crud--e:0":                                      "unknown",
	"test/engine/test_execute.py::SchemaTranslateTest_postgresql+psycopg2_9_5_None::test_ddl_hastable--e:0":                              "unknown",
	"test/engine/test_execute.py::SchemaTranslateTest_postgresql+psycopg2_9_5_None::test_via_engine--e:0":                                "unknown",
	"test/engine/test_reflection.py::ReflectionTest_postgresql+psycopg2_9_5_None::test_extend_existing--e:0":                             "unknown",
	"test/engine/test_reflection.py::ReflectionTest_postgresql+psycopg2_9_5_None::test_extend_existing_reflect_all_dont_dupe_index--e:0": "unknown",
	"test/engine/test_reflection.py::SchemaTest_postgresql+psycopg2_9_5_None::test_explicit_default_schema--e:0":                         "unknown",
	"test/engine/test_reflection.py::SchemaTest_postgresql+psycopg2_9_5_None::test_explicit_default_schema_metadata--e:0":                "unknown",
	"test/engine/test_transaction.py::ExplicitAutoCommitTest::test_explicit_compiled--e:0":                                               "unknown",
	"test/engine/test_transaction.py::ExplicitAutoCommitTest::test_explicit_compiled_deprecated--e:0":                                    "unknown",
	"test/engine/test_transaction.py::ExplicitAutoCommitTest::test_explicit_connection--e:0":                                             "unknown",
	"test/engine/test_transaction.py::ExplicitAutoCommitTest::test_explicit_text--e:0":                                                   "unknown",
	"test/engine/test_transaction.py::ExplicitAutoCommitTest::test_explicit_text_deprecated--e:0":                                        "unknown",
	"test/engine/test_transaction.py::IsolationLevelTest_postgresql+psycopg2_9_5_None::test_engine_param_stays--e:0":                     "unknown",
	"test/orm/inheritance/test_relationship.py::SelfReferentialM2MTest::test_eager_join--e:1":                                            "unknown",
	"test/orm/inheritance/test_single.py::ManyToManyToSingleTest::test_eager_join--e:1":                                                  "unknown",
	"test/orm/test_defaults.py::ExcludedDefaultsTest::test_exclude--e:0":                                                                 "unknown",
	"test/orm/test_eager_relations.py::EntityViaMultiplePathTestThree::test_multi_path_load_lazy_none--e:0":                              "unknown",
	"test/orm/test_eager_relations.py::SelfReferentialEagerTest::test_lazy_fallback_doesnt_affect_eager--e:0":                            "unknown",
	"test/orm/test_eager_relations.py::SelfReferentialEagerTest::test_with_deferred--e:0":                                                "unknown",
	"test/orm/test_events.py::RefreshFlushInReturningTest_postgresql+psycopg2_9_5_None::test_no_attr_events_flush--e:0":                  "unknown",
	"test/orm/test_froms.py::ExternalColumnsTest::test_external_columns--e:0":                                                            "unknown",
	"test/orm/test_froms.py::TestOverlyEagerEquivalentCols::test_equivs--e:0":                                                            "unknown",
	"test/orm/test_mapper.py::OptionsTest::test_eager_options_with_limit--e:1":                                                           "unknown",
	"test/orm/test_naturalpks.py::NaturalPKTest_postgresql+psycopg2_9_5_None::test_entity--e:0":                                          "unknown",
	"test/orm/test_pickled.py::PickleTest::test_exceptions--e:1":                                                                         "unknown",
	"test/orm/test_query.py::YieldTest::test_eagerload_opt_disable--e:0":                                                                 "unknown",
	"test/orm/test_transaction.py::SessionTransactionTest_postgresql+psycopg2_9_5_None::test_external_nested_transaction--e:0":           "unknown",
	"test/orm/test_transaction.py::SessionTransactionTest_postgresql+psycopg2_9_5_None::test_external_nested_transaction--e:1":           "unknown",
	"test/orm/test_update_delete.py::UpdateDeleteTest_postgresql+psycopg2_9_5_None::test_evaluate_before_delete--e:0":                    "unknown",
	"test/orm/test_update_delete.py::UpdateDeleteTest_postgresql+psycopg2_9_5_None::test_evaluate_before_update--e:0":                    "unknown",
	"test/orm/test_update_delete.py::UpdateDeleteTest_postgresql+psycopg2_9_5_None::test_evaluate_clauseelement--e:0":                    "unknown",
	"test/orm/test_update_delete.py::UpdateDeleteTest_postgresql+psycopg2_9_5_None::test_evaluate_double_synonym_attr--e:0":              "unknown",
	"test/orm/test_update_delete.py::UpdateDeleteTest_postgresql+psycopg2_9_5_None::test_evaluate_invalid--e:0":                          "unknown",
	"test/orm/test_update_delete.py::UpdateDeleteTest_postgresql+psycopg2_9_5_None::test_evaluate_synonym_attr--e:0":                     "unknown",
	"test/orm/test_update_delete.py::UpdateDeleteTest_postgresql+psycopg2_9_5_None::test_evaluate_synonym_string--e:0":                   "unknown",
	"test/orm/test_update_delete.py::UpdateDeleteTest_postgresql+psycopg2_9_5_None::test_evaluate_unmapped_col--e:0":                     "unknown",
	"test/orm/test_update_delete.py::UpdateDeleteTest_postgresql+psycopg2_9_5_None::test_evaluate_unmapped_col--e:1":                     "unknown",
	"test/sql/test_delete.py::DeleteFromRoundTripTest_postgresql+psycopg2_9_5_None::test_exec_alias_plus_table--e:0":                     "unknown",
	"test/sql/test_delete.py::DeleteFromRoundTripTest_postgresql+psycopg2_9_5_None::test_exec_three_table--e:0":                          "unknown",
	"test/sql/test_delete.py::DeleteFromRoundTripTest_postgresql+psycopg2_9_5_None::test_exec_two_table--e:0":                            "unknown",
	"test/sql/test_delete.py::DeleteFromRoundTripTest_postgresql+psycopg2_9_5_None::test_exec_two_table_plus_alias--e:0":                 "unknown",
	"test/sql/test_metadata.py::SchemaTypeTest_postgresql+psycopg2_9_5_None::test_enum_column_copy_transfers_events--e:0":                "unknown",
	"test/sql/test_metadata.py::UseExistingTest::test_exception_no_flags--e:0":                                                           "unknown",
	"test/sql/test_metadata.py::UseExistingTest::test_existing_plus_useexisting_raises--e:0":                                             "unknown",
	"test/sql/test_metadata.py::UseExistingTest::test_extend_existing_add_column--e:0":                                                   "unknown",
	"test/sql/test_metadata.py::UseExistingTest::test_extend_existing_add_column_no_orig--e:0":                                           "unknown",
	"test/sql/test_metadata.py::UseExistingTest::test_extend_existing_add_column_no_reflection--e:0":                                     "unknown",
	"test/sql/test_metadata.py::UseExistingTest::test_extend_existing_coltype--e:0":                                                      "unknown",
	"test/sql/test_metadata.py::UseExistingTest::test_extend_existing_coltype_no_orig--e:0":                                              "unknown",
	"test/sql/test_metadata.py::UseExistingTest::test_extend_existing_coltype_no_reflection--e:0":                                        "unknown",
	"test/sql/test_metadata.py::UseExistingTest::test_extend_existing_quote--e:0":                                                        "unknown",
	"test/sql/test_metadata.py::UseExistingTest::test_extend_existing_quote_no_orig--e:0":                                                "unknown",
	"test/sql/test_metadata.py::UseExistingTest::test_extend_existing_quote_no_reflection--e:0":                                          "unknown",
	"test/sql/test_metadata.py::UseExistingTest::test_extend_existing_quote_no_reflection--e:1":                                          "unknown",
	"test/sql/test_types.py::UserDefinedRoundTripTest_postgresql+psycopg2_9_5_None::test_expanding_in--e:0":                              "unknown",
	"test/sql/test_types.py::UserDefinedRoundTripTest_postgresql+psycopg2_9_5_None::test_expanding_in--e:1":                              "unknown",
	"test/sql/test_update.py::UpdateFromRoundTripTest_postgresql+psycopg2_9_5_None::test_exec_join_multitable--e:0":                      "unknown",
	"test/sql/test_update.py::UpdateFromRoundTripTest_postgresql+psycopg2_9_5_None::test_exec_multitable--e:0":                           "unknown",
	"test/sql/test_update.py::UpdateFromRoundTripTest_postgresql+psycopg2_9_5_None::test_exec_multitable_same_name--e:0":                 "unknown",
	"test/sql/test_update.py::UpdateFromRoundTripTest_postgresql+psycopg2_9_5_None::test_exec_three_table--e:0":                          "unknown",
	"test/sql/test_update.py::UpdateFromRoundTripTest_postgresql+psycopg2_9_5_None::test_exec_two_table--e:0":                            "unknown",
	"test/sql/test_update.py::UpdateFromRoundTripTest_postgresql+psycopg2_9_5_None::test_exec_two_table_plus_alias--e:0":                 "unknown",
	"test/sql/test_update.py::UpdateFromRoundTripTest_postgresql+psycopg2_9_5_None::test_exec_two_table_plus_alias--e:1":                 "unknown",
}

var sqlAlchemyFBlackList19_1 = blacklist{
	"test/aaa_profiling/test_orm.py::JoinedEagerLoadTest::test_fetch_results--f:0":                                                                         "unknown",
	"test/aaa_profiling/test_orm.py::JoinedEagerLoadTest::test_fetch_results--f:1":                                                                         "unknown",
	"test/dialect/postgresql/test_reflection.py::ReflectionTest_postgresql+psycopg2_9_5_None::test_foreign_key_option_inspection--f:0":                     "unknown",
	"test/dialect/postgresql/test_types.py::FloatCoercionTest_postgresql+psycopg2_9_5_None::test_float_coercion--f:0":                                      "unknown",
	"test/dialect/postgresql/test_types.py::JSONRoundTripTest_postgresql+psycopg2_9_5_None::test_fixed_round_trip_python--f:0":                             "unknown",
	"test/dialect/test_suite.py::ServerSideCursorsTest_postgresql+psycopg2_9_5_None::test_for_update_expr--f:0":                                            "unknown",
	"test/dialect/test_suite.py::ServerSideCursorsTest_postgresql+psycopg2_9_5_None::test_for_update_string--f:0":                                          "unknown",
	"test/engine/test_reflection.py::ReflectionTest_postgresql+psycopg2_9_5_None::test_fk_options--f:0":                                                    "unknown",
	"test/ext/test_associationproxy.py::ComparatorTest::test_filter_eq_None_nul--f:0":                                                                      "unknown",
	"test/ext/test_associationproxy.py::ComparatorTest::test_filter_eq_null_nul_nul--f:0":                                                                  "unknown",
	"test/ext/test_baked.py::LikeQueryTest::test_first_no_result--f:1":                                                                                     "unknown",
	"test/ext/test_baked.py::ResultPostCriteriaTest::test_first--f:0":                                                                                      "unknown",
	"test/orm/inheritance/test_polymorphic_rel.py::PolymorphicJoinsTest_postgresql+psycopg2_9_5_None::test_from_alias--f:1":                                "unknown",
	"test/orm/inheritance/test_polymorphic_rel.py::PolymorphicPolymorphicTest_postgresql+psycopg2_9_5_None::test_filter_on_baseclass--f:0":                 "unknown",
	"test/orm/inheritance/test_polymorphic_rel.py::PolymorphicPolymorphicTest_postgresql+psycopg2_9_5_None::test_from_alias--f:0":                          "unknown",
	"test/orm/inheritance/test_relationship.py::SameNamedPropTwoPolymorphicSubClassesTest::test_fixed_w_poly_joined--f:0":                                  "unknown",
	"test/orm/inheritance/test_relationship.py::SameNamedPropTwoPolymorphicSubClassesTest::test_fixed_w_poly_subquery--f:0":                                "unknown",
	"test/orm/inheritance/test_relationship.py::SameNamedPropTwoPolymorphicSubClassesTest::test_free_w_poly_joined--f:0":                                   "unknown",
	"test/orm/inheritance/test_relationship.py::SameNamedPropTwoPolymorphicSubClassesTest::test_free_w_poly_subquery--f:0":                                 "unknown",
	"test/orm/test_cycles.py::InheritTestTwo::test_flush--f:0":                                                                                             "unknown",
	"test/orm/test_cycles.py::InheritTestTwo::test_flush--f:1":                                                                                             "unknown",
	"test/orm/test_froms.py::AddEntityEquivalenceTest::test_add_entity_equivalence--f:0":                                                                   "unknown",
	"test/orm/test_froms.py::AddEntityEquivalenceTest::test_add_entity_equivalence--f:1":                                                                   "unknown",
	"test/orm/test_froms.py::ColumnAccessTest::test_table_anonymous_expression_from_self_twice--f:1":                                                       "unknown",
	"test/orm/test_froms.py::CustomJoinTest::test_double_same_mappers--f:0":                                                                                "unknown",
	"test/orm/test_froms.py::ExternalColumnsTest::test_external_columns--f:0":                                                                              "unknown",
	"test/orm/test_froms.py::ExternalColumnsTest::test_external_columns_bad--f:0":                                                                          "unknown",
	"test/orm/test_froms.py::ExternalColumnsTest::test_external_columns_compound--f:0":                                                                     "unknown",
	"test/orm/test_froms.py::ExternalColumnsTest::test_external_columns_joinedload--f:0":                                                                   "unknown",
	"test/orm/test_froms.py::FromSelfTest::test_aliases--f:0":                                                                                              "unknown",
	"test/orm/test_froms.py::FromSelfTest::test_filter--f:0":                                                                                               "unknown",
	"test/orm/test_froms.py::FromSelfTest::test_group_by--f:0":                                                                                             "unknown",
	"test/orm/test_froms.py::FromSelfTest::test_having--f:0":                                                                                               "unknown",
	"test/orm/test_froms.py::FromSelfTest::test_join--f:0":                                                                                                 "unknown",
	"test/orm/test_froms.py::FromSelfTest::test_multiple_entities--f:0":                                                                                    "unknown",
	"test/orm/test_froms.py::FromSelfTest::test_multiple_with_column_entities--f:0":                                                                        "unknown",
	"test/orm/test_froms.py::FromSelfTest::test_no_joinedload--f:0":                                                                                        "unknown",
	"test/orm/test_froms.py::InstancesTest::test_contains_eager--f:0":                                                                                      "unknown",
	"test/orm/test_froms.py::InstancesTest::test_contains_eager_aliased--f:0":                                                                              "unknown",
	"test/orm/test_froms.py::InstancesTest::test_contains_eager_aliased_instances--f:0":                                                                    "unknown",
	"test/orm/test_froms.py::InstancesTest::test_contains_eager_chaining--f:0":                                                                             "unknown",
	"test/orm/test_froms.py::InstancesTest::test_contains_eager_chaining_aliased_endpoint--f:0":                                                            "unknown",
	"test/orm/test_froms.py::InstancesTest::test_contains_eager_multi_alias--f:0":                                                                          "unknown",
	"test/orm/test_froms.py::InstancesTest::test_contains_eager_multi_aliased--f:0":                                                                        "unknown",
	"test/orm/test_froms.py::InstancesTest::test_contains_eager_multi_string_alias--f:0":                                                                   "unknown",
	"test/orm/test_froms.py::InstancesTest::test_contains_eager_string_alias--f:0":                                                                         "unknown",
	"test/orm/test_froms.py::InstancesTest::test_from_alias_four--f:0":                                                                                     "unknown",
	"test/orm/test_froms.py::InstancesTest::test_from_alias_one--f:0":                                                                                      "unknown",
	"test/orm/test_froms.py::InstancesTest::test_from_alias_three--f:0":                                                                                    "unknown",
	"test/orm/test_froms.py::InstancesTest::test_from_alias_two--f:0":                                                                                      "unknown",
	"test/orm/test_froms.py::InstancesTest::test_mixed_eager_contains_with_limit--f:0":                                                                     "unknown",
	"test/orm/test_froms.py::MixedEntitiesTest::test_add_multi_columns--f:0":                                                                               "unknown",
	"test/orm/test_froms.py::MixedEntitiesTest::test_alias_naming--f:0":                                                                                    "unknown",
	"test/orm/test_froms.py::MixedEntitiesTest::test_aliased_adapt_on_names--f:0":                                                                          "unknown",
	"test/orm/test_froms.py::MixedEntitiesTest::test_aliased_multi_mappers--f:0":                                                                           "unknown",
	"test/orm/test_froms.py::MixedEntitiesTest::test_column_from_limited_joinedload--f:0":                                                                  "unknown",
	"test/orm/test_froms.py::MixedEntitiesTest::test_column_queries--f:0":                                                                                  "unknown",
	"test/orm/test_froms.py::MixedEntitiesTest::test_correlated_subquery--f:0":                                                                             "unknown",
	"test/orm/test_froms.py::MixedEntitiesTest::test_expression_selectable_matches_mzero--f:0":                                                             "unknown",
	"test/orm/test_froms.py::MixedEntitiesTest::test_multi_columns--f:0":                                                                                   "unknown",
	"test/orm/test_froms.py::MixedEntitiesTest::test_multi_columns_2--f:0":                                                                                 "unknown",
	"test/orm/test_froms.py::MixedEntitiesTest::test_multi_mappers--f:0":                                                                                   "unknown",
	"test/orm/test_froms.py::MixedEntitiesTest::test_raw_columns--f:0":                                                                                     "unknown",
	"test/orm/test_froms.py::MixedEntitiesTest::test_self_referential--f:0":                                                                                "unknown",
	"test/orm/test_froms.py::MixedEntitiesTest::test_values--f:0":                                                                                          "unknown",
	"test/orm/test_froms.py::MixedEntitiesTest::test_values_specific_order_by--f:0":                                                                        "unknown",
	"test/orm/test_froms.py::MixedEntitiesTest::test_values_with_boolean_selects--f:0":                                                                     "unknown",
	"test/orm/test_froms.py::MixedEntitiesTest::test_with_entities--f:0":                                                                                   "unknown",
	"test/orm/test_froms.py::QueryCorrelatesLikeSelect::test_as_scalar_query_auto_correlate--f:0":                                                          "unknown",
	"test/orm/test_froms.py::QueryCorrelatesLikeSelect::test_as_scalar_query_correlate_off--f:0":                                                           "unknown",
	"test/orm/test_froms.py::QueryCorrelatesLikeSelect::test_as_scalar_query_explicit_correlate--f:0":                                                      "unknown",
	"test/orm/test_froms.py::QueryCorrelatesLikeSelect::test_as_scalar_select_auto_correlate--f:0":                                                         "unknown",
	"test/orm/test_froms.py::QueryCorrelatesLikeSelect::test_as_scalar_select_correlate_off--f:0":                                                          "unknown",
	"test/orm/test_froms.py::QueryCorrelatesLikeSelect::test_as_scalar_select_explicit_correlate--f:0":                                                     "unknown",
	"test/orm/test_froms.py::RawSelectTest::test_select--f:0":                                                                                              "unknown",
	"test/orm/test_froms.py::SelectFromTest::test_aliased_class_vs_nonaliased--f:0":                                                                        "unknown",
	"test/orm/test_froms.py::SelectFromTest::test_differentiate_self_external--f:0":                                                                        "unknown",
	"test/orm/test_froms.py::SelectFromTest::test_filter_by_selected_from--f:0":                                                                            "unknown",
	"test/orm/test_froms.py::SelectFromTest::test_join--f:0":                                                                                               "unknown",
	"test/orm/test_froms.py::SelectFromTest::test_join_ent_selected_from--f:0":                                                                             "unknown",
	"test/orm/test_froms.py::SelectFromTest::test_join_mapper_order_by--f:0":                                                                               "unknown",
	"test/orm/test_froms.py::SelectFromTest::test_join_no_order_by--f:0":                                                                                   "unknown",
	"test/orm/test_froms.py::SelectFromTest::test_join_relname_from_selected_from--f:0":                                                                    "unknown",
	"test/orm/test_froms.py::SelectFromTest::test_more_joins--f:0":                                                                                         "unknown",
	"test/orm/test_froms.py::SelectFromTest::test_replace_with_eager--f:0":                                                                                 "unknown",
	"test/orm/test_froms.py::SelectFromTest::test_replace_with_select--f:0":                                                                                "unknown",
	"test/orm/test_froms.py::SelectFromTest::test_select_from_aliased--f:0":                                                                                "unknown",
	"test/orm/test_froms.py::SelectFromTest::test_very_nested_joins_with_joinedload--f:0":                                                                  "unknown",
	"test/orm/test_froms.py::TestOverlyEagerEquivalentCols::test_equivs--f:0":                                                                              "unknown",
	"test/orm/test_generative.py::RelationshipsTest::test_from--f:0":                                                                                       "unknown",
	"test/orm/test_hasparent.py::ParentRemovalTest::test_fresh_state_negative--f:0":                                                                        "unknown",
	"test/orm/test_hasparent.py::ParentRemovalTest::test_fresh_state_positive--f:0":                                                                        "unknown",
	"test/orm/test_hasparent.py::ParentRemovalTest::test_fresh_state_positive--f:1":                                                                        "unknown",
	"test/orm/test_joins.py::JoinTest::test_from_joinpoint--f:0":                                                                                           "unknown",
	"test/orm/test_joins.py::JoinTest::test_from_self_resets_joinpaths--f:0":                                                                               "unknown",
	"test/orm/test_joins.py::JoinTest::test_full_flag--f:0":                                                                                                "unknown",
	"test/orm/test_mapper.py::MapperTest::test_function--f:1":                                                                                              "unknown",
	"test/orm/test_naturalpks.py::NaturalPKTest_postgresql+psycopg2_9_5_None::test_flush_new_pk_after_expire--f:0":                                         "unknown",
	"test/orm/test_query.py::InvalidGenerationsTest::test_from_statement--f:1":                                                                             "unknown",
	"test/orm/test_query.py::ParentTest::test_from_entity_query_entity--f:0":                                                                               "unknown",
	"test/orm/test_query.py::ParentTest::test_from_entity_standalone_fn--f:0":                                                                              "unknown",
	"test/orm/test_query.py::QueryClsTest::test_fn_expr--f:0":                                                                                              "unknown",
	"test/orm/test_query.py::QueryClsTest::test_fn_expr_undocumented_query_constructor--f:0":                                                               "unknown",
	"test/orm/test_query.py::QueryClsTest::test_fn_get--f:0":                                                                                               "unknown",
	"test/orm/test_query.py::QueryClsTest::test_fn_m2o_lazyload--f:0":                                                                                      "unknown",
	"test/orm/test_query.py::QueryClsTest::test_fn_o2m_lazyload--f:0":                                                                                      "unknown",
	"test/orm/test_query.py::SliceTest::test_first--f:0":                                                                                                   "unknown",
	"test/orm/test_query.py::SynonymTest::test_froms_aliased_col--f:0":                                                                                     "unknown",
	"test/orm/test_query.py::TextTest::test_fragment--f:0":                                                                                                 "unknown",
	"test/orm/test_query.py::TextTest::test_fulltext--f:0":                                                                                                 "unknown",
	"test/orm/test_query.py::TextWarningTest::test_filter--f:0":                                                                                            "unknown",
	"test/orm/test_query.py::TextWarningTest::test_from_statement--f:0":                                                                                    "unknown",
	"test/orm/test_query.py::WithTransientOnNone::test_filter_with_transient_warn_for_none_against_non_pk--f:1":                                            "unknown",
	"test/orm/test_transaction.py::SessionTransactionTest_postgresql+psycopg2_9_5_None::test_failed_rollback_deactivates_transaction--f:0":                 "unknown",
	"test/orm/test_transaction.py::SessionTransactionTest_postgresql+psycopg2_9_5_None::test_failed_rollback_deactivates_transaction_ctx_integration--f:0": "unknown",
	"test/orm/test_versioning.py::NoBumpOnRelationshipTest_postgresql+psycopg2_9_5_None::test_functional_counter--f:0":                                     "unknown",
	"test/orm/test_versioning.py::NoBumpOnRelationshipTest_postgresql+psycopg2_9_5_None::test_functional_counter--f:1":                                     "unknown",
	"test/sql/test_constraints.py::ConstraintGenTest_postgresql+psycopg2_9_5_None::test_fk_cant_drop_cycled_unnamed--f:0":                                  "unknown",
	"test/sql/test_constraints.py::ConstraintGenTest_postgresql+psycopg2_9_5_None::test_fk_column_auto_alter_inline_constraint_create--f:0":                "unknown",
	"test/sql/test_constraints.py::ConstraintGenTest_postgresql+psycopg2_9_5_None::test_fk_column_use_alter_constraint_create--f:0":                        "unknown",
	"test/sql/test_constraints.py::ConstraintGenTest_postgresql+psycopg2_9_5_None::test_fk_column_use_alter_inline_constraint_create--f:0":                 "unknown",
	"test/sql/test_constraints.py::ConstraintGenTest_postgresql+psycopg2_9_5_None::test_fk_table_auto_alter_constraint_create--f:0":                        "unknown",
	"test/sql/test_constraints.py::ConstraintGenTest_postgresql+psycopg2_9_5_None::test_fk_table_use_alter_constraint_create--f:0":                         "unknown",
	"test/sql/test_join_rewriting.py::JoinExecTest_postgresql+psycopg2_9_5_None::test_f_b1a_where_in_b2a--f:1":                                             "unknown",
	"test/sql/test_resultset.py::ResultProxyTest_postgresql+psycopg2_9_5_None::test_fetch_partial_result_map--f:0":                                         "unknown",
	"test/sql/test_resultset.py::ResultProxyTest_postgresql+psycopg2_9_5_None::test_fetch_unordered_result_map--f:0":                                       "unknown",
	"test/sql/test_resultset.py::ResultProxyTest_postgresql+psycopg2_9_5_None::test_fetchmany--f:0":                                                        "unknown",
	"test/sql/test_resultset.py::ResultProxyTest_postgresql+psycopg2_9_5_None::test_fetchone_til_end--f:1":                                                 "unknown",
}

var sqlAlchemyGBlackList19_1 = blacklist{}
var sqlAlchemyHBlackList19_1 = blacklist{}
var sqlAlchemyIBlackList19_1 = blacklist{}
var sqlAlchemyJBlackList19_1 = blacklist{}

var sqlAlchemyKBlackList19_1 = blacklist{
	"test/orm/test_lockmode.py::ForUpdateTest::test_key_share--k:1":                                                                 "unknown",
	"test/orm/test_transaction.py::NaturalPKRollbackTest_postgresql+psycopg2_9_5_None::test_key_replaced_by_update_nested--k:0":     "unknown",
	"test/sql/test_metadata.py::UseExistingTest::test_keep_existing_add_column--k:0":                                                "unknown",
	"test/sql/test_metadata.py::UseExistingTest::test_keep_existing_add_column_no_orig--k:0":                                        "unknown",
	"test/sql/test_metadata.py::UseExistingTest::test_keep_existing_add_column_no_reflection--k:0":                                  "unknown",
	"test/sql/test_metadata.py::UseExistingTest::test_keep_existing_coltype--k:0":                                                   "unknown",
	"test/sql/test_metadata.py::UseExistingTest::test_keep_existing_coltype_no_orig--k:0":                                           "unknown",
	"test/sql/test_metadata.py::UseExistingTest::test_keep_existing_coltype_no_reflection--k:0":                                     "unknown",
	"test/sql/test_metadata.py::UseExistingTest::test_keep_existing_quote--k:0":                                                     "unknown",
	"test/sql/test_metadata.py::UseExistingTest::test_keep_existing_quote_no_orig--k:0":                                             "unknown",
	"test/sql/test_metadata.py::UseExistingTest::test_keep_existing_quote_no_reflection--k:0":                                       "unknown",
	"test/sql/test_metadata.py::UseExistingTest::test_keep_plus_existing_raises--k:0":                                               "unknown",
	"test/sql/test_resultset.py::KeyTargetingTest_postgresql+psycopg2_9_5_None::test_keyed_accessor_composite_conflict_2--k:0":      "unknown",
	"test/sql/test_resultset.py::KeyTargetingTest_postgresql+psycopg2_9_5_None::test_keyed_accessor_composite_keys_precedent--k:0":  "unknown",
	"test/sql/test_resultset.py::KeyTargetingTest_postgresql+psycopg2_9_5_None::test_keyed_accessor_composite_labeled--k:0":         "unknown",
	"test/sql/test_resultset.py::KeyTargetingTest_postgresql+psycopg2_9_5_None::test_keyed_accessor_composite_names_precedent--k:0": "unknown",
	"test/sql/test_resultset.py::KeyTargetingTest_postgresql+psycopg2_9_5_None::test_keyed_accessor_single--k:0":                    "unknown",
	"test/sql/test_resultset.py::KeyTargetingTest_postgresql+psycopg2_9_5_None::test_keyed_accessor_single_labeled--k:0":            "unknown",
	"test/sql/test_resultset.py::KeyTargetingTest_postgresql+psycopg2_9_5_None::test_keyed_accessor_wschema--k:0":                   "unknown",
}

var sqlAlchemyLBlackList19_1 = blacklist{}
var sqlAlchemyMBlackList19_1 = blacklist{}
var sqlAlchemyNBlackList19_1 = blacklist{}
var sqlAlchemyOBlackList19_1 = blacklist{}
var sqlAlchemyPBlackList19_1 = blacklist{}
var sqlAlchemyQBlackList19_1 = blacklist{}
var sqlAlchemyRBlackList19_1 = blacklist{}
var sqlAlchemySBlackList19_1 = blacklist{}
var sqlAlchemyTBlackList19_1 = blacklist{}
var sqlAlchemyUBlackList19_1 = blacklist{}
var sqlAlchemyVBlackList19_1 = blacklist{}
var sqlAlchemyWBlackList19_1 = blacklist{}
var sqlAlchemyXBlackList19_1 = blacklist{}
var sqlAlchemyYBlackList19_1 = blacklist{}
var sqlAlchemyZBlackList19_1 = blacklist{}
