// Copyright 2018 The Cockroach Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
// implied. See the License for the specific language governing
// permissions and limitations under the License. See the AUTHORS file
// for names of contributors.

package main

var sqlalchemyBlacklists = blacklistsForVersion{
	{"sqlalchemy1 v2.2", "sqlAlchemy1BlackList19_1", sqlAlchemy1BlackList19_1, "", nil},
	{"sqlalchemy2 v2.2", "sqlAlchemy2BlackList19_1", sqlAlchemy2BlackList19_1, "", nil},
	{"sqlalchemy3 v2.2", "sqlAlchemy3BlackList19_1", sqlAlchemy3BlackList19_1, "", nil},
	{"sqlalchemy4 v2.2", "sqlAlchemy4BlackList19_1", sqlAlchemy4BlackList19_1, "", nil},
	{"sqlalchemy5 v2.2", "sqlAlchemy5BlackList19_1", sqlAlchemy5BlackList19_1, "", nil},
	{"sqlalchemy1 v19.1", "sqlAlchemy1BlackList19_1", sqlAlchemy1BlackList19_1, "", nil},
	{"sqlalchemy2 v19.1", "sqlAlchemy2BlackList19_1", sqlAlchemy2BlackList19_1, "", nil},
	{"sqlalchemy3 v19.1", "sqlAlchemy3BlackList19_1", sqlAlchemy3BlackList19_1, "", nil},
	{"sqlalchemy4 v19.1", "sqlAlchemy4BlackList19_1", sqlAlchemy4BlackList19_1, "", nil},
	{"sqlalchemy5 v19.1", "sqlAlchemy5BlackList19_1", sqlAlchemy5BlackList19_1, "", nil},
}

// Please keep these lists alphabetized for easy diffing.
// After a failed run, an updated version of this blacklist should be available
// in the test log.
// In this blacklist, all tests have a "--x:n" appended to them. The x
// represents the testset that it was run in, the n is for when there are
// duplicates within a single testset.
var sqlAlchemy1BlackList19_1 = blacklist{}

var sqlAlchemy2BlackList19_1 = blacklist{}

var sqlAlchemy3BlackList19_1 = blacklist{
	"test/dialect/mssql/test_types.py::BinaryTest::test_large_binary--l:0":                                                                                 "unknown",
	"test/dialect/mssql/test_types.py::BinaryTest::test_large_legacy_types--l:0":                                                                           "unknown",
	"test/dialect/mysql/test_on_duplicate.py::OnDuplicateTest::test_last_inserted_id--l:0":                                                                 "unknown",
	"test/dialect/mysql/test_reflection.py::TypeReflectionTest::test_legacy_enum_types--l:0":                                                               "unknown",
	"test/dialect/oracle/test_types.py::LOBFetchTest::test_large_stream--l:0":                                                                              "unknown",
	"test/dialect/oracle/test_types.py::LOBFetchTest::test_large_stream_single_arraysize--l:0":                                                             "unknown",
	"test/dialect/oracle/test_types.py::LOBFetchTest::test_lobs_with_convert--l:0":                                                                         "unknown",
	"test/dialect/oracle/test_types.py::LOBFetchTest::test_lobs_with_convert_many_rows--l:0":                                                               "unknown",
	"test/dialect/oracle/test_types.py::LOBFetchTest::test_lobs_with_convert_raw--l:0":                                                                     "unknown",
	"test/dialect/oracle/test_types.py::LOBFetchTest::test_lobs_without_convert--l:0":                                                                      "unknown",
	"test/dialect/oracle/test_types.py::LOBFetchTest::test_lobs_without_convert_many_rows--l:0":                                                            "unknown",
	"test/dialect/oracle/test_types.py::SetInputSizesTest::test_long--l:0":                                                                                 "unknown",
	"test/dialect/oracle/test_types.py::TypesTest::test_long_type--l:0":                                                                                    "unknown",
	"test/dialect/oracle/test_types.py::TypesTest::test_longstring--l:0":                                                                                   "unknown",
	"test/dialect/postgresql/test_types.py::HStoreRoundTripTest::test_literal_round_trip--l:0":                                                             "unknown",
	"test/dialect/postgresql/test_types.py::HashableFlagORMTest::test_json--j:0":                                                                           "unknown",
	"test/dialect/postgresql/test_types.py::HashableFlagORMTest::test_jsonb--j:0":                                                                          "unknown",
	"test/dialect/test_firebird.py::BuggyDomainReflectionTest::test_lowercase_default_name--l:0":                                                           "unknown",
	"test/dialect/test_sqlite.py::ConstraintReflectionTest::test_legacy_quoted_identifiers_unit--l:0":                                                      "unknown",
	"test/dialect/test_sqlite.py::TypeReflectionTest::test_lookup_direct_lookup--l:0":                                                                      "unknown",
	"test/dialect/test_sqlite.py::TypeReflectionTest::test_lookup_direct_type_affinity--l:0":                                                               "unknown",
	"test/dialect/test_sqlite.py::TypeReflectionTest::test_lookup_direct_unsupported_args--l:0":                                                            "unknown",
	"test/dialect/test_suite.py::CompoundSelectTest_postgresql+psycopg2_9_5_None::test_limit_offset_aliased_selectable_in_unions--l:0":                     "unknown",
	"test/dialect/test_suite.py::CompoundSelectTest_postgresql+psycopg2_9_5_None::test_limit_offset_in_unions_from_alias--l:0":                             "unknown",
	"test/dialect/test_suite.py::CompoundSelectTest_postgresql+psycopg2_9_5_None::test_limit_offset_selectable_in_unions--l:0":                             "unknown",
	"test/dialect/test_suite.py::DateHistoricTest_postgresql+psycopg2_9_5_None::test_literal--l:0":                                                         "unknown",
	"test/dialect/test_suite.py::DateTest_postgresql+psycopg2_9_5_None::test_literal--l:0":                                                                 "unknown",
	"test/dialect/test_suite.py::DateTimeCoercedToDateTimeTest_postgresql+psycopg2_9_5_None::test_literal--l:0":                                            "unknown",
	"test/dialect/test_suite.py::DateTimeHistoricTest_postgresql+psycopg2_9_5_None::test_literal--l:0":                                                     "unknown",
	"test/dialect/test_suite.py::DateTimeMicrosecondsTest_postgresql+psycopg2_9_5_None::test_literal--l:0":                                                 "unknown",
	"test/dialect/test_suite.py::DateTimeTest_postgresql+psycopg2_9_5_None::test_literal--l:0":                                                             "unknown",
	"test/dialect/test_suite.py::IntegerTest_postgresql+psycopg2_9_5_None::test_literal--l:0":                                                              "unknown",
	"test/dialect/test_suite.py::LastrowidTest_postgresql+psycopg2_9_5_None::test_last_inserted_id--l:0":                                                   "unknown",
	"test/dialect/test_suite.py::LimitOffsetTest_postgresql+psycopg2_9_5_None::test_limit_offset_nobinds--l:0":                                             "unknown",
	"test/dialect/test_suite.py::ReturningTest_postgresql+psycopg2_9_5_None::test_last_inserted_id_implicit_returning--l:0":                                "unknown",
	"test/dialect/test_suite.py::ReturningTest_postgresql+psycopg2_9_5_None::test_last_inserted_id_implicit_returning--l:1":                                "unknown",
	"test/dialect/test_suite.py::StringTest_postgresql+psycopg2_9_5_None::test_literal--l:0":                                                               "unknown",
	"test/dialect/test_suite.py::StringTest_postgresql+psycopg2_9_5_None::test_literal_backslashes--l:0":                                                   "unknown",
	"test/dialect/test_suite.py::StringTest_postgresql+psycopg2_9_5_None::test_literal_quoting--l:0":                                                       "unknown",
	"test/dialect/test_suite.py::TextTest_postgresql+psycopg2_9_5_None::test_literal--l:0":                                                                 "unknown",
	"test/dialect/test_suite.py::TextTest_postgresql+psycopg2_9_5_None::test_literal_backslashes--l:0":                                                     "unknown",
	"test/dialect/test_suite.py::TextTest_postgresql+psycopg2_9_5_None::test_literal_percentsigns--l:0":                                                    "unknown",
	"test/dialect/test_suite.py::TextTest_postgresql+psycopg2_9_5_None::test_literal_quoting--l:0":                                                         "unknown",
	"test/dialect/test_suite.py::TimeMicrosecondsTest_postgresql+psycopg2_9_5_None::test_literal--l:0":                                                     "unknown",
	"test/dialect/test_suite.py::TimeTest_postgresql+psycopg2_9_5_None::test_literal--l:0":                                                                 "unknown",
	"test/dialect/test_suite.py::TimestampMicrosecondsTest::test_literal--l:0":                                                                             "unknown",
	"test/dialect/test_suite.py::UnicodeTextTest_postgresql+psycopg2_9_5_None::test_literal--l:0":                                                          "unknown",
	"test/dialect/test_suite.py::UnicodeVarcharTest_postgresql+psycopg2_9_5_None::test_literal--l:0":                                                       "unknown",
	"test/engine/test_execute.py::HandleErrorTest_postgresql+psycopg2_9_5_None::test_legacy_dbapi_error--l:0":                                              "unknown",
	"test/engine/test_execute.py::HandleErrorTest_postgresql+psycopg2_9_5_None::test_legacy_dbapi_error_no_ad_hoc_context--l:0":                            "unknown",
	"test/engine/test_execute.py::HandleErrorTest_postgresql+psycopg2_9_5_None::test_legacy_dbapi_error_non_dbapi_error--l:0":                              "unknown",
	"test/engine/test_logging.py::EchoTest::test_echo_flag_independence--l:0":                                                                              "unknown",
	"test/engine/test_logging.py::LogParamsTest::test_error_large_dict--l:0":                                                                               "unknown",
	"test/engine/test_logging.py::LogParamsTest::test_error_large_list--l:0":                                                                               "unknown",
	"test/engine/test_logging.py::LogParamsTest::test_exception_format_dict_param--l:0":                                                                    "unknown",
	"test/engine/test_logging.py::LogParamsTest::test_exception_format_unexpected_member_parameter--l:0":                                                   "unknown",
	"test/engine/test_logging.py::LogParamsTest::test_exception_format_unexpected_parameter--l:0":                                                          "unknown",
	"test/engine/test_logging.py::LogParamsTest::test_log_large_dict--l:0":                                                                                 "unknown",
	"test/engine/test_logging.py::LogParamsTest::test_log_large_list--l:0":                                                                                 "unknown",
	"test/engine/test_logging.py::LogParamsTest::test_log_large_multi_parameter--l:0":                                                                      "unknown",
	"test/engine/test_logging.py::LogParamsTest::test_log_large_parameter_multiple--l:0":                                                                   "unknown",
	"test/engine/test_logging.py::LogParamsTest::test_log_large_parameter_single--l:0":                                                                     "unknown",
	"test/engine/test_logging.py::LogParamsTest::test_result_large_param--l:0":                                                                             "unknown",
	"test/engine/test_logging.py::LoggingNameTest::test_named_logger_echoflags_execute--l:0":                                                               "unknown",
	"test/engine/test_logging.py::LoggingNameTest::test_named_logger_execute--l:0":                                                                         "unknown",
	"test/engine/test_logging.py::LoggingNameTest::test_named_logger_execute_after_dispose--l:0":                                                           "unknown",
	"test/engine/test_logging.py::LoggingNameTest::test_named_logger_names_after_dispose--l:0":                                                             "unknown",
	"test/engine/test_logging.py::LoggingNameTest::test_unnamed_logger_echoflags_execute--l:0":                                                             "unknown",
	"test/engine/test_logging.py::LoggingNameTest::test_unnamed_logger_execute--l:0":                                                                       "unknown",
	"test/engine/test_pool.py::PoolEventsTest::test_listen_targets_scope--l:0":                                                                             "unknown",
	"test/ext/test_automap.py::AutomapInhTest::test_joined_inheritance_reflect--j:0":                                                                       "unknown",
	"test/ext/test_horizontal_shard.py::LazyLoadIdentityKeyTest::test_lazy_load_from_db--l:0":                                                              "unknown",
	"test/ext/test_horizontal_shard.py::LazyLoadIdentityKeyTest::test_lazy_load_from_identity_map--l:0":                                                    "unknown",
	"test/ext/test_horizontal_shard.py::LazyLoadIdentityKeyTest::test_lazy_load_no_baked_conflict--l:0":                                                    "unknown",
	"test/orm/inheritance/test_assorted_poly.py::Ticket2419Test::test_join_w_eager_w_any--j:0":                                                             "unknown",
	"test/orm/inheritance/test_poly_loading.py::FixtureLoadTest::test_load_company_plus_employees--l:0":                                                    "unknown",
	"test/orm/inheritance/test_poly_loading.py::LoadBaseAndSubWEagerRelMapped::test_load--l:0":                                                             "unknown",
	"test/orm/inheritance/test_poly_loading.py::LoadBaseAndSubWEagerRelOpt::test_load--l:0":                                                                "unknown",
	"test/orm/inheritance/test_poly_persistence.py::RoundTripTest::test_lazy_auto--l:0":                                                                    "unknown",
	"test/orm/inheritance/test_poly_persistence.py::RoundTripTest::test_lazy_inclbase_redefcol_unions--l:0":                                                "unknown",
	"test/orm/inheritance/test_poly_persistence.py::RoundTripTest::test_lazy_inclbase_unions--l:0":                                                         "unknown",
	"test/orm/inheritance/test_poly_persistence.py::RoundTripTest::test_lazy_joins--l:0":                                                                   "unknown",
	"test/orm/inheritance/test_poly_persistence.py::RoundTripTest::test_lazy_none--l:0":                                                                    "unknown",
	"test/orm/inheritance/test_poly_persistence.py::RoundTripTest::test_lazy_redefcol_auto--l:0":                                                           "unknown",
	"test/orm/inheritance/test_poly_persistence.py::RoundTripTest::test_lazy_redefcol_joins--l:0":                                                          "unknown",
	"test/orm/inheritance/test_poly_persistence.py::RoundTripTest::test_lazy_redefcol_none--l:0":                                                           "unknown",
	"test/orm/inheritance/test_poly_persistence.py::RoundTripTest::test_lazy_redefcol_unions--l:0":                                                         "unknown",
	"test/orm/inheritance/test_poly_persistence.py::RoundTripTest::test_lazy_unions--l:0":                                                                  "unknown",
	"test/orm/inheritance/test_polymorphic_rel.py::PolymorphicAliasedJoinsTest_postgresql+psycopg2_9_5_None::test_join_from_columns_or_subclass_nine--j:0": "unknown",
	"test/orm/inheritance/test_polymorphic_rel.py::PolymorphicAliasedJoinsTest_postgresql+psycopg2_9_5_None::test_loads_at_once--l:0":                      "unknown",
	"test/orm/inheritance/test_polymorphic_rel.py::PolymorphicJoinsTest_postgresql+psycopg2_9_5_None::test_join_from_columns_or_subclass_nine--j:0":        "unknown",
	"test/orm/inheritance/test_polymorphic_rel.py::PolymorphicJoinsTest_postgresql+psycopg2_9_5_None::test_loads_at_once--l:0":                             "unknown",
	"test/orm/inheritance/test_polymorphic_rel.py::PolymorphicPolymorphicTest_postgresql+psycopg2_9_5_None::test_join_from_columns_or_subclass_nine--j:0":  "unknown",
	"test/orm/inheritance/test_polymorphic_rel.py::PolymorphicPolymorphicTest_postgresql+psycopg2_9_5_None::test_loads_at_once--l:0":                       "unknown",
	"test/orm/inheritance/test_polymorphic_rel.py::PolymorphicTest_postgresql+psycopg2_9_5_None::test_join_from_columns_or_subclass_nine--j:0":             "unknown",
	"test/orm/inheritance/test_polymorphic_rel.py::PolymorphicTest_postgresql+psycopg2_9_5_None::test_loads_at_once--l:0":                                  "unknown",
	"test/orm/inheritance/test_polymorphic_rel.py::PolymorphicUnionsTest_postgresql+psycopg2_9_5_None::test_join_from_columns_or_subclass_nine--j:0":       "unknown",
	"test/orm/inheritance/test_polymorphic_rel.py::PolymorphicUnionsTest_postgresql+psycopg2_9_5_None::test_loads_at_once--l:0":                            "unknown",
	"test/orm/inheritance/test_relationship.py::JoinAcrossJoinedInhMultiPath::test_joinedload--j:1":                                                        "unknown",
	"test/orm/inheritance/test_relationship.py::JoinedloadOverWPolyAliased::test_local_wpoly--l:0":                                                         "unknown",
	"test/orm/inheritance/test_relationship.py::JoinedloadOverWPolyAliased::test_local_wpoly_innerjoins--l:0":                                              "unknown",
	"test/orm/inheritance/test_relationship.py::JoinedloadOverWPolyAliased::test_local_wpoly_innerjoins_roundtrip--l:0":                                    "unknown",
	"test/orm/inheritance/test_relationship.py::JoinedloadOverWPolyAliased::test_local_wpoly_innerjoins_roundtrip--l:1":                                    "unknown",
	"test/orm/inheritance/test_relationship.py::SelfReferentialJ2JSelfTest::test_join_explicit_alias--j:0":                                                 "unknown",
	"test/orm/inheritance/test_relationship.py::SubClassEagerToSubClassTest::test_joinedload--j:0":                                                         "unknown",
	"test/orm/inheritance/test_selects.py::InheritingSelectablesTest::test_load--l:0":                                                                      "unknown",
	"test/orm/inheritance/test_with_poly.py::PolymorphicAliasedJoinsTest::test_join_to_join_entities--j:1":                                                 "unknown",
	"test/orm/inheritance/test_with_poly.py::PolymorphicJoinsTest::test_join_base_to_sub--j:0":                                                             "unknown",
	"test/orm/inheritance/test_with_poly.py::PolymorphicJoinsTest::test_join_to_join_columns--j:0":                                                         "unknown",
	"test/orm/inheritance/test_with_poly.py::PolymorphicJoinsTest::test_join_to_join_entities--j:0":                                                        "unknown",
	"test/orm/test_bundle.py::BundleTest::test_joins_from_adapted_entities--j:0":                                                                           "unknown",
	"test/orm/test_default_strategies.py::DefaultStrategyOptionsTest::test_joined_with_subqueryload--j:1":                                                  "unknown",
	"test/orm/test_deferred.py::InheritanceTest::test_load_only_subclass_of_type--l:1":                                                                     "unknown",
	"test/orm/test_eager_relations.py::CorrelatedSubqueryTest::test_labeled_on_limitid_alias--l:0":                                                         "unknown",
	"test/orm/test_eager_relations.py::CorrelatedSubqueryTest::test_labeled_on_limitid_alias--l:1":                                                         "unknown",
	"test/orm/test_eager_relations.py::CorrelatedSubqueryTest::test_labeled_on_limitid_noalias--l:0":                                                       "unknown",
	"test/orm/test_eager_relations.py::CorrelatedSubqueryTest::test_labeled_on_limitid_noalias--l:1":                                                       "unknown",
	"test/orm/test_eager_relations.py::EagerTest::test_late_compile--l:0":                                                                                  "unknown",
	"test/orm/test_eager_relations.py::EagerTest::test_limit--l:0":                                                                                         "unknown",
	"test/orm/test_eager_relations.py::EagerTest::test_limit_2--l:0":                                                                                       "unknown",
	"test/orm/test_eager_relations.py::EagerTest::test_limit_3--l:0":                                                                                       "unknown",
	"test/orm/test_eager_relations.py::EagerTest::test_limit_4--l:0":                                                                                       "unknown",
	"test/orm/test_eager_relations.py::LazyLoadOptSpecificityTest::test_lazyload_aliased_abs_bcs_one--l:0":                                                 "unknown",
	"test/orm/test_eager_relations.py::LazyLoadOptSpecificityTest::test_lazyload_aliased_abs_bcs_two--l:0":                                                 "unknown",
	"test/orm/test_eager_relations.py::LazyLoadOptSpecificityTest::test_lazyload_plus_joined_aliased_abs_bcs--l:0":                                         "unknown",
	"test/orm/test_eager_relations.py::LazyLoadOptSpecificityTest::test_lazyload_plus_joined_unaliased_abs_bcs--l:0":                                       "unknown",
	"test/orm/test_eager_relations.py::LazyLoadOptSpecificityTest::test_lazyload_unaliased_abs_bcs_one--l:0":                                               "unknown",
	"test/orm/test_eager_relations.py::LazyLoadOptSpecificityTest::test_lazyload_unaliased_abs_bcs_two--l:0":                                               "unknown",
	"test/orm/test_eager_relations.py::LoadOnExistingTest::test_load_two_levels_collection_to_collection--l:0":                                             "unknown",
	"test/orm/test_eager_relations.py::LoadOnExistingTest::test_load_two_levels_collection_to_scalar--l:0":                                                 "unknown",
	"test/orm/test_eager_relations.py::LoadOnExistingTest::test_loads_second_level_collection_to_collection--l:0":                                          "unknown",
	"test/orm/test_eager_relations.py::LoadOnExistingTest::test_loads_second_level_collection_to_scalar--l:0":                                              "unknown",
	"test/orm/test_eager_relations.py::SelfReferentialEagerTest::test_lazy_fallback_doesnt_affect_eager--l:0":                                              "unknown",
	"test/orm/test_eager_relations.py::SubqueryTest::test_label_anonymizing--l:0":                                                                          "unknown",
	"test/orm/test_events.py::MapperEventsTest::test_listen_doesnt_force_compile--l:0":                                                                     "unknown",
	"test/orm/test_events.py::SessionLifecycleEventsTest::test_loaded_as_persistent--l:0":                                                                  "unknown",
	"test/orm/test_expire.py::ExpireTest::test_lazyload_autoflushes--l:0":                                                                                  "unknown",
	"test/orm/test_inspect.py::TestORMInspection::test_local_table--l:0":                                                                                   "unknown",
	"test/orm/test_joins.py::JoinTest::test_left_is_none--l:0":                                                                                             "unknown",
	"test/orm/test_joins.py::JoinTest::test_left_is_none_and_query_has_no_entities--l:0":                                                                   "unknown",
	"test/orm/test_joins.py::SelfReferentialTest::test_join_to_nonaliased--j:0":                                                                            "unknown",
	"test/orm/test_lazy_relations.py::CompositeSimpleM2OTest::test_dont_use_get_pj_is_different--l:0":                                                      "unknown",
	"test/orm/test_lazy_relations.py::CompositeSimpleM2OTest::test_use_get_reverseorder--l:0":                                                              "unknown",
	"test/orm/test_lazy_relations.py::CompositeSimpleM2OTest::test_use_get_sameorder--l:0":                                                                 "unknown",
	"test/orm/test_lazy_relations.py::CorrelatedTest::test_correlated_lazyload--l:0":                                                                       "unknown",
	"test/orm/test_lazy_relations.py::GetterStateTest::test_get_empty_passive_no_initialize--l:0":                                                          "unknown",
	"test/orm/test_lazy_relations.py::GetterStateTest::test_get_empty_passive_return_never_set--l:0":                                                       "unknown",
	"test/orm/test_lazy_relations.py::GetterStateTest::test_get_populated_passive_no_initialize--l:0":                                                      "unknown",
	"test/orm/test_lazy_relations.py::GetterStateTest::test_get_populated_passive_return_never_set--l:0":                                                   "unknown",
	"test/orm/test_lazy_relations.py::GetterStateTest::test_history_empty_passive_no_initialize--l:0":                                                      "unknown",
	"test/orm/test_lazy_relations.py::GetterStateTest::test_history_empty_passive_return_never_set--l:0":                                                   "unknown",
	"test/orm/test_lazy_relations.py::GetterStateTest::test_history_populated_passive_no_initialize--l:0":                                                  "unknown",
	"test/orm/test_lazy_relations.py::GetterStateTest::test_history_populated_passive_return_never_set--l:0":                                               "unknown",
	"test/orm/test_lazy_relations.py::GetterStateTest::test_no_use_get_params_missing--l:0":                                                                "unknown",
	"test/orm/test_lazy_relations.py::GetterStateTest::test_no_use_get_params_not_hashable--l:0":                                                           "unknown",
	"test/orm/test_lazy_relations.py::GetterStateTest::test_no_use_get_params_not_hashable_on_pending--l:0":                                                "unknown",
	"test/orm/test_lazy_relations.py::LazyTest::test_backrefs_dont_lazyload--l:0":                                                                          "unknown",
	"test/orm/test_lazy_relations.py::LazyTest::test_basic--l:0":                                                                                           "unknown",
	"test/orm/test_lazy_relations.py::LazyTest::test_callable_bind--l:0":                                                                                   "unknown",
	"test/orm/test_lazy_relations.py::LazyTest::test_custom_bind--l:0":                                                                                     "unknown",
	"test/orm/test_lazy_relations.py::LazyTest::test_distinct--l:0":                                                                                        "unknown",
	"test/orm/test_lazy_relations.py::LazyTest::test_double--l:0":                                                                                          "unknown",
	"test/orm/test_lazy_relations.py::LazyTest::test_limit--l:0":                                                                                           "unknown",
	"test/orm/test_lazy_relations.py::LazyTest::test_many_to_many--l:0":                                                                                    "unknown",
	"test/orm/test_lazy_relations.py::LazyTest::test_many_to_one--l:0":                                                                                     "unknown",
	"test/orm/test_lazy_relations.py::LazyTest::test_many_to_one_binds--l:0":                                                                               "unknown",
	"test/orm/test_lazy_relations.py::LazyTest::test_needs_parent--l:0":                                                                                    "unknown",
	"test/orm/test_lazy_relations.py::LazyTest::test_no_orphan--l:0":                                                                                       "unknown",
	"test/orm/test_lazy_relations.py::LazyTest::test_one_to_many_scalar--l:0":                                                                              "unknown",
	"test/orm/test_lazy_relations.py::LazyTest::test_orderby--l:0":                                                                                         "unknown",
	"test/orm/test_lazy_relations.py::LazyTest::test_orderby_desc--l:0":                                                                                    "unknown",
	"test/orm/test_lazy_relations.py::LazyTest::test_orderby_secondary--l:0":                                                                               "unknown",
	"test/orm/test_lazy_relations.py::LazyTest::test_uselist_false_warning--l:0":                                                                           "unknown",
	"test/orm/test_lazy_relations.py::LazyTest::test_uses_get--l:0":                                                                                        "unknown",
	"test/orm/test_lazy_relations.py::LazyTest::test_uses_get_compatible_types--l:0":                                                                       "unknown",
	"test/orm/test_lazy_relations.py::M2OGetTest::test_m2o_noload--l:0":                                                                                    "unknown",
	"test/orm/test_lazy_relations.py::O2MWOSideFixedTest::test_lazyload_assert_expected_sql--l:0":                                                          "unknown",
	"test/orm/test_lazy_relations.py::O2MWOSideFixedTest::test_lazyload_people_no_other_exists--l:0":                                                       "unknown",
	"test/orm/test_lazy_relations.py::O2MWOSideFixedTest::test_lazyload_people_other_exists--l:0":                                                          "unknown",
	"test/orm/test_lazy_relations.py::RefersToSelfLazyLoadInterferenceTest::test_lazy_doesnt_interfere--l:0":                                               "unknown",
	"test/orm/test_lazy_relations.py::TypeCoerceTest::test_lazyload_singlecast--l:0":                                                                       "unknown",
	"test/orm/test_load_on_fks.py::FlushOnPendingTest::test_annoying_autoflush_one--l:0":                                                                   "unknown",
	"test/orm/test_load_on_fks.py::FlushOnPendingTest::test_annoying_autoflush_two--l:0":                                                                   "unknown",
	"test/orm/test_load_on_fks.py::FlushOnPendingTest::test_dont_load_if_no_keys--l:0":                                                                     "unknown",
	"test/orm/test_load_on_fks.py::LoadOnFKsTest::test_autoflush_load_on_pending_on_pending--l:0":                                                          "unknown",
	"test/orm/test_load_on_fks.py::LoadOnFKsTest::test_autoflush_on_pending--l:0":                                                                          "unknown",
	"test/orm/test_load_on_fks.py::LoadOnFKsTest::test_backref_doesnt_double--l:0":                                                                         "unknown",
	"test/orm/test_load_on_fks.py::LoadOnFKsTest::test_collection_load_from_pending_no_sql--l:0":                                                           "unknown",
	"test/orm/test_load_on_fks.py::LoadOnFKsTest::test_collection_load_from_pending_populated--l:0":                                                        "unknown",
	"test/orm/test_load_on_fks.py::LoadOnFKsTest::test_enable_rel_loading_allows_backref_event--l:0":                                                       "unknown",
	"test/orm/test_load_on_fks.py::LoadOnFKsTest::test_enable_rel_loading_on_persistent_allows_backref_event--l:0":                                         "unknown",
	"test/orm/test_load_on_fks.py::LoadOnFKsTest::test_load_on_pending_allows_backref_event--l:0":                                                          "unknown",
	"test/orm/test_load_on_fks.py::LoadOnFKsTest::test_load_on_pending_with_set--l:0":                                                                      "unknown",
	"test/orm/test_load_on_fks.py::LoadOnFKsTest::test_load_on_persistent_allows_backref_event--l:0":                                                       "unknown",
	"test/orm/test_load_on_fks.py::LoadOnFKsTest::test_m2o_history_on_persistent_allows_backref_event--l:0":                                                "unknown",
	"test/orm/test_load_on_fks.py::LoadOnFKsTest::test_m2o_lazy_loader_on_pending--l:0":                                                                    "unknown",
	"test/orm/test_load_on_fks.py::LoadOnFKsTest::test_m2o_lazy_loader_on_persistent--l:0":                                                                 "unknown",
	"test/orm/test_load_on_fks.py::LoadOnFKsTest::test_m2o_lazy_loader_on_transient--l:0":                                                                  "unknown",
	"test/orm/test_load_on_fks.py::LoadOnFKsTest::test_no_load_on_pending_allows_backref_event--l:0":                                                       "unknown",
	"test/orm/test_loading.py::InstancesTest::test_cursor_close_w_failed_rowproc--l:0":                                                                     "unknown",
	"test/orm/test_loading.py::InstancesTest::test_row_proc_not_created--l:0":                                                                              "unknown",
	"test/orm/test_loading.py::MergeResultTest::test_entity_col_mix_keyed_tuple--l:0":                                                                      "unknown",
	"test/orm/test_loading.py::MergeResultTest::test_entity_col_mix_plain_tuple--l:0":                                                                      "unknown",
	"test/orm/test_loading.py::MergeResultTest::test_none_entity--l:0":                                                                                     "unknown",
	"test/orm/test_loading.py::MergeResultTest::test_single_column--l:0":                                                                                   "unknown",
	"test/orm/test_loading.py::MergeResultTest::test_single_entity--l:0":                                                                                   "unknown",
	"test/orm/test_lockmode.py::CompileTest::test_default_update--l:0":                                                                                     "unknown",
	"test/orm/test_lockmode.py::CompileTest::test_mysql_read--l:0":                                                                                         "unknown",
	"test/orm/test_lockmode.py::CompileTest::test_not_supported_by_dialect_should_just_use_update--l:0":                                                    "unknown",
	"test/orm/test_lockmode.py::CompileTest::test_oracle_update--l:0":                                                                                      "unknown",
	"test/orm/test_lockmode.py::CompileTest::test_oracle_update_skip_locked--l:0":                                                                          "unknown",
	"test/orm/test_lockmode.py::CompileTest::test_postgres_for_no_key_nowait_update--l:0":                                                                  "unknown",
	"test/orm/test_lockmode.py::CompileTest::test_postgres_for_no_key_update--l:0":                                                                         "unknown",
	"test/orm/test_lockmode.py::CompileTest::test_postgres_read--l:0":                                                                                      "unknown",
	"test/orm/test_lockmode.py::CompileTest::test_postgres_read_nowait--l:0":                                                                               "unknown",
	"test/orm/test_lockmode.py::CompileTest::test_postgres_update--l:0":                                                                                    "unknown",
	"test/orm/test_lockmode.py::CompileTest::test_postgres_update_of--l:0":                                                                                 "unknown",
	"test/orm/test_lockmode.py::CompileTest::test_postgres_update_of_entity--l:0":                                                                          "unknown",
	"test/orm/test_lockmode.py::CompileTest::test_postgres_update_of_entity_list--l:0":                                                                     "unknown",
	"test/orm/test_lockmode.py::CompileTest::test_postgres_update_of_list--l:0":                                                                            "unknown",
	"test/orm/test_lockmode.py::CompileTest::test_postgres_update_skip_locked--l:0":                                                                        "unknown",
	"test/orm/test_lockmode.py::ForUpdateTest::test_key_share--l:0":                                                                                        "unknown",
	"test/orm/test_lockmode.py::ForUpdateTest::test_nowait--l:0":                                                                                           "unknown",
	"test/orm/test_lockmode.py::ForUpdateTest::test_of_single_col--l:0":                                                                                    "unknown",
	"test/orm/test_lockmode.py::ForUpdateTest::test_plain--l:0":                                                                                            "unknown",
	"test/orm/test_lockmode.py::ForUpdateTest::test_read--l:0":                                                                                             "unknown",
	"test/orm/test_lockmode.py::LegacyLockModeTest::test_false_legacy--l:0":                                                                                "unknown",
	"test/orm/test_lockmode.py::LegacyLockModeTest::test_nowait_legacy--l:0":                                                                               "unknown",
	"test/orm/test_lockmode.py::LegacyLockModeTest::test_plain_legacy--l:0":                                                                                "unknown",
	"test/orm/test_lockmode.py::LegacyLockModeTest::test_read_legacy--l:0":                                                                                 "unknown",
	"test/orm/test_lockmode.py::LegacyLockModeTest::test_unknown_legacy_lock_mode--l:0":                                                                    "unknown",
	"test/orm/test_mapper.py::MapperTest::test_key_error_raised_class_mapper--k:1":                                                                         "unknown",
	"test/orm/test_mapper.py::OptionsTest::test_lazy_options--l:0":                                                                                         "unknown",
	"test/orm/test_mapper.py::OptionsTest::test_lazy_options_with_limit--l:0":                                                                              "unknown",
	"test/orm/test_merge.py::MutableMergeTest::test_list--l:0":                                                                                             "unknown",
	"test/orm/test_naturalpks.py::NaturalPKTest_postgresql+psycopg2_9_5_None::test_load_after_expire--l:0":                                                 "unknown",
	"test/orm/test_of_type.py::PolymorphicAliasedJoinsTest::test_joinedload_explicit_withpoly--j:0":                                                        "unknown",
	"test/orm/test_of_type.py::PolymorphicAliasedJoinsTest::test_joinedload_implicit_withpoly--j:0":                                                        "unknown",
	"test/orm/test_of_type.py::PolymorphicAliasedJoinsTest::test_joinedload_stacked_of_type--j:0":                                                          "unknown",
	"test/orm/test_of_type.py::PolymorphicAliasedJoinsTest::test_joinedload_stacked_of_type--j:1":                                                          "unknown",
	"test/orm/test_of_type.py::PolymorphicJoinsTest::test_join_to_subclass_five--j:0":                                                                      "unknown",
	"test/orm/test_of_type.py::PolymorphicJoinsTest::test_join_to_subclass_four--j:0":                                                                      "unknown",
	"test/orm/test_of_type.py::PolymorphicJoinsTest::test_join_to_subclass_one--j:0":                                                                       "unknown",
	"test/orm/test_of_type.py::PolymorphicJoinsTest::test_join_to_subclass_three--j:0":                                                                     "unknown",
	"test/orm/test_of_type.py::PolymorphicJoinsTest::test_join_to_subclass_two--j:0":                                                                       "unknown",
	"test/orm/test_of_type.py::PolymorphicJoinsTest::test_joinedload_explicit_withpoly--j:0":                                                               "unknown",
	"test/orm/test_of_type.py::PolymorphicJoinsTest::test_joinedload_implicit_withpoly--j:0":                                                               "unknown",
	"test/orm/test_of_type.py::PolymorphicJoinsTest::test_joinedload_stacked_of_type--j:0":                                                                 "unknown",
	"test/orm/test_of_type.py::PolymorphicPolymorphicTest::test_joinedload_explicit_withpoly--j:0":                                                         "unknown",
	"test/orm/test_of_type.py::PolymorphicPolymorphicTest::test_joinedload_implicit_withpoly--j:0":                                                         "unknown",
	"test/orm/test_of_type.py::PolymorphicPolymorphicTest::test_joinedload_stacked_of_type--j:0":                                                           "unknown",
	"test/orm/test_of_type.py::PolymorphicUnionsTest::test_joinedload_explicit_withpoly--j:0":                                                              "unknown",
	"test/orm/test_of_type.py::PolymorphicUnionsTest::test_joinedload_implicit_withpoly--j:0":                                                              "unknown",
	"test/orm/test_of_type.py::PolymorphicUnionsTest::test_joinedload_stacked_of_type--j:0":                                                                "unknown",
	"test/orm/test_of_type.py::SubclassRelationshipTest::test_lazyload--l:0":                                                                               "unknown",
	"test/orm/test_options.py::PickleTest::test_legacy_opt_setstate--l:0":                                                                                  "unknown",
	"test/orm/test_pickled.py::OptionsTest::test_load--l:0":                                                                                                "unknown",
	"test/orm/test_query.py::ExpressionTest::test_join--j:1":                                                                                               "unknown",
	"test/orm/test_query.py::ExpressionTest::test_label--l:0":                                                                                              "unknown",
	"test/orm/test_query.py::ExpressionTest::test_labeled_subquery--l:0":                                                                                   "unknown",
	"test/orm/test_query.py::ExpressionTest::test_legacy_order_by_cancelled_allows_assertions--l:0":                                                        "unknown",
	"test/orm/test_query.py::FilterTest::test_limit_offset--l:0":                                                                                           "unknown",
	"test/orm/test_query.py::GetTest::test_load--l:0":                                                                                                      "unknown",
	"test/orm/test_query.py::SliceTest::test_limit_offset_applies--l:0":                                                                                    "unknown",
	"test/orm/test_query.py::SynonymTest::test_joins--j:0":                                                                                                 "unknown",
	"test/orm/test_query.py::YieldTest::test_joinedload_m2o_ok--j:0":                                                                                       "unknown",
	"test/orm/test_relationships.py::CompositeJoinPartialFK::test_joins_fully--j:0":                                                                        "unknown",
	"test/orm/test_relationships.py::InvalidRelationshipEscalationTestM2M::test_local_col_setup--l:0":                                                      "unknown",
	"test/orm/test_relationships.py::RemoteForeignBetweenColsTest::test_lazyload--l:0":                                                                     "unknown",
	"test/orm/test_relationships.py::SecondaryNestedJoinTest::test_lazyload--l:0":                                                                          "unknown",
	"test/orm/test_selectin_relations.py::EagerTest::test_limit--l:0":                                                                                      "unknown",
	"test/orm/test_selectin_relations.py::LoadOnExistingTest::test_load_two_levels_collection_to_collection--l:0":                                          "unknown",
	"test/orm/test_selectin_relations.py::LoadOnExistingTest::test_load_two_levels_collection_to_scalar--l:0":                                              "unknown",
	"test/orm/test_selectin_relations.py::LoadOnExistingTest::test_loads_second_level_collection_to_collection--l:0":                                       "unknown",
	"test/orm/test_selectin_relations.py::LoadOnExistingTest::test_loads_second_level_collection_to_scalar--l:0":                                           "unknown",
	"test/orm/test_selectin_relations.py::SelfReferentialTest::test_lazy_fallback_doesnt_affect_eager--l:0":                                                "unknown",
	"test/orm/test_selectin_relations.py::SingleInhSubclassTest::test_load--l:0":                                                                           "unknown",
	"test/orm/test_subquery_relations.py::EagerTest::test_limit--l:0":                                                                                      "unknown",
	"test/orm/test_subquery_relations.py::LoadOnExistingTest::test_load_two_levels_collection_to_collection--l:0":                                          "unknown",
	"test/orm/test_subquery_relations.py::LoadOnExistingTest::test_load_two_levels_collection_to_scalar--l:0":                                              "unknown",
	"test/orm/test_subquery_relations.py::LoadOnExistingTest::test_loads_second_level_collection_to_collection--l:0":                                       "unknown",
	"test/orm/test_subquery_relations.py::LoadOnExistingTest::test_loads_second_level_collection_to_scalar--l:0":                                           "unknown",
	"test/orm/test_subquery_relations.py::SelfReferentialTest::test_lazy_fallback_doesnt_affect_eager--l:0":                                                "unknown",
	"test/orm/test_transaction.py::NaturalPKRollbackTest_postgresql+psycopg2_9_5_None::test_key_replaced_by_update_nested--k:0":                            "unknown",
	"test/orm/test_transaction.py::NaturalPKRollbackTest_postgresql+psycopg2_9_5_None::test_key_replaced_by_update_nested--k:1":                            "unknown",
	"test/orm/test_unitofwork.py::SaveTest::test_lazyattr_commit--l:0":                                                                                     "unknown",
	"test/orm/test_utils.py::PathRegistryTest::test_length--l:0":                                                                                           "unknown",
	"test/sql/test_insert_exec.py::InsertExecTest_postgresql+psycopg2_9_5_None::test_lastrow_accessor_five--l:0":                                           "unknown",
	"test/sql/test_insert_exec.py::InsertExecTest_postgresql+psycopg2_9_5_None::test_lastrow_accessor_four--l:0":                                           "unknown",
	"test/sql/test_insert_exec.py::InsertExecTest_postgresql+psycopg2_9_5_None::test_lastrow_accessor_one--l:0":                                            "unknown",
	"test/sql/test_insert_exec.py::InsertExecTest_postgresql+psycopg2_9_5_None::test_lastrow_accessor_six--l:0":                                            "unknown",
	"test/sql/test_insert_exec.py::InsertExecTest_postgresql+psycopg2_9_5_None::test_lastrow_accessor_three--l:0":                                          "unknown",
	"test/sql/test_insert_exec.py::InsertExecTest_postgresql+psycopg2_9_5_None::test_lastrow_accessor_two--l:0":                                            "unknown",
	"test/sql/test_insert_exec.py::InsertExecTest_postgresql+psycopg2_9_5_None::test_lastrowid_zero--l:0":                                                  "unknown",
	"test/sql/test_labels.py::MaxIdentTest::test_too_long_name_disallowed--l:0":                                                                            "unknown",
	"test/sql/test_lateral.py::LateralTest::test_from_function--l:1":                                                                                       "unknown",
	"test/sql/test_lateral.py::LateralTest::test_join_lateral_w_select_subquery--l:1":                                                                      "unknown",
	"test/sql/test_lateral.py::LateralTest::test_plain_join--l:1":                                                                                          "unknown",
	"test/sql/test_lateral.py::LateralTest::test_select_from--l:1":                                                                                         "unknown",
	"test/sql/test_lateral.py::LateralTest::test_standalone--l:1":                                                                                          "unknown",
	"test/sql/test_metadata.py::UseExistingTest::test_keep_existing_add_column--k:0":                                                                       "unknown",
	"test/sql/test_metadata.py::UseExistingTest::test_keep_existing_add_column_no_orig--k:0":                                                               "unknown",
	"test/sql/test_metadata.py::UseExistingTest::test_keep_existing_add_column_no_reflection--k:0":                                                         "unknown",
	"test/sql/test_metadata.py::UseExistingTest::test_keep_existing_coltype--k:0":                                                                          "unknown",
	"test/sql/test_metadata.py::UseExistingTest::test_keep_existing_coltype_no_orig--k:0":                                                                  "unknown",
	"test/sql/test_metadata.py::UseExistingTest::test_keep_existing_coltype_no_reflection--k:0":                                                            "unknown",
	"test/sql/test_metadata.py::UseExistingTest::test_keep_existing_quote--k:0":                                                                            "unknown",
	"test/sql/test_metadata.py::UseExistingTest::test_keep_existing_quote_no_orig--k:0":                                                                    "unknown",
	"test/sql/test_metadata.py::UseExistingTest::test_keep_existing_quote_no_reflection--k:0":                                                              "unknown",
	"test/sql/test_metadata.py::UseExistingTest::test_keep_plus_existing_raises--k:0":                                                                      "unknown",
	"test/sql/test_metadata.py::UseExistingTest::test_keep_plus_existing_raises--k:1":                                                                      "unknown",
	"test/sql/test_query.py::QueryTest_postgresql+psycopg2_9_5_None::test_like_ops--l:0":                                                                   "unknown",
	"test/sql/test_query.py::QueryTest_postgresql+psycopg2_9_5_None::test_literal_in--l:0":                                                                 "unknown",
	"test/sql/test_resultset.py::KeyTargetingTest_postgresql+psycopg2_9_5_None::test_keyed_accessor_composite_conflict_2--k:0":                             "unknown",
	"test/sql/test_resultset.py::KeyTargetingTest_postgresql+psycopg2_9_5_None::test_keyed_accessor_composite_keys_precedent--k:0":                         "unknown",
	"test/sql/test_resultset.py::KeyTargetingTest_postgresql+psycopg2_9_5_None::test_keyed_accessor_composite_labeled--k:0":                                "unknown",
	"test/sql/test_resultset.py::KeyTargetingTest_postgresql+psycopg2_9_5_None::test_keyed_accessor_composite_names_precedent--k:0":                        "unknown",
	"test/sql/test_resultset.py::KeyTargetingTest_postgresql+psycopg2_9_5_None::test_keyed_accessor_single--k:0":                                           "unknown",
	"test/sql/test_resultset.py::KeyTargetingTest_postgresql+psycopg2_9_5_None::test_keyed_accessor_single_labeled--k:0":                                   "unknown",
	"test/sql/test_resultset.py::KeyTargetingTest_postgresql+psycopg2_9_5_None::test_keyed_accessor_wschema--k:0":                                          "unknown",
	"test/sql/test_resultset.py::ResultProxyTest_postgresql+psycopg2_9_5_None::test_keys--k:0":                                                             "unknown",
	"test/sql/test_resultset.py::ResultProxyTest_postgresql+psycopg2_9_5_None::test_keys_anon_labels--k:0":                                                 "unknown",
	"test/sql/test_resultset.py::ResultProxyTest_postgresql+psycopg2_9_5_None::test_keys_anon_labels--k:1":                                                 "unknown",
	"test/sql/test_resultset.py::ResultProxyTest_postgresql+psycopg2_9_5_None::test_len--l:0":                                                              "unknown",
	"test/sql/test_returning.py::ReturningTest_postgresql+psycopg2_9_5_None::test_labeling--l:0":                                                           "unknown",
	"test/sql/test_returning.py::ReturningTest_postgresql+psycopg2_9_5_None::test_literal_returning--l:0":                                                  "unknown",
	"test/sql/test_types.py::BinaryTest_postgresql+psycopg2_9_5_None::test_literal_roundtrip--l:0":                                                         "unknown",
	"test/sql/test_types.py::BooleanTest::test_literal_processor_coercion_native_0--l:0":                                                                   "unknown",
	"test/sql/test_types.py::BooleanTest::test_literal_processor_coercion_native_1--l:0":                                                                   "unknown",
	"test/sql/test_types.py::BooleanTest::test_literal_processor_coercion_native_false--l:0":                                                               "unknown",
	"test/sql/test_types.py::BooleanTest::test_literal_processor_coercion_native_int_out_of_range--l:0":                                                    "unknown",
	"test/sql/test_types.py::BooleanTest::test_literal_processor_coercion_native_str--l:0":                                                                 "unknown",
	"test/sql/test_types.py::BooleanTest::test_literal_processor_coercion_native_true--l:0":                                                                "unknown",
	"test/sql/test_types.py::BooleanTest::test_literal_processor_coercion_nonnative_0--l:0":                                                                "unknown",
	"test/sql/test_types.py::BooleanTest::test_literal_processor_coercion_nonnative_1--l:0":                                                                "unknown",
	"test/sql/test_types.py::BooleanTest::test_literal_processor_coercion_nonnative_false--l:0":                                                            "unknown",
	"test/sql/test_types.py::BooleanTest::test_literal_processor_coercion_nonnative_str--l:0":                                                              "unknown",
	"test/sql/test_types.py::BooleanTest::test_literal_processor_coercion_nonnative_true--l:0":                                                             "unknown",
	"test/sql/test_types.py::EnumTest_postgresql+psycopg2_9_5_None::test_lookup_failure--l:0":                                                              "unknown",
	"test/sql/test_types.py::ExpressionTest::test_literal_adapt--l:0":                                                                                      "unknown",
	"test/sql/test_update.py::UpdateTest::test_labels_no_collision--l:0":                                                                                   "unknown",
}

var sqlAlchemy4BlackList19_1 = blacklist{}

var sqlAlchemy5BlackList19_1 = blacklist{}
