{
 "title": "Resilience testing",
 "tags": [
  "drt",
  "cct",
  "resilience",
  "testing"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "sys_uptime{job=\"cockroachdb\"}"
    }
   },
   {
    "name": "instances",
    "label": "Instances",
    "query": {
     "query": "label_values(sys_uptime{job=\"cockroachdb\",cluster=\"$cluster\"},instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU",
   "type": "heatmap",
   "description": "A heatmap in which each horizontal stripe reflects per-node CPU usage (0.0-1.0).",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 1 },
   "repeat": "g",
   "targets": [
    {
     "expr": "sys_cpu_combined_percent_normalized{instance=~\"$instances\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Range count",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ranges{cluster=\"$cluster\", instance=~\"$instances\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Unavailable Ranges",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ranges_unavailable{instance=~\"$instances\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Under-Replicated",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 19, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ranges_underreplicated{instance=~\"$instances\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Tripped Replicas",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 22, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kv_replica_circuit_breaker_num_tripped_replicas{instance=~\"$instances\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Live Nodes",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 16, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "min (liveness_livenodes{instance=~\"$instances\"})",
     "legendFormat": "Live Nodes"
    },
    {
     "expr": "min (liveness_livenodes{instance=~\"$instances\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Replicas",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 19, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum (replicas{instance=~\"$instances\"})",
     "legendFormat": "Live Nodes"
    }
   ]
  },
  {
   "title": "Leaseholders",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum (replicas_leaseholders{instance=~\"$instances\"})",
     "legendFormat": "Live Nodes"
    }
   ]
  },
  {
   "title": "TPCC regular workload successful QPS",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(workload_tpcc_newOrder_success_total{cluster=\"cct-232-workloads\", job=\"workload-2112\"}[$__rate_interval])",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(workload_tpcc_delivery_success_total{cluster=\"cct-232-workloads\", job=\"workload-2112\"}[$__rate_interval])",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(workload_tpcc_orderStatus_success_total{cluster=\"cct-232-workloads\", job=\"workload-2112\"}[$__rate_interval])",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(workload_tpcc_payment_success_total{cluster=\"cct-232-workloads\", job=\"workload-2112\"}[$__rate_interval])",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(workload_tpcc_stockLevel_success_total{cluster=\"cct-232-workloads\", job=\"workload-2112\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "TPCC drop workload imports running",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 9, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "jobs_import_currently_running{cluster=\"$cluster\", instance=~\"$instances\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "jobs_import_currently_paused{cluster=\"$cluster\", instance=~\"$instances\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "jobs_import_currently_idle{cluster=\"$cluster\", instance=~\"$instances\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "TPCC drop workload successful QPS",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(workload_tpcc_newOrder_success_total{cluster=\"cct-232-workloads\", job=\"workload-2113\"}[$__rate_interval])",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(workload_tpcc_delivery_success_total{cluster=\"cct-232-workloads\", job=\"workload-2113\"}[$__rate_interval])",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(workload_tpcc_orderStatus_success_total{cluster=\"cct-232-workloads\", job=\"workload-2113\"}[$__rate_interval])",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(workload_tpcc_payment_success_total{cluster=\"cct-232-workloads\", job=\"workload-2113\"}[$__rate_interval])",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(workload_tpcc_stockLevel_success_total{cluster=\"cct-232-workloads\", job=\"workload-2113\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Schemachange workload operations",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(workload_schemachange_opOk_duration_seconds_count{cluster=\"cct-232-workloads\", job=\"workload-2115\"}[$__rate_interval])",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(workload_schemachange_txnOk_duration_seconds_count{cluster=\"cct-232-workloads\", job=\"workload-2115\"}[$__rate_interval])",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(workload_schemachange_txnCmtErr_duration_seconds_count{cluster=\"cct-232-workloads\", job=\"workload-2115\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "KV workload p95 latencies",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(workload_kv_read_duration_seconds_bucket{cluster=\"cct-232-workloads\",job=\"workload-2114\"}[$__rate_interval])) by (le))",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(workload_kv_write_duration_seconds_bucket{cluster=\"cct-232-workloads\",job=\"workload-2114\"}[$__rate_interval])) by (le))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Ranges",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "ranges{cluster=\"$cluster\", instance=~\"$instances\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Admission Control",
   "type": "heatmap",
   "description": "A heatmap in which each horizontal stripe reflects per-node CPU usage (0.0-1.0).",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "rate(admission_wait_durations_kv_sum{instance=~\"$instances\"}[$__rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "IO Admission Control",
   "type": "heatmap",
   "description": "A heatmap in which each horizontal stripe reflects per-node CPU usage (0.0-1.0).",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 28 },
   "targets": [
    {
     "expr": "rate(admission_wait_durations_kv_stores_sum{instance=~\"$instances\"}[$__rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "RSS % (23.2+ only)",
   "type": "heatmap",
   "description": "https://github.com/cockroachdb/cockroach/pull/101542",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 28 },
   "targets": [
    {
     "expr": "sys_rss{instance=~\"$instances\"}/sys_totalmem{instance=~\"$instances\"}",
     "legendFormat": "{{instance}} s{{store}}"
    }
   ]
  },
  {
   "title": "Disk slow / stalled events",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "storage_disk_slow{cluster=\"$cluster\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "storage_disk_stalled{cluster=\"$cluster\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "kv exec latencies",
   "type": "heatmap",
   "description": "Execution latencies as perceived by KV servers (i.e. not measuring time spent on the KV client).\n\nThese include contention, etc, so these being elevated does not imply that KV is causing high latencies.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 33 },
   "targets": [
    {
     "expr": "sum by (le) (rate(exec_latency_bucket{instance=~\"$instances\"}[$__rate_interval])) / ignoring(le) group_left sum (rate(exec_latency_count{instance=~\"$instances\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "sql service latencies",
   "type": "heatmap",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 39 },
   "targets": [
    {
     "expr": "# We take the combined rate histogram of the latencies. Then we compute the rate count (i.e. how many requests/sec we are handling) and divide each entry of the histogram by that number. In other words, at each point in time, the buckets will now add up to 1 instead of adding up to the ops/s. This is nicer for coloring and you can say things like \"50% of all requests had a latency in this bucket\".\nsum by (le) (rate(sql_service_latency_bucket{instance=~\"$instances\"}[$__rate_interval])) / ignoring(le) group_left sum (rate(sql_service_latency_count{instance=~\"$instances\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "kv exec p50/90/99/max",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "histogram_quantile(1.0, sum by (le)(rate(exec_latency_bucket{instance=~\"$instances\"}[$__rate_interval])))",
     "legendFormat": "p_max"
    },
    {
     "expr": "histogram_quantile(0.99, sum by (le)(rate(exec_latency_bucket{instance=~\"$instances\"}[$__rate_interval])))",
     "legendFormat": "p_99"
    },
    {
     "expr": "histogram_quantile(0.9, sum by (le)(rate(exec_latency_bucket{instance=~\"$instances\"}[$__rate_interval])))",
     "legendFormat": "p_90"
    },
    {
     "expr": "histogram_quantile(0.5, sum by (le)(rate(exec_latency_bucket{instance=~\"$instances\"}[$__rate_interval])))",
     "legendFormat": "p_50"
    }
   ]
  },
  {
   "title": "sql service p50/90/99/max",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "histogram_quantile(1.0, sum by (le)(rate(sql_service_latency_bucket{instance=~\"$instances\"}[$__rate_interval])))",
     "legendFormat": "p_max"
    },
    {
     "expr": "histogram_quantile(0.99, sum by (le)(rate(sql_service_latency_bucket{instance=~\"$instances\"}[$__rate_interval])))",
     "legendFormat": "p_99"
    },
    {
     "expr": "histogram_quantile(0.9, sum by (le)(rate(sql_service_latency_bucket{instance=~\"$instances\"}[$__rate_interval])))",
     "legendFormat": "p_90"
    },
    {
     "expr": "histogram_quantile(0.5, sum by (le)(rate(sql_service_latency_bucket{instance=~\"$instances\"}[$__rate_interval])))",
     "legendFormat": "p_50"
    }
   ]
  },
  {
   "title": "KV QPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 45 },
   "targets": [
    {
     "expr": "rate(exec_latency_count{instance=~\"$instances\"}[$__rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "sql QPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
   "targets": [
    {
     "expr": "rate(sql_service_latency_count{instance=~\"$instances\"}[$__rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Go mem",
   "type": "timeseries",
   "description": "In a perfectly symmetrical cluster+workload, all nodes would consume roughly equal RSS. Heterogeneous topology and/or load imbalances can break this symmetry.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sys_go_totalbytes{instance=~\"$instances\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "sql_exec_latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(instance) (rate(sql_exec_latency_count{cluster=\"$cluster\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "WAL fsync pmax",
   "type": "heatmap",
   "description": "A heatmap in which each horizontal stripe reflects a store's fsync latency.\n\nOn 22.2 and before, we're using the logcommit latency. On 23.1, we prefer the WAL fsync latency.",
   "gridPos": { "h": 5, "w": 8, "x": 12, "y": 59 },
   "targets": [
    {
     "expr": "# NB: never OR histograms except if they have matching buckets, which is not the case here (at least when running 22.2 and 23.1 mixed). Here we OR the scalar quantiles, which is fine.\nhistogram_quantile(1, sum by (instance,store,le)(rate(storage_wal_fsync_latency_bucket{instance=~\"$instances\"}[$__rate_interval]))) or histogram_quantile(1, sum by (instance,store,le)(rate(raft_process_logcommit_latency_bucket{instance=~\"$instances\"}[$__rate_interval])))",
     "legendFormat": "{{instance}} s{{store}}"
    }
   ]
  },
  {
   "title": "SQL mem",
   "type": "timeseries",
   "description": "In a perfectly symmetrical cluster+workload, all nodes would consume roughly equal RSS. Heterogeneous topology and/or load imbalances can break this symmetry.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sql_mem_root_current{instance=~\"$instances\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Oldest protected timestamp age",
   "type": "timeseries",
   "description": "This metric tracks difference between the current time and the oldest protected timestamp. We expect a steady increase the entire duration a protected timestamp record exists. Sudden drops indicate a record being released, perhaps after a job completes. An ever-increasing duration would indicate the oldest record sticking around and preventing GC if > the configured GC TTL. If the age exceeds >2 days, that's perhaps alarming -- we've potentially prevented MVCC GC for >48h and a sudden burst of it after the record is removed could be destabilizing.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "spanconfig_kvsubscriber_oldest_protected_record_nanos{instance=~\"$instances\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Runtime", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 78 } },
  {
   "title": "Go scheduler latency",
   "type": "heatmap",
   "description": "Histogram of Go scheduler latencies, normalized to a sum of 1. In other words, if a bucket shows, say, 12%, this means that 12% of all goroutine schedules ended up in that bucket.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 79 },
   "targets": [
    {
     "expr": "# Normalize the count so that it sums up to 1 across the histogram, so we can use a [0,1] color scale.\nrate(go_scheduler_latency_bucket{instance=~\"$instances\"}[$__rate_interval]) / ignoring(le) group_left rate(go_scheduler_latency_count{instance=~\"$instances\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Storage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 88 } },
  {
   "title": "IO Admission Control Threshold",
   "type": "timeseries",
   "description": ">= 1 enables admission control",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 89 },
   "targets": [
    {
     "expr": "storage_l0_num_files{instance=~\"$instances\"}/1000",
     "legendFormat": "{{instance}} L0 files"
    },
    {
     "expr": "storage_l0_sublevels{instance=\"$instances\"}/20",
     "legendFormat": "{{instance}} sublevels"
    }
   ]
  },
  {
   "title": "WAL fsync p99s",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 89 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (instance,node_id,store,le)(rate(storage_wal_fsync_latency_bucket{instance=~\"$instances\"}[$__rate_interval])))\nor histogram_quantile(0.99, sum by (instance,node_id,store,le)(rate(raft_process_logcommit_latency_bucket{instance=~\"$instances\"}[$__rate_interval])))",
     "legendFormat": "{{instance}} s{{store}}"
    }
   ]
  },
  {
   "title": "stacked disk read",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 95 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "rate(sys_host_disk_read_bytes{instance=~\"$instances\"}[$__rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "WAL fsync latencies (v23.1+ only)",
   "type": "heatmap",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 97 },
   "targets": [
    {
     "expr": "sum by (le) (rate(storage_wal_fsync_latency_bucket{instance=~\"$instances\"}[$__rate_interval])) / ignoring(le) group_left sum (rate(storage_wal_fsync_latency_count{instance=~\"$instances\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "stacked compaction writes",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 101 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "rate(rocksdb_compacted_bytes_written{instance=~\"$instances\"}[$__rate_interval])",
     "legendFormat": "{{instance}} s{{store}}"
    }
   ]
  },
  {
   "title": "stacked disk write",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 103 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "rate(sys_host_disk_write_bytes{instance=~\"$instances\"}[$__rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Flush utilization",
   "type": "timeseries",
   "description": "Percent of time that a flush was active, per store.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 108 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "storage_flush_utilization{instance=~\"$instances\"}",
     "legendFormat": "{{instance}} s{{store}}"
    }
   ]
  },
  {
   "title": "stacked compaction reads",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 109 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "rate(rocksdb_compacted_bytes_read{instance=~\"$instances\"}[$__rate_interval])",
     "legendFormat": "{{instance}} s{{store}}"
    }
   ]
  },
  {
   "title": "Pebble snapshot-pinned bytes written stacked",
   "type": "timeseries",
   "description": "The sum of bytes of keys that would've been elided by a flush or a compaction, but couldn't because of an open LSM snapshot.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 116 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(storage_compactions_keys_pinned_bytes{instance=~\"$instances\"}[$__rate_interval])",
     "legendFormat": "{{instance}} s{{store}}"
    }
   ]
  },
  {
   "title": "Block cache hit rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 116 },
   "targets": [
    { "expression": "${Hits}/(${Hits}+${Misses})", "type": "math" }
   ]
  },
  {
   "title": "Pebble tombstone counts stacked",
   "type": "timeseries",
   "description": "The sum of the number of DELs, SINGLEDELs and RANGEDELs within each store at the current moment.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 124 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "storage_keys_tombstone_count{instance=~\"$instances\"}",
     "legendFormat": "{{instance}} s{{store}}"
    }
   ]
  },
  {
   "title": "Pebble RANGEKEYSETs stacked",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 124 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "storage_keys_range_key_set_count{instance=~\"$instances\"}",
     "legendFormat": "{{instance}} s{{store}}"
    }
   ]
  },
  {
   "title": "Iterator seeks (stacked)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 132 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(storage_iterator_internal_seeks{instance=~\"$instances\"}[$__rate_interval])",
     "legendFormat": "internal s{{store}}"
    },
    {
     "expr": "rate(storage_iterator_external_seeks{instance=~\"$instances\"}[$__rate_interval])",
     "legendFormat": "external s{{store}}"
    }
   ]
  },
  {
   "title": "Iterator steps (stacked)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 132 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(storage_iterator_external_steps{instance=~\"$instances\"}[$__rate_interval])",
     "legendFormat": "external s{{store}}"
    },
    {
     "expr": "rate(storage_iterator_internal_steps{instance=~\"$instances\"}[$__rate_interval])",
     "legendFormat": "internal s{{store}}"
    }
   ]
  },
  {
   "title": "I/O Sources (reads on the left, writes on the right)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 140 },
   "collapsed": true,
   "panels": [
    {
     "title": "compaction reads",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 100 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "rate(rocksdb_compacted_bytes_read{instance=~\"$instances\"}[$__rate_interval])",
       "legendFormat": "{{instance}} s{{store}}"
      }
     ]
    },
    {
     "title": "compaction writes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 100 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "rate(rocksdb_compacted_bytes_written{instance=~\"$instances\"}[$__rate_interval])",
       "legendFormat": "{{instance}} s{{store}}"
      }
     ]
    },
    {
     "title": "BatchRequest reads (30m avg)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 108 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "rebalancing_readbytespersecond{instance=~\"$instances\"}",
       "legendFormat": "{{instance}} s{{store}}"
      },
      { "legendFormat": "__auto" }
     ]
    },
    {
     "title": "BatchRequest writes (30m avg)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 108 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "rebalancing_writebytespersecond{instance=~\"$instances\"}",
       "legendFormat": "{{instance}} s{{store}}"
      },
      { "legendFormat": "__auto" }
     ]
    },
    {
     "title": "raft.Storage entry reads",
     "type": "timeseries",
     "description": "Bytes passed out from the `(raft.Storage).Entries` method. This is the hot path through which Raft reads from disk. (The other hot path is log appends, which are writes).",
     "gridPos": { "h": 8, "w": 10, "x": 0, "y": 116 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "rate(raft_storage_read_bytes{instance=~\"$instances\"}[$__rate_interval])",
       "legendFormat": "{{instance}} s{{store}}"
      }
     ]
    },
    {
     "title": "TODO raft log application writes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 2, "x": 10, "y": 116 }
    },
    {
     "title": "MsgApp append bytes",
     "type": "timeseries",
     "description": "These were stepped into raft, so in all likelihood got written to the raft log and soon thereafter applied.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 116 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "rate(raft_rcvd_stepped_bytes{instance=~\"$instances\"}[$__rate_interval])",
       "legendFormat": "{{instance}} s{{store}}"
      }
     ]
    },
    {
     "title": "snapshot sent (reads)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 124 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "rate(range_snapshots_sent_bytes{instance=~\"$instances\"}[$__rate_interval])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "snapshot rcvd",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 124 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "rate(range_snapshots_rcvd_bytes{instance=~\"$instances\"}[$__rate_interval])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "SQL disk spill read",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 132 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "rate(sql_disk_distsql_spilled_bytes_read{instance=~\"$instances\"}[$__rate_interval])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "SQL disk spill write",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 132 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "rate(sql_disk_distsql_spilled_bytes_written{instance=~\"$instances\"}[$__rate_interval])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "catch-up scans (TODO: bytes instead of time spent)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 140 },
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "targets": [
      {
       "expr": "rate(kv_rangefeed_catchup_scan_nanos{instance=~\"$instances\"}[$__rate_interval])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "TODO: reads via ConsistencyChecker",
     "type": "timeseries",
     "description": "we have processing nanos, but it's rate limited, we should have a metric for the bytes/sec processed.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 148 }
    }
   ]
  },
  {
   "title": "Replication",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 141 },
   "collapsed": true,
   "panels": [
    {
     "title": "logcommit latencies (v23.1+ only)",
     "type": "heatmap",
     "description": "In <23.1, this contains the raft entry fsync.\nin >=23.1, only sideloading needs to fsync in logcommit; regular entries are fsynced in a separate goroutine.",
     "gridPos": { "h": 6, "w": 11, "x": 0, "y": 101 },
     "targets": [
      {
       "expr": "sum by (le) (rate(raft_process_logcommit_latency_bucket{instance=~\"$instances\"}[$__rate_interval])) / ignoring(le) group_left sum (rate(raft_process_logcommit_latency_count{instance=~\"$instances\"}[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "raft scheduler latencies",
     "type": "heatmap",
     "description": "Duration between enqueuing a replica in the raft scheduler to processing it.\n\nNote that concurrent processing of a Replica is single-threaded, so slow raft processing on a replica that has more work to do is reflected in this histogram.",
     "gridPos": { "h": 6, "w": 11, "x": 11, "y": 101 },
     "targets": [
      {
       "expr": "sum by (le) (rate(raft_scheduler_latency_bucket{instance=~\"$instances\"}[$__rate_interval])) / ignoring(le) group_left sum (rate(raft_scheduler_latency_count{instance=~\"$instances\"}[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 142 },
   "collapsed": true,
   "panels": [
    {
     "title": "stacked net recv",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 11, "x": 0, "y": 244 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "rate(sys_host_net_recv_bytes{instance=~\"$instances\"}[$__rate_interval])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "stacked net send",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 11, "x": 11, "y": 244 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "rate(sys_host_net_send_bytes{instance=~\"$instances\"}[$__rate_interval])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "round-trip latencies",
     "type": "heatmap",
     "description": "measured from within CRDB, so unreliable under high CPU utilization.\nAlso heartbeats only happen every couple of seconds so this can miss transient spikes easily.\nThe heartbeats are subject to TCP head-of-line blocking.",
     "gridPos": { "h": 6, "w": 11, "x": 0, "y": 250 },
     "targets": [
      {
       "expr": "sum by (le) (rate(round_trip_latency_bucket{instance=~\"$instances\"}[$__rate_interval])) / ignoring(le) group_left sum (rate(round_trip_latency_count{instance=~\"$instances\"}[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}