# Prometheus configuration for cockroach clusters.
#
# Run with:
# $ prometheus -config.file=prometheus.yml
global:
  scrape_interval: 10s
  evaluation_interval: 10s

rule_files:
- "rules/alerts.rules"
- "rules/aggregation.rules"

scrape_configs:
  - job_name: 'cockroach'
    metrics_path: '/_status/vars'

    # Insecure mode:
    scheme: 'http'
    # Secure mode:
    # scheme: 'https'

    tls_config:
      insecure_skip_verify: true

    static_configs:
    - targets: ['localhost:8080']
      labels:
        cluster: 'my-cockroachdb-cluster'
