blank_issues_enabled: false
contact_links:
  - name: Security Vulnerabilities
    url: https://www.cockroachlabs.com/security/responsible-disclosure-policy/
    about: "Report a security vulnerability or security-related bug in CockroachDB or Cockroach Cloud"
  - name: CockroachDB Community Forum
    url: https://forum.cockroachlabs.com/
    about: "For general questions about CockroachDB"
  - name: Enterprise Support
    url: https://support.cockroachlabs.com
    about: "Enterprise Support"
