--
-- The TPC-DS database can be restored from backup (only scale factors of 1 and
-- 10 - about 1GB and 10GB respectively - are available at the moment):
--
--   RESTORE DATABASE tpcds FROM 'gs://cockroach-fixtures/workload/tpcds/scalefactor=1/backup';
--
-- The detailed instructions on how to generate the data from scratch can be
-- found on an internal Confluence page.
