--
-- The TPC-DS database can be restored from backup (only scale factor of 1 -
-- about 1GB - is available at the moment; also table statistics were disabled
-- on purpose):
--
--   RESTORE DATABASE tpcds FROM LATEST IN 'gs://cockroach-fixtures-us-east1/workload/tpcds/scalefactor=1/backup_25_3?AUTH=implicit';
--
-- The detailed instructions on how to generate the data from scratch can be
-- found on an internal Confluence page.
