load("@io_bazel_rules_go//go:def.bzl", "go_test")

go_test(
    name = "tenantcapabilitiesccl_test",
    srcs = [
        "capabilities_test.go",
        "commit_trigger_bypass_test.go",
        "main_test.go",
    ],
    data = glob(["testdata/**"]),
    deps = [
        "//pkg/base",
        "//pkg/ccl",
        "//pkg/keys",
        "//pkg/kv",
        "//pkg/kv/kvclient/rangefeed/rangefeedcache",
        "//pkg/kv/kvpb",
        "//pkg/multitenant/tenantcapabilities",
        "//pkg/multitenant/tenantcapabilities/tenantcapabilitieswatcher",
        "//pkg/roachpb",
        "//pkg/security/securityassets",
        "//pkg/security/securitytest",
        "//pkg/server",
        "//pkg/sql",
        "//pkg/testutils",
        "//pkg/testutils/datapathutils",
        "//pkg/testutils/serverutils",
        "//pkg/testutils/sqlutils",
        "//pkg/testutils/testcluster",
        "//pkg/util/hlc",
        "//pkg/util/leaktest",
        "//pkg/util/log",
        "//pkg/util/protoutil",
        "//pkg/util/randutil",
        "//pkg/util/syncutil",
        "@com_github_cockroachdb_datadriven//:datadriven",
        "@com_github_cockroachdb_errors//:errors",
        "@com_github_stretchr_testify//require",
    ],
)
