<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>fileTypes</key>
  <array>
    <string>ddt</string>
  </array>
  <key>name</key>
  <string>Datadriven</string>
  <key>scopeName</key>
  <string>source.datadriven</string>
  <key>patterns</key>
  <array>
    <dict>
      <key>include</key>
      <string>#comment</string>
    </dict>
    <dict>
      <key>include</key>
      <string>#subtest</string>
    </dict>
    <dict>
      <key>include</key>
      <string>#result</string>
    </dict>
    <dict>
      <key>include</key>
      <string>#logictest</string>
    </dict>
  </array>
  <key>repository</key>
  <dict>
    <key>comment</key>
    <dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>begin</key>
          <string>^#</string>
          <key>end</key>
          <string>\n</string>
          <key>name</key>
          <string>comment.line.number-sign.datadriven</string>
        </dict>
      </array>
    </dict>
    <key>subtest</key>
    <dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>begin</key>
          <string>^(subtest).*</string>
          <key>captures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>entity.name.function.datadriven</string>
            </dict>
          </dict>
          <key>end</key>
          <string>\n</string>
          <key>name</key>
          <string>meta.subtest.datadriven</string>
        </dict>
      </array>
    </dict>
    <key>result</key>
    <dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>begin</key>
          <string>^----</string>
          <key>end</key>
          <string>^\s*$\n</string>
          <key>name</key>
          <string>meta.result.datadriven</string>
        </dict>
      </array>
    </dict>
    <key>logictest</key>
    <dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>include</key>
          <string>#statement</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#query</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#logictestmisc</string>
        </dict>
      </array>
      <key>name</key>
      <string>meta.logictest.datadriven</string>
    </dict>
    <key>statement</key>
    <dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>begin</key>
          <string>^(let|statement).*\n</string>
          <key>captures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>entity.name.function.datadriven</string>
            </dict>
          </dict>
          <key>end</key>
          <string>^$\n</string>
          <key>name</key>
          <string>meta.statement.datadriven</string>
          <key>patterns</key>
          <array>
            <dict>
              <key>include</key>
              <string>source.sql</string>
            </dict>
          </array>
        </dict>
      </array>
    </dict>
    <key>query</key>
    <dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>begin</key>
          <string>^(query).*\n</string>
          <key>captures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>entity.name.function.datadriven</string>
            </dict>
          </dict>
          <key>while</key>
          <string>^(?!----).*$</string>
          <key>name</key>
          <string>meta.query.datadriven</string>
          <key>patterns</key>
          <array>
            <dict>
              <key>include</key>
              <string>source.sql</string>
            </dict>
          </array>
        </dict>
      </array>
    </dict>
    <key>logictestmisc</key>
    <dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>begin</key>
          <string>(?x) # Enable free spacing mode
          ^(sleep |
            halt_threshold |
            halt |
            onlyif |
            repeat |
            skip_on_retry |
            skipif |
            skip |
            traceon |
            traceoff |
            user).*</string>
          <key>captures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>entity.name.function.datadriven</string>
            </dict>
          </dict>
          <key>end</key>
          <string>\n</string>
          <key>name</key>
          <string>meta.logictestmisc.datadriven</string>
         </dict>
      </array>
    </dict>
  </dict>
  <key>uuid</key>
  <string>752CE5A6-4179-4742-B091-ED2EE51B7245</string>
</dict>
</plist>
