// Copyright 2020 The Cockroach Authors.
//
// Use of this software is governed by the Business Source License
// included in the file licenses/BSL.txt.
//
// As of the Change Date specified in that file, in accordance with
// the Business Source License, use of this software will be governed
// by the Apache License, Version 2.0, included in the file
// licenses/APL.txt.

import { DatabaseSummaryProps } from "src/views/databases/containers/databaseSummary";
import Long from "long";
import { cockroach } from "src/js/protos";
import ZoneConfigurationLevel = cockroach.server.serverpb.ZoneConfigurationLevel;
import moment from "moment";
import { noop } from "lodash";

const mockedActions = {
  setSort: () => {},
  refreshDatabaseDetails: () => {},
  refreshTableDetails: () => {},
  refreshTableStats: () => {},
};

export const dbLoadingProps: any = {
  ...mockedActions,
  name: "defaultdb",
  tableInfos: [],
  dbResponse: {
    inFlight: true,
  },
  grants: [],
};

export const dbEmptyProps: any = {
  ...mockedActions,
  name: "defaultdb",
  tableInfos: [],
  dbResponse: {
    inFlight: false,
  },
  grants: [],
};

export const dbFullfilledProps: DatabaseSummaryProps = {
  name: "system",
  tableInfos: [
    {
      name: "comments",
      id: 24,
      numColumns: 4,
      numIndices: 1,
      rangeCount: 1,
      createStatement:
        'CREATE TABLE comments (\n\ttype INT8 NOT NULL,\n\tobject_id INT8 NOT NULL,\n\tsub_id INT8 NOT NULL,\n\tcomment STRING NOT NULL,\n\tCONSTRAINT "primary" PRIMARY KEY (type ASC, object_id ASC, sub_id ASC),\n\tFAMILY "primary" (type, object_id, sub_id),\n\tFAMILY fam_4_comment (comment)\n)',
      configureZoneStatement:
        "ALTER RANGE default CONFIGURE ZONE USING\n\trange_min_bytes = 134217728,\n\trange_max_bytes = 536870912,\n\tgc.ttlseconds = 90000,\n\tnum_replicas = 3,\n\tconstraints = '[]',\n\tlease_preferences = '[]'",
      grants: [
        { user: "admin", privileges: ["DELETE"] },
        { user: "admin", privileges: ["GRANT"] },
        { user: "admin", privileges: ["INSERT"] },
        { user: "admin", privileges: ["SELECT"] },
        { user: "admin", privileges: ["UPDATE"] },
        { user: "public", privileges: ["SELECT"] },
        { user: "root", privileges: ["DELETE"] },
        { user: "root", privileges: ["GRANT"] },
        { user: "root", privileges: ["INSERT"] },
        { user: "root", privileges: ["SELECT"] },
        { user: "root", privileges: ["UPDATE"] },
      ],
      numReplicas: 5,
      mvccSize: {
        last_update_nanos: Long.fromString("1568822946512088000"),
        intent_age: Long.fromString("0"),
        gc_bytes_age: Long.fromString("0"),
        live_bytes: Long.fromString("0"),
        live_count: Long.fromString("0"),
        key_bytes: Long.fromString("0"),
        key_count: Long.fromString("0"),
        val_bytes: Long.fromString("0"),
        val_count: Long.fromString("0"),
        intent_bytes: Long.fromString("0"),
        intent_count: Long.fromString("0"),
        sys_bytes: Long.fromString("198"),
        sys_count: Long.fromString("4"),
        contains_estimates: Long.fromString("0"),
      },
      physicalSize: 0,
    },
    {
      name: "descriptor",
      id: 3,
      numColumns: 2,
      numIndices: 1,
      rangeCount: 0,
      createStatement:
        'CREATE TABLE descriptor (\n\tid INT8 NOT NULL,\n\tdescriptor BYTES NULL,\n\tCONSTRAINT "primary" PRIMARY KEY (id ASC),\n\tFAMILY "primary" (id),\n\tFAMILY fam_2_descriptor (descriptor)\n)',
      configureZoneStatement:
        "ALTER RANGE default CONFIGURE ZONE USING\n\trange_min_bytes = 134217728,\n\trange_max_bytes = 536870912,\n\tgc.ttlseconds = 90000,\n\tnum_replicas = 3,\n\tconstraints = '[]',\n\tlease_preferences = '[]'",
      grants: [
        { user: "admin", privileges: ["GRANT"] },
        { user: "admin", privileges: ["SELECT"] },
        { user: "root", privileges: ["GRANT"] },
        { user: "root", privileges: ["SELECT"] },
      ],
      numReplicas: 5,
      mvccSize: {
        last_update_nanos: Long.fromString("0"),
        intent_age: Long.fromString("0"),
        gc_bytes_age: Long.fromString("0"),
        live_bytes: Long.fromString("0"),
        live_count: Long.fromString("0"),
        key_bytes: Long.fromString("0"),
        key_count: Long.fromString("0"),
        val_bytes: Long.fromString("0"),
        val_count: Long.fromString("0"),
        intent_bytes: Long.fromString("0"),
        intent_count: Long.fromString("0"),
        sys_bytes: Long.fromString("0"),
        sys_count: Long.fromString("0"),
        contains_estimates: Long.fromString("0"),
      },
      physicalSize: 0,
    },
    {
      name: "eventlog",
      id: 12,
      numColumns: 6,
      numIndices: 1,
      rangeCount: 1,
      createStatement:
        'CREATE TABLE eventlog (\n\t"timestamp" TIMESTAMP NOT NULL,\n\t"eventType" STRING NOT NULL,\n\t"targetID" INT8 NOT NULL,\n\t"reportingID" INT8 NOT NULL,\n\tinfo STRING NULL,\n\t"uniqueID" BYTES NOT NULL DEFAULT uuid_v4(),\n\tCONSTRAINT "primary" PRIMARY KEY ("timestamp" ASC, "uniqueID" ASC),\n\tFAMILY "primary" ("timestamp", "uniqueID"),\n\tFAMILY "fam_2_eventType" ("eventType"),\n\tFAMILY "fam_3_targetID" ("targetID"),\n\tFAMILY "fam_4_reportingID" ("reportingID"),\n\tFAMILY fam_5_info (info)\n)',
      configureZoneStatement:
        "ALTER RANGE default CONFIGURE ZONE USING\n\trange_min_bytes = 134217728,\n\trange_max_bytes = 536870912,\n\tgc.ttlseconds = 90000,\n\tnum_replicas = 3,\n\tconstraints = '[]',\n\tlease_preferences = '[]'",
      grants: [
        { user: "admin", privileges: ["DELETE"] },
        { user: "admin", privileges: ["GRANT"] },
        { user: "admin", privileges: ["INSERT"] },
        { user: "admin", privileges: ["SELECT"] },
        { user: "admin", privileges: ["UPDATE"] },
        { user: "root", privileges: ["DELETE"] },
        { user: "root", privileges: ["GRANT"] },
        { user: "root", privileges: ["INSERT"] },
        { user: "root", privileges: ["SELECT"] },
        { user: "root", privileges: ["UPDATE"] },
      ],
      numReplicas: 5,
      mvccSize: {
        last_update_nanos: Long.fromString("1590763503402517000"),
        intent_age: Long.fromString("0"),
        gc_bytes_age: Long.fromString("816043540"),
        live_bytes: Long.fromString("13971"),
        live_count: Long.fromString("90"),
        key_bytes: Long.fromString("4531"),
        key_count: Long.fromString("95"),
        val_bytes: Long.fromString("10285"),
        val_count: Long.fromString("100"),
        intent_bytes: Long.fromString("0"),
        intent_count: Long.fromString("0"),
        sys_bytes: Long.fromString("208"),
        sys_count: Long.fromString("4"),
        contains_estimates: Long.fromString("0"),
      },
      physicalSize: 0,
    },
    {
      name: "jobs",
      id: 15,
      numColumns: 5,
      numIndices: 2,
      rangeCount: 1,
      createStatement:
        "CREATE TABLE jobs (\n\tid INT8 NOT NULL DEFAULT unique_rowid(),\n\tstatus STRING NOT NULL,\n\tcreated TIMESTAMP NOT NULL DEFAULT now():::TIMESTAMP,\n\tpayload BYTES NOT NULL,\n\tprogress BYTES NULL,\n\tCONSTRAINT \"primary\" PRIMARY KEY (id ASC),\n\tINDEX jobs_status_created_idx (status ASC, created ASC),\n\tFAMILY fam_0_id_status_created_payload (id, status, created, payload),\n\tFAMILY progress (progress)\n);\nALTER TABLE system.public.jobs CONFIGURE ZONE USING\n\trange_min_bytes = 16777216,\n\trange_max_bytes = 67108864,\n\tgc.ttlseconds = 600,\n\tnum_replicas = 5,\n\tconstraints = '[]',\n\tlease_preferences = '[]'",
      configureZoneStatement:
        "ALTER TABLE system.public.jobs CONFIGURE ZONE USING\n\trange_min_bytes = 16777216,\n\trange_max_bytes = 67108864,\n\tgc.ttlseconds = 600,\n\tnum_replicas = 5,\n\tconstraints = '[]',\n\tlease_preferences = '[]'",
      grants: [
        { user: "admin", privileges: ["DELETE"] },
        { user: "admin", privileges: ["GRANT"] },
        { user: "admin", privileges: ["INSERT"] },
        { user: "admin", privileges: ["SELECT"] },
        { user: "admin", privileges: ["UPDATE"] },
        { user: "root", privileges: ["DELETE"] },
        { user: "root", privileges: ["GRANT"] },
        { user: "root", privileges: ["INSERT"] },
        { user: "root", privileges: ["SELECT"] },
        { user: "root", privileges: ["UPDATE"] },
      ],
      numReplicas: 5,
      mvccSize: {
        last_update_nanos: Long.fromString("1589802430780575000"),
        intent_age: Long.fromString("0"),
        gc_bytes_age: Long.fromString("0"),
        live_bytes: Long.fromString("0"),
        live_count: Long.fromString("0"),
        key_bytes: Long.fromString("0"),
        key_count: Long.fromString("0"),
        val_bytes: Long.fromString("0"),
        val_count: Long.fromString("0"),
        intent_bytes: Long.fromString("0"),
        intent_count: Long.fromString("0"),
        sys_bytes: Long.fromString("208"),
        sys_count: Long.fromString("4"),
        contains_estimates: Long.fromString("0"),
      },
      physicalSize: 0,
    },
    {
      name: "lease",
      id: 11,
      numColumns: 4,
      numIndices: 1,
      rangeCount: 1,
      createStatement:
        'CREATE TABLE lease (\n\t"descID" INT8 NOT NULL,\n\tversion INT8 NOT NULL,\n\t"nodeID" INT8 NOT NULL,\n\texpiration TIMESTAMP NOT NULL,\n\tCONSTRAINT "primary" PRIMARY KEY ("descID" ASC, version ASC, expiration ASC, "nodeID" ASC),\n\tFAMILY "primary" ("descID", version, "nodeID", expiration)\n)',
      configureZoneStatement:
        "ALTER RANGE default CONFIGURE ZONE USING\n\trange_min_bytes = 134217728,\n\trange_max_bytes = 536870912,\n\tgc.ttlseconds = 90000,\n\tnum_replicas = 3,\n\tconstraints = '[]',\n\tlease_preferences = '[]'",
      grants: [
        { user: "admin", privileges: ["DELETE"] },
        { user: "admin", privileges: ["GRANT"] },
        { user: "admin", privileges: ["INSERT"] },
        { user: "admin", privileges: ["SELECT"] },
        { user: "admin", privileges: ["UPDATE"] },
        { user: "root", privileges: ["DELETE"] },
        { user: "root", privileges: ["GRANT"] },
        { user: "root", privileges: ["INSERT"] },
        { user: "root", privileges: ["SELECT"] },
        { user: "root", privileges: ["UPDATE"] },
      ],
      numReplicas: 5,
      mvccSize: {
        last_update_nanos: Long.fromString("1591010093853736000"),
        intent_age: Long.fromString("0"),
        gc_bytes_age: Long.fromString("25775420"),
        live_bytes: Long.fromString("70"),
        live_count: Long.fromString("2"),
        key_bytes: Long.fromString("5183"),
        key_count: Long.fromString("124"),
        val_bytes: Long.fromString("620"),
        val_count: Long.fromString("246"),
        intent_bytes: Long.fromString("0"),
        intent_count: Long.fromString("0"),
        sys_bytes: Long.fromString("208"),
        sys_count: Long.fromString("4"),
        contains_estimates: Long.fromString("0"),
      },
      physicalSize: 0,
    },
    {
      name: "locations",
      id: 21,
      numColumns: 4,
      numIndices: 1,
      rangeCount: 1,
      createStatement:
        'CREATE TABLE locations (\n\t"localityKey" STRING NOT NULL,\n\t"localityValue" STRING NOT NULL,\n\tlatitude DECIMAL(18,15) NOT NULL,\n\tlongitude DECIMAL(18,15) NOT NULL,\n\tCONSTRAINT "primary" PRIMARY KEY ("localityKey" ASC, "localityValue" ASC),\n\tFAMILY "fam_0_localityKey_localityValue_latitude_longitude" ("localityKey", "localityValue", latitude, longitude)\n)',
      configureZoneStatement:
        "ALTER RANGE default CONFIGURE ZONE USING\n\trange_min_bytes = 134217728,\n\trange_max_bytes = 536870912,\n\tgc.ttlseconds = 90000,\n\tnum_replicas = 3,\n\tconstraints = '[]',\n\tlease_preferences = '[]'",
      grants: [
        { user: "admin", privileges: ["DELETE"] },
        { user: "admin", privileges: ["GRANT"] },
        { user: "admin", privileges: ["INSERT"] },
        { user: "admin", privileges: ["SELECT"] },
        { user: "admin", privileges: ["UPDATE"] },
        { user: "root", privileges: ["DELETE"] },
        { user: "root", privileges: ["GRANT"] },
        { user: "root", privileges: ["INSERT"] },
        { user: "root", privileges: ["SELECT"] },
        { user: "root", privileges: ["UPDATE"] },
      ],
      numReplicas: 5,
      mvccSize: {
        last_update_nanos: Long.fromString("1568822946669858000"),
        intent_age: Long.fromString("0"),
        gc_bytes_age: Long.fromString("0"),
        live_bytes: Long.fromString("326"),
        live_count: Long.fromString("5"),
        key_bytes: Long.fromString("187"),
        key_count: Long.fromString("5"),
        val_bytes: Long.fromString("139"),
        val_count: Long.fromString("5"),
        intent_bytes: Long.fromString("0"),
        intent_count: Long.fromString("0"),
        sys_bytes: Long.fromString("198"),
        sys_count: Long.fromString("4"),
        contains_estimates: Long.fromString("0"),
      },
      physicalSize: 0,
    },
    {
      name: "namespace",
      id: 30,
      numColumns: 3,
      numIndices: 1,
      rangeCount: 1,
      createStatement:
        'CREATE TABLE namespace (\n\t"parentID" INT8 NOT NULL,\n\tname STRING NOT NULL,\n\tid INT8 NULL,\n\tCONSTRAINT "primary" PRIMARY KEY ("parentID" ASC, name ASC),\n\tFAMILY "primary" ("parentID", name),\n\tFAMILY fam_3_id (id)\n)',
      configureZoneStatement:
        "ALTER RANGE default CONFIGURE ZONE USING\n\trange_min_bytes = 134217728,\n\trange_max_bytes = 536870912,\n\tgc.ttlseconds = 90000,\n\tnum_replicas = 3,\n\tconstraints = '[]',\n\tlease_preferences = '[]'",
      grants: [
        { user: "admin", privileges: ["GRANT"] },
        { user: "admin", privileges: ["SELECT"] },
        { user: "root", privileges: ["GRANT"] },
        { user: "root", privileges: ["SELECT"] },
      ],
      numReplicas: 5,
      mvccSize: {
        last_update_nanos: Long.fromString("1587980617075991000"),
        intent_age: Long.fromString("0"),
        gc_bytes_age: Long.fromString("0"),
        live_bytes: Long.fromString("1043"),
        live_count: Long.fromString("27"),
        key_bytes: Long.fromString("881"),
        key_count: Long.fromString("27"),
        val_bytes: Long.fromString("162"),
        val_count: Long.fromString("27"),
        intent_bytes: Long.fromString("0"),
        intent_count: Long.fromString("0"),
        sys_bytes: Long.fromString("250"),
        sys_count: Long.fromString("4"),
        contains_estimates: Long.fromString("0"),
      },
      physicalSize: 0,
    },
  ].map((ti) => ({ ...ti, detailsAndStatsLoaded: () => true })),
  dbResponse: {
    data: {
      data: {
        grants: [
          { user: "admin", privileges: ["GRANT"] },
          { user: "admin", privileges: ["SELECT"] },
          { user: "root", privileges: ["GRANT"] },
          { user: "root", privileges: ["SELECT"] },
        ],
        table_names: [
          "comments",
          "descriptor",
          "eventlog",
          "jobs",
          "lease",
          "locations",
          "namespace",
        ],
        descriptor_id: Long.fromString("1"),
        zone_config: {
          range_min_bytes: Long.fromString("16777216"),
          range_max_bytes: Long.fromString("67108864"),
          gc: { ttl_seconds: 90000 },
          num_replicas: 5,
          inherited_constraints: false,
          inherited_lease_preferences: false,
        },
        zone_config_level: ZoneConfigurationLevel.DATABASE,
        toJSON: () => ({}),
      },
      inFlight: false,
      valid: true,
      requestedAt: moment("2020-06-01T11:15:23.907Z"),
      setAt: moment("2020-06-01T11:15:24.323Z"),
      lastError: null,
    },
  },
  grants: [
    { user: "admin", privileges: ["GRANT"] },
    { user: "admin", privileges: ["SELECT"] },
    { user: "root", privileges: ["GRANT"] },
    { user: "root", privileges: ["SELECT"] },
  ].map((ti) => ({ ...ti, toJSON: () => ti })),
  setSort: noop,
  sortSetting: {
    ascending: true,
    sortKey: 1,
  },
  refreshDatabaseDetails: noop as DatabaseSummaryProps["refreshDatabaseDetails"],
  refreshTableDetails: noop as DatabaseSummaryProps["refreshTableDetails"],
  refreshTableStats: noop as DatabaseSummaryProps["refreshTableStats"],
};
