{
 "title": "CRDB Console: Replication by Test Run and Name",
 "tags": [ "crdb-console-run-name" ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   {
    "name": "test_run_id",
    "label": "Test Run ID",
    "query": {
     "query": "label_values(sys_uptime{job=\"cockroachdb\"},test_run_id)"
    }
   },
   {
    "name": "test_name",
    "label": "Test",
    "query": {
     "query": "label_values(sys_uptime{job=\"cockroachdb\",test_run_id=~\"$test_run_id\"},test_name)"
    }
   },
   {
    "name": "node",
    "label": "Node",
    "query": {
     "query": "label_values(sys_uptime{job=\"cockroachdb\",test_run_id=~\"$test_run_id\", test_name=~\"$test_name\"},instance)"
    }
   },
   { "name": "rate_interval", "label": "Rate Interval", "query": "30s,1m,5m,10m,30m,1h,6h,12h,1d" }
  ]
 },
 "panels": [
  {
   "title": "Ranges",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "ranges" }
   ],
   "targets": [
    {
     "expr": "sum(sum(ranges{test_run_id=~\"$test_run_id\", test_name=~\"$test_name\",job=\"cockroachdb\",instance=~\"$node\"})) by (instance)",
     "legendFormat": "Ranges"
    },
    {
     "expr": "sum(sum(replicas_leaders{test_run_id=~\"$test_run_id\", test_name=~\"$test_name\",job=\"cockroachdb\",instance=~\"$node\"}) by (instance))",
     "legendFormat": "Leaders"
    },
    {
     "expr": "sum(sum(replicas_leaseholders{test_run_id=~\"$test_run_id\", test_name=~\"$test_name\",job=\"cockroachdb\",instance=~\"$node\"}) by (instance))",
     "legendFormat": "Lease Holders"
    },
    {
     "expr": "sum(sum(replicas_leaders_not_leaseholders{test_run_id=~\"$test_run_id\", test_name=~\"$test_name\",job=\"cockroachdb\",instance=~\"$node\"}) by (instance))",
     "legendFormat": "Leaders w/o Lease"
    },
    {
     "expr": "sum(sum(ranges_unavailable{test_run_id=~\"$test_run_id\", test_name=~\"$test_name\",job=\"cockroachdb\",instance=~\"$node\"}) by (instance))",
     "legendFormat": "Unavailable"
    },
    {
     "expr": "sum(sum(ranges_underreplicated{test_run_id=~\"$test_run_id\", test_name=~\"$test_name\",job=\"cockroachdb\",instance=~\"$node\"}) by (instance))",
     "legendFormat": "Under-replicated"
    },
    {
     "expr": "sum(sum(ranges_overreplicated{test_run_id=~\"$test_run_id\", test_name=~\"$test_name\",job=\"cockroachdb\",instance=~\"$node\"}) by (instance))",
     "legendFormat": "Over-replicated"
    }
   ]
  },
  {
   "title": "Replicas per Store",
   "type": "graph",
   "description": "The number of replicas on each store.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short", "label": "replicas" }
   ],
   "targets": [
    {
     "expr": "sum(replicas{test_run_id=~\"$test_run_id\", test_name=~\"$test_name\",job=\"cockroachdb\",instance=~\"$node\"}) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Leaseholders per Store",
   "type": "graph",
   "description": "The number of leaseholder replicas on each store. A leaseholder replica is the one that receives and coordinates all read and write requests for its range.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short", "label": "leaseholders" }
   ],
   "targets": [
    {
     "expr": "sum(replicas_leaseholders{test_run_id=~\"$test_run_id\", test_name=~\"$test_name\",job=\"cockroachdb\",instance=~\"$node\"}) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Average Queries per Store",
   "type": "graph",
   "description": "Exponentially weighted moving average of the number of KV batch requests processed by leaseholder replicas on each store per second. Tracks roughly the last 30 minutes of requests. Used for load-based rebalancing decisions.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short", "label": "queries" }
   ],
   "targets": [
    {
     "expr": "rebalancing_queriespersecond{job=\"cockroachdb\",test_run_id=~\"$test_run_id\", test_name=~\"$test_name\",instance=~\"$node\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Logical Bytes per Store",
   "type": "graph",
   "description": "Number of logical bytes stored in [key-value pairs](https://www.cockroachlabs.com/docs/v21.1/architecture/distribution-layer.html#table-data) on each node.\n\nThis includes historical and deleted data.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "bytes", "label": "logical store size" }
   ],
   "targets": [
    {
     "expr": "totalbytes{job=\"cockroachdb\",test_run_id=~\"$test_run_id\", test_name=~\"$test_name\",instance=~\"$node\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Replica Quiescence",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "short", "label": "replicas" }
   ],
   "targets": [
    {
     "expr": "sum(sum(replicas{test_run_id=~\"$test_run_id\", test_name=~\"$test_name\",job=\"cockroachdb\",instance=~\"$node\"}) by (instance))  ",
     "legendFormat": "Replicas"
    },
    {
     "expr": "sum(sum(replicas_quiescent{test_run_id=~\"$test_run_id\", test_name=~\"$test_name\",job=\"cockroachdb\",instance=~\"$node\"}) by (instance))",
     "legendFormat": "Quiescent"
    }
   ]
  },
  {
   "title": "Range Operations",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "short", "label": "ranges" }
   ],
   "targets": [
    {
     "expr": "sum(sum(rate(range_splits{test_run_id=~\"$test_run_id\", test_name=~\"$test_name\",job=\"cockroachdb\",instance=~\"$node\"}[$rate_interval])) by (instance))",
     "legendFormat": "Splits"
    },
    {
     "expr": "sum(sum(rate(range_merges{test_run_id=~\"$test_run_id\", test_name=~\"$test_name\",job=\"cockroachdb\",instance=~\"$node\"}[$rate_interval])) by (instance))",
     "legendFormat": "Merges"
    },
    {
     "expr": "sum(sum(rate(range_adds{test_run_id=~\"$test_run_id\", test_name=~\"$test_name\",job=\"cockroachdb\",instance=~\"$node\"}[$rate_interval])) by (instance))",
     "legendFormat": "Adds"
    },
    {
     "expr": "sum(sum(rate(range_removes{test_run_id=~\"$test_run_id\", test_name=~\"$test_name\",job=\"cockroachdb\",instance=~\"$node\"}[$rate_interval])) by (instance))",
     "legendFormat": "Removes"
    },
    {
     "expr": "sum(sum(rate(leases_transfers_success{test_run_id=~\"$test_run_id\", test_name=~\"$test_name\",job=\"cockroachdb\",instance=~\"$node\"}[$rate_interval])) by (instance))",
     "legendFormat": "Lease Transfers"
    },
    {
     "expr": "sum(sum(rate(rebalancing_lease_transfers{test_run_id=~\"$test_run_id\", test_name=~\"$test_name\",job=\"cockroachdb\",instance=~\"$node\"}[$rate_interval])) by (instance))",
     "legendFormat": "Load-based Lease Transfers"
    },
    {
     "expr": "sum(sum(rate(rebalancing_range_rebalances{test_run_id=~\"$test_run_id\", test_name=~\"$test_name\",job=\"cockroachdb\",instance=~\"$node\"}[$rate_interval])) by (instance))",
     "legendFormat": "Load-based Range Rebalances"
    }
   ]
  },
  {
   "title": "Snapshots",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "short", "label": "snapshots" }
   ],
   "targets": [
    {
     "expr": "sum(rate(range_snapshots_generated{test_run_id=~\"$test_run_id\", test_name=~\"$test_name\",job=\"cockroachdb\",instance=~\"$node\"}[$rate_interval]))",
     "legendFormat": "Generated"
    },
    {
     "expr": "sum(rate(range_snapshots_applied_voter{test_run_id=~\"$test_run_id\", test_name=~\"$test_name\",job=\"cockroachdb\",instance=~\"$node\"}[$rate_interval]))",
     "legendFormat": "Applied (Voters)"
    },
    {
     "expr": "sum(rate(range_snapshots_applied_initial{test_run_id=~\"$test_run_id\", test_name=~\"$test_name\",job=\"cockroachdb\",instance=~\"$node\"}[$rate_interval]))",
     "legendFormat": "Applied (Initial Upreplication)"
    },
    {
     "expr": "sum(rate(range_snapshots_applied_initial{test_run_id=~\"$test_run_id\", test_name=~\"$test_name\",job=\"cockroachdb\",instance=~\"$node\"}[$rate_interval]))",
     "legendFormat": "Applied (Non-Voters)"
    },
    {
     "expr": "sum(rate(replicas_reserved{test_run_id=~\"$test_run_id\", test_name=~\"$test_name\",job=\"cockroachdb\",instance=~\"$node\"}[$__rate_interval]))",
     "legendFormat": "Reserved Replicas"
    }
   ]
  },
  {
   "title": "Msg App",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 64 },
   "yaxes": [
    { "format": "short", "label": "ranges" }
   ],
   "targets": [
    {
     "expr": "rate(raft_rcvd_app{test_run_id=~\"$test_run_id\", test_name=~\"$test_name\",job=\"cockroachdb\",instance=~\"$node\"}[$rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Msg Queued Bytes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 72 },
   "yaxes": [
    { "format": "short", "label": "ranges" }
   ],
   "targets": [
    {
     "expr": "rate(raft_rcvd_queued_bytes{test_run_id=~\"$test_run_id\", test_name=~\"$test_name\",job=\"cockroachdb\",instance=~\"$node\"}[$rate_interval])",
     "legendFormat": "__auto"
    },
    { "legendFormat": "__auto" }
   ]
  }
 ]
}