# Yaml for destroying the drt-scale cluster.
environment:
  ROACHPROD_GCE_DEFAULT_SERVICE_ACCOUNT: 622274581499-compute@developer.gserviceaccount.com
  ROACHPROD_DNS: drt.crdb.io
  ROACHPROD_GCE_DNS_DOMAIN: drt.crdb.io
  ROACHPROD_GCE_DNS_ZONE: drt
  ROACHPROD_GCE_DEFAULT_PROJECT: cockroach-drt
  CLUSTER: drt-scale
  WORKLOAD_CLUSTER: workload-scale

targets:
  - target_name: $CLUSTER
    steps:
      - command: destroy
        args:
          - $CLUSTER
  - target_name: $WORKLOAD_CLUSTER
    steps:
      - command: destroy
        args:
          - $WORKLOAD_CLUSTER
