{
 "title": "Unified Overload Control",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  { "title": "Elastic CPU Limiter", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Elastic CPU utilization limit",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "admission_elastic_cpu_utilization_limit",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Go scheduler latency (p99)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(go_scheduler_latency_bucket[$__rate_interval])))"
    }
   ]
  },
  {
   "title": "Elastic CPU utilization (as seen by elastic work; acquired - returned CPU time)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    { "expression": "($A-$B)/8000000000", "type": "math" },
    {
     "expr": "avg(admission_elastic_cpu_granter_target_utilization)",
     "legendFormat": "Average Elastic CPU Limit"
    }
   ]
  },
  {
   "title": "Service latency (p99)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(sql_service_latency_bucket[$__rate_interval])))"
    }
   ]
  },
  {
   "title": "Non-elastic CPU utilization (smoothed; 2m)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    { "expression": "$C-(($A-$B))", "type": "math" }
   ]
  },
  {
   "title": "Aggregate CPU utilization (smoothed; 2m)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg_over_time(sys_cpu_combined_percent_normalized[2m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CRDB",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "title": "Service latency (p99)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum by(le) (rate(sql_service_latency_bucket[$__rate_interval])))"
      }
     ]
    },
    {
     "title": "Log commit latency (p99)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum by(le) (rate(raft_process_logcommit_latency_bucket{node=\"1\"}[$__rate_interval])))"
      },
      {
       "expr": "histogram_quantile(0.99, sum by(le) (rate(raft_process_logcommit_latency_bucket{node=\"2\"}[$__rate_interval])))"
      },
      {
       "expr": "histogram_quantile(0.99, sum by(le) (rate(raft_process_logcommit_latency_bucket{node=\"3\"}[$__rate_interval])))"
      }
     ]
    },
    {
     "title": "Backups currently running",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "targets": [
      {
       "expr": "sum(jobs_backup_currently_running)"
      }
     ]
    },
    {
     "title": "SQL statements",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
     "targets": [
      {
       "expr": "rate(sql_insert_count[$__rate_interval])"
      },
      {
       "expr": "rate(sql_delete_count[$__rate_interval])"
      },
      {
       "expr": "rate(sql_select_count[$__rate_interval])"
      },
      {
       "expr": "rate(sql_update_count[$__rate_interval])"
      }
     ]
    },
    {
     "title": "Backups failed",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
     "targets": [
      {
       "expr": "sum(rate(schedules_BACKUP_failed[$__rate_interval]))"
      }
     ]
    },
    {
     "title": "# of export requests received",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
     "targets": [
      {
       "expr": "avg by(node) (rate(rpc_method_export_recv[$__rate_interval]))"
      }
     ]
    },
    {
     "title": "CPU utilization",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sys_cpu_combined_percent_normalized"
      }
     ]
    },
    {
     "title": "# of export requests sent",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
     "targets": [
      {
       "expr": "avg by(node) (rate(distsender_rpc_export_sent[$__rate_interval]))"
      }
     ]
    },
    {
     "title": "Weighted IO time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum by(node) (rate(node_disk_io_time_weighted_seconds_total{node!=\"4\"}[1m]))"
      }
     ]
    },
    {
     "title": "Liveness blips",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
     "targets": [
      {
       "expr": "rate(liveness_heartbeatfailures[$__rate_interval])"
      }
     ]
    },
    {
     "title": "Read bandwidth",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "rate(sys_host_disk_read_bytes[$__rate_interval])"
      }
     ]
    },
    {
     "title": "Read IOPS",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "expr": "rate(sys_host_disk_read_count[$__rate_interval])"
      }
     ]
    },
    {
     "title": "Write bandwidth",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "rate(sys_host_disk_write_bytes[$__rate_interval])"
      }
     ]
    },
    {
     "title": "Write IOPS",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "expr": "sum by(node) (rate(node_disk_writes_completed_total{node!=\"4\"}[1m]))"
      }
     ]
    },
    {
     "title": "Read and write bandwidth",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 58 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "sum by(node) (rate(sys_host_disk_read_bytes[$__rate_interval])) + sum by(node) (rate(sys_host_disk_write_bytes[$__rate_interval]))"
      }
     ]
    },
    {
     "title": "Read and write IOPS",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 58 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "expr": "sum by(node) (rate(node_disk_reads_completed_total{node!=\"4\"}[$__rate_interval])) + sum by(node) (rate(node_disk_writes_completed_total{node!=\"4\"}[$__rate_interval]))"
      }
     ]
    },
    {
     "title": "IOPS in progress",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 66 },
     "targets": [
      {
       "expr": "sum by(node) (node_disk_io_now{node!=\"4\"})"
      }
     ]
    },
    {
     "title": "Batch requests received",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 66 },
     "targets": [
      {
       "expr": "rate(rpc_batches_recv[$__rate_interval])"
      }
     ]
    }
   ]
  },
  {
   "title": "Admission Control",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "panels": [
    {
     "title": "Granter total slots",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "slots" } },
     "targets": [
      {
       "expr": "admission_granter_total_slots_kv",
       "legendFormat": "KV {node=\"{{node}}\"}"
      }
     ]
    },
    {
     "title": "Granter used slots",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "slots/s" } },
     "targets": [
      {
       "expr": "admission_granter_used_slots_kv",
       "legendFormat": "KV {node=\"{{node}}\"}"
      },
      {
       "expr": "admission_granter_used_slots_sql_root_start",
       "legendFormat": "SQL root start {node=\"{{node}}\"}"
      },
      {
       "expr": "admission_granter_used_slots_sql_leaf_start",
       "legendFormat": "SQL leaf start {node=\"{{node}}\"}"
      }
     ]
    },
    {
     "title": "KV admission requests",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum by(node) (rate(admission_requested_kv[$__rate_interval]))"
      },
      {
       "expr": "sum by() (rate(admission_requested_kv[$__rate_interval]))"
      }
     ]
    },
    {
     "title": "KV requests admitted",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum by(node) (rate(admission_admitted_kv[$__rate_interval]))"
      },
      {
       "expr": "sum by() (rate(admission_admitted_kv[$__rate_interval]))"
      }
     ]
    },
    {
     "title": "KV stores requests",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "rate(admission_requested_kv_stores[$__rate_interval])",
       "legendFormat": "{node=\"{{node}}\"}"
      },
      {
       "expr": "sum by() (rate(admission_requested_kv_stores[$__rate_interval]))"
      }
     ]
    },
    {
     "title": "KV stores requests admitted",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum by(node) (rate(admission_admitted_kv_stores[$__rate_interval]))"
      },
      {
       "expr": "sum by() (rate(admission_admitted_kv_stores[$__rate_interval]))"
      }
     ]
    },
    {
     "title": "IO token exhaustion duration",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 45 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "rate(admission_granter_io_tokens_exhausted_duration_kv[$__rate_interval])"
      }
     ]
    },
    {
     "title": "KV wait queue length",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 45 },
     "targets": [
      {
       "expr": "admission_wait_queue_length_kv_stores",
       "legendFormat": "KV stores {node=\"{{node}}\"}"
      },
      {
       "expr": "admission_wait_queue_length_kv",
       "legendFormat": "KV {node=\"{{node}}\"}"
      }
     ]
    },
    {
     "title": "Aggregate wait time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 53 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "rate(admission_wait_sum_kv_stores[$__rate_interval])",
       "legendFormat": "KV stores {node=\"{{node}}\"}"
      },
      {
       "expr": "rate(admission_wait_sum_kv[$__rate_interval])",
       "legendFormat": "KV {node=\"{{node}}\"}"
      },
      {
       "expr": "rate(admission_wait_sum_sql_kv_response[$__rate_interval])",
       "legendFormat": "SQL-KV {node=\"{{node}}\"}"
      },
      {
       "expr": "rate(admission_wait_sum_sql_sql_response[$__rate_interval])",
       "legendFormat": "SQL-SQL {node=\"{{node}}\"}"
      },
      {
       "expr": "rate(admission_wait_sum_sql_leaf_start[$__rate_interval])",
       "legendFormat": "SQL leaf start {node=\"{{node}}\"}"
      },
      {
       "expr": "rate(admission_wait_sum_sql_root_start[$__rate_interval])",
       "legendFormat": "SQL root start {node=\"{{node}}\"}"
      }
     ]
    },
    {
     "title": "Queue wait durations (p99)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 53 },
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(admission_wait_durations_kv_bucket[$__rate_interval])) by (le))",
       "legendFormat": "KV"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(admission_wait_durations_kv_stores_bucket[$__rate_interval])) by (le))",
       "legendFormat": "KV Stores"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(admission_wait_durations_sql_kv_response_bucket[$__rate_interval])) by (le))",
       "legendFormat": "SQL-KV"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(admission_wait_durations_sql_sql_response_bucket[$__rate_interval])) by (le))",
       "legendFormat": "SQL-SQL"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(admission_wait_durations_sql_leaf_start_bucket[$__rate_interval])) by (le)) ",
       "legendFormat": "SQL leaf start"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(admission_wait_durations_sql_root_start_bucket[$__rate_interval])) by (le)) ",
       "legendFormat": "SQL root start"
      }
     ]
    },
    {
     "title": "IO Admission Threshold Fraction",
     "type": "timeseries",
     "description": "at 1, IO admission control kicks in",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 61 },
     "targets": [
      { "expr": "storage_l0_sublevels/20" },
      { "expr": "storage_l0_num_files/1000", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "L0 flushed + ingested bytes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 61 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "rate(storage_l0_bytes_ingested[$__rate_interval])",
       "legendFormat": "ingested {node=\"{{node}}\"}"
      },
      {
       "expr": "rate(storage_l0_bytes_flushed[$__rate_interval])",
       "legendFormat": "flushed {node=\"{{node}}\"}"
      }
     ]
    }
   ]
  }
 ]
}