{
 "title": "cgroup i/o",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Read I/O",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "cgroup_io_read_bytes_total{device=\"259:0\"}",
     "legendFormat": "n{{node}}"
    }
   ]
  },
  {
   "title": "Write I/O",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "cgroup_io_write_bytes_total{device=\"259:0\"}",
     "legendFormat": "n{{node}}"
    }
   ]
  },
  {
   "title": "Read I/O Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "rate(cgroup_io_read_bytes_total{device=\"259:0\"}[$__rate_interval])",
     "legendFormat": "n{{node}}"
    }
   ]
  },
  {
   "title": "Write I/O Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "rate(cgroup_io_write_bytes_total{device=\"259:0\"}[$__rate_interval])",
     "legendFormat": "n{{node}}"
    }
   ]
  }
 ]
}