// Copyright 2026 The Cockroach Authors.
//
// Use of this software is governed by the CockroachDB Software License
// included in the /LICENSE file.

package sql

// sessionVarDescriptions contains the descriptions for session variables.
// These descriptions are sourced from the proto files and documentation.
// They will be merged into the sessionVar structs in vars.go.
var sessionVarDescriptions = map[string]string{
	"allow_ordinal_column_references":                                 "Controls whether the deprecated ordinal column reference syntax (e.g., SELECT @1 FROM t) is allowed.",
	"allow_role_memberships_to_change_during_transaction":             "Controls whether operations consulting role membership cache retain their lease throughout the transaction.",
	"allow_unsafe_internals":                                          "Controls access to unsafe internals in the system database and the crdb_internal schema. When off, queries to those namespaces will fail. Usage of unsafe internals is audited via the SENSITIVE_ACCESS logging channel.",
	"alter_primary_region_super_region_override":                      "Controls whether the user can modify a primary region that is part of a super region.",
	"always_distribute_full_scans":                                    "Controls whether full table scans always force the plan to be distributed, regardless of the estimated row count.",
	"application_name":                                                "Sets the name of the application running the current session. Used for logging and per-application statistics.",
	"authentication_method":                                           "The authentication method used for the session.",
	"autocommit_before_ddl":                                           "Causes any DDL statement received during an explicit transaction to auto-commit before executing the schema change. This is useful because CockroachDB does not fully support multiple schema changes in a single transaction.",
	"avoid_buffering":                                                 "Indicates that the returned data should not be buffered by conn executor. This is currently used by replication primitives to ensure the data is flushed to the consumer immediately.",
	"avoid_full_table_scans_in_mutations":                             "Controls whether mutation queries that plan full table scans should be avoided.",
	"backslash_quote":                                                 "Controls whether backslash can be used as a quote escape character (compatibility setting).",
	"buffered_writes_implicit_txns_enabled":                           "Controls whether buffered writes are enabled for implicit transactions.",
	"buffered_writes_use_locking_on_non_unique_indexes":               "Controls whether buffered writes use locking on non-unique indexes.",
	"bypass_pcr_reader_catalog_aost":                                  "Disables the AOST used by all user queries on the PCR reader catalog.",
	"bytea_output":                                                    "Controls how to encode byte arrays when converting to string.",
	"canary_stats_mode":                                               "When sql.stats.canary_fraction > 0, controls which table statistics are used for query planning: 'on' always uses the newest stats as soon as they are available, 'off' always uses the second newest (stable) stats, and 'auto' selects probabilistically based on the canary fraction. Has no effect when sql.stats.canary_fraction is 0.",
	"catalog_digest_staleness_check_enabled":                          "Controls whether to use catalog digest information for fast memo staleness checks.",
	"check_function_bodies":                                           "Controls whether functions are validated during function creation.",
	"client_encoding":                                                 "Controls the client-side character encoding. Only UTF8 is supported.",
	"client_min_messages":                                             "Controls which message levels are sent to the client.",
	"close_cursors_at_commit":                                         "Determines whether cursors remain open after their parent transaction closes.",
	"copy_fast_path_enabled":                                          "Controls whether the optimized copy mode is enabled.",
	"copy_from_atomic_enabled":                                        "When enabled, implicit transaction COPY FROM operations are committed atomically, matching PostgreSQL behavior. When disabled, rows are segmented into batches unless issued within an explicit transaction.",
	"copy_from_retries_enabled":                                       "Controls whether retries should be internally attempted for retriable errors in COPY FROM operations.",
	"copy_num_retries_per_batch":                                      "Determines the number of times a single batch of rows can be retried for non-atomic COPY operations.",
	"copy_transaction_quality_of_service":                             "Sets the admission control priority of the transactions used to evaluate COPY commands.",
	"copy_write_pipelining_enabled":                                   "Controls whether write pipelining is enabled for implicit transactions used by COPY.",
	"cost_scans_with_default_col_size":                                "Controls whether the optimizer should cost scans and joins using a default number of bytes per column instead of column sizes from statistics.",
	"crdb_version":                                                    "The version of CockroachDB.",
	"create_table_with_schema_locked":                                 "Controls whether CREATE TABLE acquires a schema lock on the parent schema.",
	"database":                                                        "Sets the current database for resolving names in queries.",
	"datestyle":                                                       "Controls the display format for date and time values as well as the rules for interpreting ambiguous date inputs.",
	"deadlock_timeout":                                                "Sets the amount of time to wait on a lock before checking for deadlock. If set to 0, there is no timeout.",
	"declare_cursor_statement_timeout_enabled":                        "Controls whether statement timeouts apply during DECLARE CURSOR operations.",
	"default_int_size":                                                "Specifies the size in bits or bytes (preferred) of how the INT type should be parsed.",
	"default_table_access_method":                                     "Sets the default table access method (compatibility setting).",
	"default_tablespace":                                              "Supported only for pg compatibility - CockroachDB has no notion of tablespaces.",
	"default_text_search_config":                                      "Sets the default text search configuration used for builtins like `to_tsvector` and `to_tsquery`.",
	"default_transaction_isolation":                                   "Sets the transaction isolation level of new transactions.",
	"default_transaction_priority":                                    "Sets the default priority of newly created transactions.",
	"default_transaction_quality_of_service":                          "Sets the default admission control priority of newly created transactions.",
	"default_transaction_read_only":                                   "Sets whether new transactions are read-only by default.",
	"default_transaction_use_follower_reads":                          "When enabled, all read-only transactions use `AS OF SYSTEM TIME follower_read_timestamp()` to allow follower reads. When disabled, read-only transactions only use follower reads if an explicit `AS OF SYSTEM TIME` clause is specified.",
	"default_with_oids":                                               "Controls whether new tables are created with OIDs by default (compatibility setting).",
	"descriptor_validation":                                           "Controls whether schema object descriptors are validated at read and write time, read time only, or never.",
	"direct_columnar_scans_enabled":                                   "Controls whether the COL_BATCH_RESPONSE scan format should be used for ScanRequests and ReverseScanRequests whenever possible.",
	"disable_changefeed_replication":                                  "Disables changefeed events from being emitted for data changes made in a session, applying to new transactions only.",
	"disable_hoist_projection_in_join_limitation":                     "Disables the restrictions placed on projection hoisting during query planning in the optimizer.",
	"disable_optimizer_rules":                                         "Allows disabling specific optimizer transformation rules by name, specified as a comma-separated list.",
	"disable_partially_distributed_plans":                             "Controls whether partially distributed plans are disabled.",
	"disable_plan_gists":                                              "Controls whether plan gists are disabled.",
	"disable_vec_union_eager_cancellation":                            "Disables the eager cancellation that is performed by the vectorized engine when transitioning into the draining state in some cases.",
	"disable_wait_for_jobs_notice":                                    "Controls whether the notice about waiting for jobs to complete is suppressed.",
	"disallow_full_table_scans":                                       "When enabled, queries on tables with a row count greater than large_full_scan_rows will not use full table or index scans. If no other query plan is possible, queries will return an error. This setting does not apply to internal queries.",
	"distribute_group_by_row_count_threshold":                         "Sets the minimum number of rows estimated to be processed by the GroupBy operator to distribute the plan.",
	"distribute_join_row_count_threshold":                             "Sets the minimum number of rows estimated to be processed from both inputs by the hash or merge join to distribute the plan.",
	"distribute_scan_row_count_threshold":                             "Sets the minimum number of rows estimated to be read by the Scan operator to distribute the plan.",
	"distribute_sort_row_count_threshold":                             "Sets the minimum number of rows estimated to be processed by the Sort operator to distribute the plan.",
	"distsql":                                                         "Controls the query distribution mode for the session. By default, CockroachDB determines which queries benefit from distributed execution. Distribution thresholds for specific operations are controlled by `distribute_group_by_row_count_threshold`, `distribute_scan_row_count_threshold`, and `distribute_sort_row_count_threshold`.",
	"distsql_plan_gateway_bias":                                       "Controls how many more partition spans the gateway node can be assigned compared to other nodes when distributing SQL execution.",
	"distsql_prevent_partitioning_soft_limited_scans":                 "Controls whether the DistSQL planner prevents partitioning of soft-limited scans across multiple nodes.",
	"distsql_use_reduced_leaf_write_sets":                             "Controls whether distributed SQL uses reduced write sets for leaf transactions.",
	"distsql_workmem":                                                 "Determines how much RAM (in bytes) a single operation of a single query can use before it has to spill to disk.",
	"enable_auto_rehoming":                                            "Controls whether auto-rehoming is enabled for REGIONAL BY ROW tables.",
	"enable_create_stats_using_extremes":                              "Controls whether CREATE STATISTICS using the EXTREMES method is enabled.",
	"enable_create_stats_using_extremes_bool_enum":                    "Controls whether CREATE STATISTICS using the EXTREMES method is enabled for boolean and enum types.",
	"enable_durable_locking_for_serializable":                         "Controls whether FOR UPDATE and FOR SHARE locks are replicated via Raft under serializable isolation, allowing locks to be preserved across lease transfers. Enabling this adds latency to locking statements. This matches the default READ COMMITTED behavior.",
	"enable_experimental_alter_column_type_general":                   "Controls whether ALTER TABLE ... ALTER COLUMN ... TYPE can be used for general conversions requiring online schema changes.",
	"enable_implicit_fk_locking_for_serializable":                     "Controls whether shared locks are used to perform foreign key checks under serializable isolation. Requires enable_shared_locking_for_serializable to also be enabled.",
	"enable_implicit_select_for_update":                               "Controls whether `FOR UPDATE` locking may be used during the row-fetch phase of mutation statements.",
	"enable_implicit_transaction_for_batch_statements":                "Controls whether a batch of statements sent in one query is executed as an implicit transaction.",
	"enable_insert_fast_path":                                         "Controls whether the fast path for INSERT operations with VALUES input may be used.",
	"enable_multiple_modifications_of_table":                          "Allows statements with multiple modification subqueries for the same table, risking data corruption if rows are modified multiple times.",
	"enable_multiregion_placement_policy":                             "Controls whether placement can be used in multi-region contexts.",
	"enable_shared_locking_for_serializable":                          "Controls whether SELECT FOR SHARE statements acquire shared locks under serializable isolation. When off, FOR SHARE statements are still permitted but silently do not lock.",
	"enable_super_regions":                                            "When enabled, allows defining super regions: sets of database regions on a multi-region cluster such that schema objects will have all replicas stored only in regions that are members of the super region.",
	"enable_zigzag_join":                                              "Controls whether the optimizer should try to plan a zigzag join.",
	"enforce_home_region":                                             "When enabled, queries return an error if they cannot run entirely in the gateway's home region, such as when reading from multiple home regions in a REGIONAL BY ROW table. Only tables with ZONE survivability can be scanned without error when this is enabled.",
	"enforce_home_region_follower_reads_enabled":                      "Allows using follower reads to dynamically detect and report a query's home region when enforce_home_region is enabled.",
	"escape_string_warning":                                           "Controls whether warnings are issued for escape string syntax.",
	"expect_and_ignore_not_visible_columns_in_copy":                   "Changes behavior for COPY FROM to expect and ignore not visible column fields.",
	"experimental_distsql_planning":                                   "Controls whether experimental distributed SQL planning is enabled.",
	"experimental_enable_implicit_column_partitioning":                "Controls whether implicit column partitioning can be created.",
	"experimental_enable_temp_tables":                                 "Controls whether temporary tables can be created.",
	"experimental_enable_unique_without_index_constraints":            "Controls whether creating unique constraints without an index is allowed.",
	"experimental_hash_group_join_enabled":                            "Controls whether the physical planner will convert a hash join followed by hash aggregator into a single hash group-join.",
	"extra_float_digits":                                              "Sets the number of digits beyond the standard number to use for float conversions.",
	"force_savepoint_restart":                                         "Overrides the default SAVEPOINT behavior for compatibility with certain ORMs.",
	"foreign_key_cascades_limit":                                      "Sets the maximum number of cascading operations for foreign key actions.",
	"idle_in_transaction_session_timeout":                             "Sets the maximum allowed duration for an idle transaction session. The session is terminated if it exceeds this limit.",
	"index_join_streamer_batch_size":                                  "Sets the size limit on input rows to the ColIndexJoin operator when using the Streamer API for a single lookup KV batch.",
	"index_recommendations_enabled":                                   "Controls whether index recommendations are enabled.",
	"initial_retry_backoff_for_read_committed":                        "Sets the initial backoff duration for automatic retries of statements in explicit READ COMMITTED transactions that encounter retry errors.",
	"inject_retry_errors_enabled":                                     "Causes statements (except SET) inside explicit transactions to return a transaction retry error for testing application retry logic. If the client retries using the cockroach_restart savepoint, the transaction proceeds normally after the 3rd retry error.",
	"inject_retry_errors_on_commit_enabled":                           "Causes statements inside explicit transactions to return a retry error just before transaction commit for testing retry logic.",
	"integer_datetimes":                                               "Reports whether integer datetime representation is used (always on).",
	"internal":                                                        "Indicates whether this query came from InternalExecutor or an internal planner.",
	"intervalstyle":                                                   "Controls the display format for `INTERVAL` values.",
	"intervalstyle_enabled":                                           "Legacy setting that no longer has any effect. Always true.",
	"is_superuser":                                                    "Indicates whether the current user has superuser privileges.",
	"join_reader_index_join_strategy_batch_size":                      "Sets the size limit on input rows to the joinReader processor when performing index joins for a single lookup KV batch.",
	"join_reader_no_ordering_strategy_batch_size":                     "Sets the size limit on input rows to the joinReader processor (when ordering is not maintained) for a single lookup KV batch.",
	"join_reader_ordering_strategy_batch_size":                        "Sets the size limit on input rows to the joinReader processor (when ordering must be maintained) for a single lookup KV batch.",
	"kv_transaction_buffered_writes_enabled":                          "Controls whether the buffered writes KV transaction protocol is used for user queries on the current session. Changes made in an explicit transaction apply only to later transactions.",
	"large_full_scan_rows":                                            "Sets the estimated row count at which a full scan is considered large and worthy of logging or disabling.",
	"lc_collate":                                                      "Reports the database collation locale.",
	"lc_ctype":                                                        "Reports the database character classification locale.",
	"lc_messages":                                                     "Sets the language in which messages are displayed (compatibility setting).",
	"lc_monetary":                                                     "Sets the locale for formatting monetary amounts (compatibility setting).",
	"lc_numeric":                                                      "Sets the locale for formatting numbers (compatibility setting).",
	"lc_time":                                                         "Sets the locale for formatting dates and times (compatibility setting).",
	"legacy_varchar_typing":                                           "Controls the legacy behavior of allowing some invalid mix-typed comparisons with VARCHAR types.",
	"locality":                                                        "The locality of the current node, as set by `cockroach start --locality`.",
	"locality_optimized_partitioned_index_scan":                       "Controls whether locality-optimized partitioned index scans are enabled.",
	"lock_timeout":                                                    "Sets the maximum amount of time a query can spend acquiring or waiting for a single row-level lock. Unlike in PostgreSQL, non-locking reads in CockroachDB also wait for conflicting locks, so this timeout applies to writes as well as locking and non-locking reads. If set to 0, queries do not time out due to lock acquisitions.",
	"log_timezone":                                                    "The timezone used for logging (always UTC).",
	"max_connections":                                                 "Reports the maximum number of concurrent connections.",
	"max_identifier_length":                                           "The maximum length allowed for identifiers.",
	"max_index_keys":                                                  "Reports the maximum number of index keys (always 32).",
	"max_prepared_transactions":                                       "Reports the maximum number of prepared transactions (always maximum int32).",
	"max_retries_for_read_committed":                                  "Sets the maximum number of automatic retries for statements in explicit READ COMMITTED transactions that encounter retry errors.",
	"multiple_active_portals_enabled":                                 "Determines if pgwire portal execution for certain queries can be paused, allowing interleaved execution with local plans.",
	"node_id":                                                         "The ID of the current node.",
	"null_ordered_last":                                               "Controls whether NULL values are ordered last. When true, NULL values appear after non-NULL values in ordered results.",
	"on_update_rehome_row_enabled":                                    "Controls whether the ON UPDATE rehome_row() will actually trigger on row updates.",
	"opt_split_scan_limit":                                            "Sets the maximum number of UNION ALL statements a Scan may be split into during query optimization to avoid a sort.",
	"optimizer":                                                       "Controls whether the cost-based optimizer is enabled.",
	"optimizer_always_use_histograms":                                 "Ensures that the optimizer always uses histograms to calculate statistics if available.",
	"optimizer_check_input_min_row_count":                             "Sets a lower bound on row count estimates for the buffer scan of foreign key and uniqueness checks.",
	"optimizer_clamp_inequality_selectivity":                          "Controls whether the optimizer clamps selectivity estimates for inequality predicates to improve cardinality estimation accuracy.",
	"optimizer_clamp_low_histogram_selectivity":                       "Controls whether the optimizer clamps low selectivity estimates from histogram statistics to prevent overly optimistic cardinality estimates.",
	"optimizer_disable_cross_region_cascade_fast_path_for_rbr_tables": "Controls whether the optimizer disables the cross-region cascade fast path optimization for REGIONAL BY ROW tables.",
	"optimizer_enable_lock_elision":                                   "Controls whether the optimizer can eliminate unnecessary locking operations.",
	"optimizer_hoist_uncorrelated_equality_subqueries":                "Controls whether the optimizer hoists uncorrelated subqueries in equality expressions with columns, potentially producing more efficient plans.",
	"optimizer_inline_any_unnest_subquery":                            "Controls whether the optimizer inlines subqueries containing ANY expressions combined with UNNEST.",
	"optimizer_merge_joins_enabled":                                   "Controls whether the optimizer should explore query plans with merge joins.",
	"optimizer_min_row_count":                                         "Sets a lower bound on row count estimates during query planning, except for expressions with zero cardinality.",
	"optimizer_plan_lookup_joins_with_reverse_scans":                  "Controls whether the optimizer can plan lookup joins using reverse index scans.",
	"optimizer_prefer_bounded_cardinality":                            "Instructs the optimizer to prefer query plans where every expression has a bounded cardinality over plans with unbounded cardinality expressions.",
	"optimizer_prove_implication_with_virtual_computed_columns":       "Controls whether the optimizer should use virtual computed columns to prove partial index implication.",
	"optimizer_push_limit_into_project_filtered_scan":                 "Controls whether the optimizer should push limit expressions into projects of filtered scans.",
	"optimizer_push_offset_into_index_join":                           "Controls whether the optimizer should push offset expressions into index joins.",
	"optimizer_use_conditional_hoist_fix":                             "Prevents the optimizer from hoisting volatile expressions that are conditionally executed by CASE, COALESCE, or IFERR expressions.",
	"optimizer_use_delete_range_fast_path":                            "Controls whether the optimizer uses the fast path for DELETE operations using range deletions.",
	"optimizer_use_exists_filter_hoist_rule":                          "Controls whether the optimizer hoists filters out of EXISTS subqueries.",
	"optimizer_use_forecasts":                                         "Controls whether the optimizer should use statistics forecasts for cardinality estimation.",
	"optimizer_use_histograms":                                        "Controls whether the optimizer should use histogram statistics for cardinality estimation.",
	"optimizer_use_improved_computed_column_filters_derivation":       "Enables the optimizer to derive filters on computed columns in more cases beyond simple single-column equations.",
	"optimizer_use_improved_disjunction_stats":                        "Controls whether the optimizer should use improved statistics calculations for disjunctive filters.",
	"optimizer_use_improved_distinct_on_limit_hint_costing":           "Controls whether the optimizer should use an improved costing estimate for DistinctOn operators with limit hints.",
	"optimizer_use_improved_hoist_join_project":                       "Controls whether the optimizer uses an improved rule for hoisting projections out of joins.",
	"optimizer_use_improved_join_elimination":                         "Allows the optimizer to eliminate joins in more cases by remapping columns from eliminated joins to equivalent columns.",
	"optimizer_use_improved_multi_column_selectivity_estimate":        "Controls whether the optimizer should use an improved selectivity estimate for multi-column predicates.",
	"optimizer_use_improved_split_disjunction_for_joins":              "Enables the optimizer to split more disjunctions (OR expressions) in join conditions by building a UNION of join expressions.",
	"optimizer_use_improved_trigram_similarity_selectivity":           "Controls whether the optimizer should use an improved selectivity estimate for trigram similarity filters.",
	"optimizer_use_improved_zigzag_join_costing":                      "Controls whether the optimizer should use improved logic in the cost model for zigzag joins.",
	"optimizer_use_limit_ordering_for_streaming_group_by":             "Enables optimization for 'SELECT ... GROUP BY ... ORDER BY ... LIMIT n' queries by using the limit ordering to inform group-by requirements.",
	"optimizer_use_lock_elision_multiple_families":                    "Controls whether the optimizer enables lock elision for operations involving multiple column families.",
	"optimizer_use_lock_op_for_serializable":                          "Controls whether the optimizer implements SELECT FOR UPDATE and FOR SHARE using the Lock operator under serializable isolation.",
	"optimizer_use_max_frequency_selectivity":                         "Controls whether the optimizer uses the maximum frequency value for selectivity estimation.",
	"optimizer_use_merged_partial_statistics":                         "Controls whether the optimizer should use statistics merged from partial and full statistics for cardinality estimation.",
	"optimizer_use_min_row_count_anti_join_fix":                       "Controls whether the optimizer uses a fix for minimum row count estimation in anti-join operations.",
	"optimizer_use_multicol_stats":                                    "Controls whether the optimizer should use multi-column statistics for cardinality estimation.",
	"optimizer_use_not_visible_indexes":                               "Controls whether the optimizer can still choose to use not visible indexes for query plans.",
	"optimizer_use_polymorphic_parameter_fix":                         "Controls whether the optimizer validates routine polymorphic parameters during overload resolution and type-checking.",
	"optimizer_use_provided_ordering_fix":                             "Controls whether the optimizer reconciles provided orderings with required ordering choices to prevent internal errors.",
	"optimizer_use_trigram_similarity_optimization":                   "Controls whether the optimizer should generate improved plans for queries with trigram similarity filters.",
	"optimizer_use_virtual_computed_column_stats":                     "Controls whether the optimizer should use statistics on virtual computed columns for cardinality estimation.",
	"override_multi_region_zone_config":                               "Controls whether zone configurations can be modified for multi-region databases and their objects.",
	"parallelize_multi_key_lookup_joins_avg_lookup_ratio":             "Sets the average lookup ratio threshold for parallelizing multi-key lookup joins.",
	"parallelize_multi_key_lookup_joins_avg_lookup_row_size":          "Sets the average lookup row size threshold for parallelizing multi-key lookup joins.",
	"parallelize_multi_key_lookup_joins_enabled":                      "Controls whether the join reader should parallelize lookup batches. When enabled, this increases the speed of lookup joins with multiple looked up rows at the cost of increased memory usage.",
	"parallelize_multi_key_lookup_joins_max_lookup_ratio":             "Sets the maximum lookup ratio threshold for parallelizing multi-key lookup joins.",
	"parallelize_multi_key_lookup_joins_only_on_mr_mutations":         "Controls whether parallelization of multi-key lookup joins is restricted to multi-row mutations only.",
	"password_encryption":                                             "The encryption method used for passwords.",
	"pg_trgm.similarity_threshold":                                    "Sets the value used to compare trigram similarities for the string % string overload.",
	"plan_cache_mode":                                                 "Controls the method that the optimizer should use to choose between a custom and generic query plan.",
	"plpgsql_use_strict_into":                                         "Causes PL/pgSQL \"SELECT ... INTO\" and \"RETURNING INTO\" syntax to always behave as if specified with STRICT option.",
	"prefer_lookup_joins_for_fks":                                     "Causes foreign key operations to prefer lookup joins.",
	"prepared_statements_cache_size":                                  "Causes the LRU prepared statements in a session to be automatically deallocated when total prepared statement memory usage exceeds this value.",
	"prevent_update_set_column_drop":                                  "Controls whether columns referenced in an UPDATE SET clause are prevented from being dropped.",
	"propagate_admission_header_to_leaf_transactions":                 "Controls whether admission control headers are propagated to leaf transactions in distributed queries.",
	"propagate_input_ordering":                                        "Controls whether to propagate inner ordering to the outer scope when planning subqueries or CTEs if the outer scope is unordered.",
	"recursion_depth_limit":                                           "Sets the maximum depth that nested trigger function calls can reach.",
	"register_latch_wait_contention_events":                           "Controls whether contention events are registered for latch wait operations.",
	"reorder_joins_limit":                                             "Sets the number of joins at which the optimizer should stop attempting to reorder.",
	"require_explicit_primary_keys":                                   "Controls whether CREATE TABLE statements should error out if no primary key is provided.",
	"results_buffer_size":                                             "Specifies the size at which the pgwire results buffer will self-flush.",
	"role":                                                            "The current role for the session.",
	"row_security":                                                    "Controls whether row level security is enabled.",
	"search_path":                                                     "Sets the list of namespaces to search when resolving unqualified names.",
	"serial_normalization":                                            "Controls how `SERIAL` columns are normalized.",
	"server_encoding":                                                 "Reports the database encoding (always UTF8). This cannot be changed.",
	"server_version":                                                  "Reports the server version string.",
	"server_version_num":                                              "Reports the server version as an integer.",
	"session_authorization":                                           "The authorized user for the current session.",
	"session_id":                                                      "The unique identifier for the current session.",
	"session_user":                                                    "The name of the user logged into the current session.",
	"show_primary_key_constraint_on_not_visible_columns":              "Controls whether SHOW CONSTRAINTS and pg_catalog.pg_constraint include primary key constraints with only hidden columns.",
	"sql_safe_updates":                                                "When enabled, disallows potentially unsafe SQL statements: `DROP DATABASE` of a non-empty database, `DELETE` and `UPDATE` without a `WHERE` clause (unless a `LIMIT` clause is included), `SELECT ... FOR UPDATE`/`FOR SHARE` without a `WHERE` or `LIMIT` clause, `ALTER TABLE ... DROP COLUMN`, and converting an existing table to `REGIONAL BY ROW` unless a region column has already been added.",
	"ssl":                                                             "Controls whether SSL is enabled.",
	"ssl_renegotiation_limit":                                         "Sets the limit for SSL renegotiation.",
	"standard_conforming_strings":                                     "Controls whether strings conform to SQL standard.",
	"statement_timeout":                                               "Sets the maximum allowed duration for a statement. The query is cancelled if it exceeds this limit.",
	"streamer_always_maintain_ordering":                               "Controls whether the SQL users of the DistSQL Streamer should always maintain ordering, even when not strictly necessary.",
	"streamer_enabled":                                                "Controls whether the DistSQL Streamer API can be used.",
	"streamer_head_of_line_only_fraction":                             "Controls the fraction of the DistSQL streamer's memory budget used for the head-of-the-line request when the eager memory usage limit has been exceeded.",
	"streamer_in_order_eager_memory_usage_fraction":                   "Controls the fraction of the DistSQL streamer's memory budget that might be used for issuing requests eagerly in the InOrder mode.",
	"streamer_out_of_order_eager_memory_usage_fraction":               "Controls the fraction of the DistSQL streamer's memory budget that might be used for issuing requests eagerly in the OutOfOrder mode.",
	"strict_ddl_atomicity":                                            "When enabled, causes errors when DDL operations inside an explicit transaction cannot be guaranteed to be performed atomically, preventing partial transaction commits.",
	"stub_catalog_tables":                                             "Controls whether catalog tables are stubbed out.",
	"synchronize_seqscans":                                            "Controls whether synchronized sequential scans are enabled (compatibility setting).",
	"system_identity":                                                 "Indicates the original name of the client presented to pgwire before it was mapped to a SQL identifier.",
	"tcp_keepalives_count":                                            "Sets the number of TCP keepalive probes to send before giving up on the connection.",
	"tcp_keepalives_idle":                                             "Sets the time interval in seconds before TCP keepalive probes are sent on idle connections.",
	"tcp_keepalives_interval":                                         "Sets the time interval in seconds between TCP keepalive probes.",
	"tcp_user_timeout":                                                "Sets the time in milliseconds before a connection is forcibly closed if data is not acknowledged.",
	"temporary_schema_name":                                           "Sets the name of the temporary schema, which is used for storing temporary tables created in the session.",
	"testing_optimizer_cost_perturbation":                             "Controls the random cost perturbation factor for producing non-optimal query plans during testing.",
	"testing_optimizer_disable_rule_probability":                      "Sets the probability of randomly disabling non-essential optimizer transformation rules for testing.",
	"testing_optimizer_inject_panics":                                 "Controls whether random panics are injected during optimization to test error-propagation.",
	"testing_optimizer_random_seed":                                   "Sets a random seed for the optimizer for testing by initializing an RNG with the given integer.",
	"testing_vectorize_inject_panics":                                 "Controls whether random panics are injected into vectorized execution to test error propagation.",
	"timezone":                                                        "Sets the timezone used for parsing timestamps.",
	"tracing":                                                         "Controls whether tracing is enabled for the session.",
	"transaction_isolation":                                           "The isolation level of the current transaction. Possible values are `SERIALIZABLE` and `READ COMMITTED`. Also allows the isolation level to change as long as queries have not been executed yet.",
	"transaction_priority":                                            "The priority level of the current transaction. Possible values are `LOW`, `NORMAL`, and `HIGH`.",
	"transaction_read_only":                                           "Controls whether the current transaction is read-only.",
	"transaction_rows_read_err":                                       "Sets the limit for the number of rows read by a SQL transaction which - once exceeded - will fail the transaction (0 means disabled).",
	"transaction_rows_read_log":                                       "Sets the threshold for the number of rows read by a SQL transaction which - once exceeded - will trigger a logging event.",
	"transaction_rows_written_err":                                    "The limit for the number of rows written by a SQL transaction which - once exceeded - will fail the transaction (0 means disabled).",
	"transaction_rows_written_log":                                    "Sets the threshold for the number of rows written by a SQL transaction which - once exceeded - will trigger a logging event.",
	"transaction_status":                                              "Reports the current transaction status.",
	"transaction_timeout":                                             "Sets the maximum duration a transaction is permitted to run before cancellation.",
	"troubleshooting_mode":                                            "When enabled, avoids performing additional work on queries such as collecting and emitting telemetry data. This is particularly useful when the cluster is experiencing issues, unavailability, or failure.",
	"unbounded_parallel_scans":                                        "Controls whether the TableReader DistSQL processors should parallelize scans across ranges.",
	"unconstrained_non_covering_index_scan_enabled":                   "Controls whether unconstrained non-covering index scan access paths are explored by the optimizer.",
	"unsafe_allow_triggers_modifying_cascades":                        "When enabled, allows row-level BEFORE triggers to modify or filter rows that are being updated or deleted as part of a cascading foreign key action. This is unsafe because it can lead to constraint violations.",
	"use_backups_with_ids":                                            "Controls whether backup operations use backup IDs.",
	"use_cputs_on_non_unique_indexes":                                 "Controls whether conditional puts (CPuts) at the KV layer are used on non-unique indexes.",
	"use_declarative_schema_changer":                                  "Controls whether the declarative schema changer is used.",
	"use_improved_routine_dependency_tracking":                        "Controls whether improved dependency tracking is used for stored procedures and routines.",
	"use_improved_routine_deps_triggers_and_computed_cols":            "Controls whether improved dependency tracking is used for routines involving triggers and computed columns.",
	"use_pre_25_2_variadic_builtins":                                  "Controls whether pre-25.2 variadic built-in function behavior is used.",
	"use_proc_txn_control_extended_protocol_fix":                      "Controls whether a fix for procedure transaction control with the extended protocol is enabled.",
	"use_soft_limit_for_distribute_scan":                              "Controls whether soft limits are used for distributing scans across nodes.",
	"use_swap_mutations":                                              "Controls whether swap mutations are used as an alternative mutation strategy.",
	"variable_inequality_lookup_join_enabled":                         "Controls whether the optimizer should consider lookup joins with inequality conditions.",
	"vector_search_beam_size":                                         "Sets the beam width for vector search operations.",
	"vector_search_rerank_multiplier":                                 "Sets the multiplier for re-ranking candidates in vector search results.",
	"vectorize":                                                       "Controls if and when the Executor executes queries using the columnar execution engine. Can be 'off', 'on', or 'experimental_always'.",
	"work_mem":                                                        "Determines how much RAM (in bytes) a single operation of a single query can use before it has to spill to disk.",
	"xmloption":                                                       "Sets how XML data is to be implicitly parsed (compatibility setting).",
}
