#!/bin/bash
set -euo pipefail

cd "$(dirname $0)/.."
if [[ $# != 4 ]]; then
    cat 1>&2 <<EOF
$0 compares plans of newline-separated queries in queryfile by running EXPLAIN
(VERBOSE) <query> against each cockroach server specified.
Note that this tool assumes the server is up and running in insecure mode and
listening on the specified port.
Usage: $0 path/to/cockroach/binary queryfile oldport newport
EOF
    exit 1
fi

COCKROACH_BINARY=$1
QUERYFILE=$2
OLDPORT=$3
NEWPORT=$4

dest=$(mktemp -d)
echo "Writing query plans to ${dest}"

ports=($OLDPORT $NEWPORT)

querynum=0
while read line
do
    for port in "${ports[@]}"
    do
        version="old"
        if [[ $port != $OLDPORT ]]; then
            version="new"
        fi

        # Run the sql client displaying the results in table format for easy
        # to read output. The sed command removes the line "(n rows)" from the
        # output.
        $COCKROACH_BINARY sql --insecure --port=$port --format=table -e "EXPLAIN (VERBOSE) $line" | sed '/^(/ d' > $dest/query$querynum.$version
    done
    ((querynum++))
done < $QUERYFILE

for (( i=0; i<$querynum; i+=1 )); do
    tmpfile=$(mktemp)
    if ! diff "$dest/query$i.old" "$dest/query$i.new" > $tmpfile; then
        echo "found difference in plans for query $i"
        cat $tmpfile
    fi
    rm $tmpfile
done
