{
 "title": "CRDB Console: Changefeeds",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "Cluster Name",
    "query": "sys_uptime{job=\"crdb\"}"
   },
   {
    "name": "node",
    "label": "Node",
    "query": "label_values(sys_uptime{job=\"crdb\",cluster=\"$cluster\"},instance)"
   },
   { "name": "rate_interval", "label": "Rate Interval", "query": "30s,1m,5m,10m,30m,1h,6h,12h,1d" }
  ]
 },
 "panels": [
  {
   "title": "sink Byte Traffic",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Bytes(B)" }
   ],
   "targets": [
    {
     "expr": "sum(rate(changefeed_emitted_bytes{job=\"crdb\",cluster=~\"cluster\"}[$__rate_interval]))",
     "legendFormat": "Emitted Bytes"
    }
   ]
  },
  {
   "title": "Changefeed Restarts",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short", "label": "actions" }
   ],
   "targets": [
    {
     "expr": "sum(jobs_changefeed_resume_retry_error{job=\"crdb\",cluster=\"$cluster\"})",
     "legendFormat": "Retryable Errors"
    }
   ]
  },
  {
   "title": "Sink Timings",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "ns", "label": "time (ns)" }
   ],
   "targets": [
    {
     "expr": "sum(changefeed_flush_nanos{job=\"crdb\",cluster=\"$cluster\"})",
     "legendFormat": "Flush Time"
    },
    {
     "expr": "sum(changefeed_emitted_messages{job=\"crdb\",cluster=\"$cluster\"})",
     "legendFormat": "Message Emit time"
    }
   ]
  },
  {
   "title": "Sink Count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short", "label": "actions" }
   ],
   "targets": [
    {
     "expr": "sum(rate(changefeed_flushes{job=\"crdb\",cluster=\"$cluster\"}[$__rate_interval]))",
     "legendFormat": "Flushes"
    },
    {
     "expr": "sum(rate(changefeed_emitted_messages{job=\"crdb\",cluster=\"$cluster\"}[$__rate_interval]))",
     "legendFormat": "Messages"
    }
   ]
  },
  {
   "title": "Max Changefeed latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "ns", "label": "time (ns)" }
   ],
   "targets": [
    {
     "expr": "changefeed_max_behind_nanos{jobs=\"crdb\",cluster=\"$cluster\"}",
     "legendFormat": "Max Changefeed Latency"
    }
   ]
  }
 ]
}