{
 "title": "CRDB Console: Overview",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "clusterfilter",
    "label": "Cluster Filter",
    "query": "sys_uptime{job=\"crdb\"}"
   },
   {
    "name": "node",
    "label": "Node",
    "query": "label_values(sys_uptime{job=\"crdb\",cluster=\"$clusterfilter\"},instance)"
   },
   { "name": "rate_interval", "label": "Rate Interval", "query": "30s,1m,5m,10m,30m,1h,6h,12h,1d" }
  ]
 },
 "panels": [
  {
   "title": "Capacity",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "bytes", "label": "Capacity (TiB)" }
   ],
   "targets": [
    {
     "expr": "sum(sum(capacity_used{job=\"crdb\",cluster=~\"$clusterfilter\"}) by (instance))",
     "legendFormat": "Used"
    },
    {
     "expr": "sum(sum(capacity_available{job=\"crdb\",cluster=~\"$clusterfilter\"}) by (cluster))",
     "legendFormat": "Max"
    },
    {
     "expr": "sum(sum(capacity_available{job=\"crdb\",cluster=~\"$clusterfilter\"}) by (cluster)) - sum(sum(capacity_used{job=\"crdb\",cluster=~\"$clusterfilter\"}) by (instance))",
     "legendFormat": "Available"
    }
   ]
  },
  {
   "title": "Replicas Per Node",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short", "label": "Replicas" }
   ],
   "targets": [
    {
     "expr": "sum(replicas{cluster=\"$clusterfilter\",job=\"crdb\",instance=~\"$node\"}) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Service latency: SQL,99th Percentile",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "ns", "label": "Latency (s)" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, rate(sql_service_latency_bucket{job=\"crdb\",cluster=~\"$clusterfilter\"}[$__rate_interval]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "SQL Queries",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short", "label": "queries" }
   ],
   "targets": [
    {
     "expr": "sum(rate(sql_select_count{job=\"crdb\",cluster=~\"$clusterfilter\"}[$__rate_interval]))  + sum(rate(sql_update_count{job=\"crdb\",cluster=~\"$clusterfilter\"}[$__rate_interval])) + sum(rate(sql_delete_count{job=\"crdb\",cluster=~\"$clusterfilter\"}[$__rate_interval]))  + \nsum(rate(sql_insert_count{job=\"crdb\",cluster=~\"$clusterfilter\"}[$__rate_interval]))",
     "legendFormat": "total QPS"
    },
    {
     "expr": "sum(rate(sql_select_count{job=\"crdb\",cluster=~\"$clusterfilter\"}[$__rate_interval]))",
     "legendFormat": "SELECTs"
    },
    {
     "expr": "sum(rate(sql_insert_count{job=\"crdb\",cluster=~\"$clusterfilter\"}[$__rate_interval]))",
     "legendFormat": "INSERTs"
    },
    {
     "expr": "sum(rate(sql_update_count{job=\"crdb\",cluster=~\"$clusterfilter\"}[$__rate_interval]))",
     "legendFormat": "{{cluster}} UPDATEs"
    },
    {
     "expr": "sum(rate(sql_delete_count{job=\"crdb\",cluster=~\"$clusterfilter\"}[$__rate_interval]))",
     "legendFormat": "DELETEs"
    }
   ]
  }
 ]
}