{
 "title": "CBDB Console:  Replications",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   { "name": "rate_interval", "label": "Rate Interval", "query": "30s,1m,5m,15m,30m,1h,2h,1d" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "sys_uptime{job=\"crdb\"}"
   },
   {
    "name": "node",
    "label": "Node",
    "query": "label_values(sys_uptime{job=\"crdb\",cluster=\"$cluster\"},instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "logical Bytes per store",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "decgbytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(sysbytes{job=\"crdb\",cluster=\"$cluster\"}[$__rate_interval]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Average Queries per Store",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(sql_query_count{job=\"crdb\",cluster=\"$cluster\",instance=~\"$node\"}[$__rate_interval]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Snapshots",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "ops", "label": "Snapshots" }
   ],
   "targets": [
    {
     "expr": "sum(rate(range_snapshots_generated{cluster=\"$cluster\",job=\"crdb\",instance=~\"$node\"}[$rate_interval]))",
     "legendFormat": "Generated"
    },
    {
     "expr": "sum(rate(range_snapshots_normal_applied{cluster=\"$cluster\",job=\"crdb\",instance=~\"$node\"}[$rate_interval]))",
     "legendFormat": "Applied(raft-initiated)"
    },
    {
     "expr": "sum(rate(range_snapshots_preemptive_applied{cluster=\"$cluster\",job=\"crdb\",instance=~\"$node\"}[$rate_interval]))",
     "legendFormat": "Applied(leaner)"
    },
    {
     "expr": "sum(rate(capacity_reserved{cluster=~\"$cluster\",job=\"crdb\",instance=~\"$node\"}[$__rate_interval]))",
     "legendFormat": "Reserved capacity"
    },
    {
     "expr": "sum(rate(replicas_reserved{cluster=~\"$cluster\",job=\"crdb\",instance=~\"$node\"}[$__rate_interval]))",
     "legendFormat": "Reserved Replicas"
    }
   ]
  },
  {
   "title": "Range Operations",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(sum(rate(range_splits{cluster=\"$cluster\",job=\"crdb\",instance=~\"$node\"}[$rate_interval])) by (instance))",
     "legendFormat": "Splits"
    },
    {
     "expr": "sum(sum(rate(range_adds{cluster=\"$cluster\",job=\"crdb\",instance=~\"$node\"}[$rate_interval])) by (instance))",
     "legendFormat": "Adds"
    },
    {
     "expr": "sum(sum(rate(range_merges{cluster=\"$cluster\",job=\"crdb\",instance=~\"$node\"}[$rate_interval])) by (instance))",
     "legendFormat": "Merges"
    },
    {
     "expr": "sum(sum(rate(range_removes{cluster=\"$cluster\",job=\"crdb\",instance=~\"$node\"}[$rate_interval])) by (instance))",
     "legendFormat": "Removes"
    },
    {
     "expr": "sum(sum(rate(range_raftleadertransfers{cluster=\"$cluster\",job=\"crdb\",instance=~\"$node\"}[$rate_interval])) by (instance))",
     "legendFormat": "leader Transfers"
    },
    {
     "expr": "sum(sum(rate(rebalancing_lease_transfers{cluster=\"$cluster\",job=\"crdb\",instance=~\"$node\"}[$rate_interval])) by (instance))",
     "legendFormat": "Load-based Lease Transfers"
    },
    {
     "expr": "sum(sum(rate(rebalancing_range_rebalances{cluster=\"$cluster\",job=\"crdb\",instance=~\"$node\"}[$rate_interval])) by (instance))",
     "legendFormat": "Load-based Range Rebalances"
    }
   ]
  },
  {
   "title": "Replica Quiescene",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(sum(replicas{cluster=\"$cluster\",job=\"crdb\",instance=~\"$node\"}) by (instance))  ",
     "legendFormat": "Replicas"
    },
    {
     "expr": "sum(sum(replicas_quiescent{cluster=\"$cluster\",job=\"crdb\",instance=~\"$node\"}) by (instance))",
     "legendFormat": "Quiescent"
    }
   ]
  },
  {
   "title": "Replicase lease holders Per Node",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(replicas_leaseholders{cluster=\"$cluster\",job=\"crdb\",instance=~\"$node\"}) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Replicas Per Store",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(replicas{cluster=\"$cluster\",job=\"crdb\",instance=~\"$node\"}) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Ranges :$node",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 57 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(sum(replicas_leaseholders{cluster=\"$cluster\",job=\"crdb\",instance=~\"$node\"})) by (instance)",
     "legendFormat": "Ranges"
    },
    {
     "expr": "sum(sum(replicas_leaders{cluster=\"$cluster\",job=\"crdb\",instance=~\"$node\"}) by (instance))",
     "legendFormat": "Leaders"
    },
    {
     "expr": "sum(sum(replicas_leaders_not_leaseholders{cluster=\"$cluster\",job=\"crdb\",instance=~\"$node\"}) by (instance))",
     "legendFormat": "Leaders W/O Lease Holders"
    },
    {
     "expr": "sum(sum(ranges_unavailable{cluster=\"$cluster\",job=\"crdb\",instance=~\"$node\"}) by (instance))",
     "legendFormat": "Unavailable"
    },
    {
     "expr": "sum(sum(ranges_underreplicated{cluster=\"$cluster\",job=\"crdb\",instance=~\"$node\"}) by (instance))",
     "legendFormat": "under-replicated"
    },
    {
     "expr": "sum(sum(ranges_overreplicated{cluster=\"$cluster\",job=\"crdb\",instance=~\"$node\"}) by (instance))",
     "legendFormat": "Over-replicated"
    },
    {
     "expr": "sum(sum(replicas_leaseholders{cluster=\"$cluster\",job=\"crdb\",instance=~\"$node\"}) by (instance))",
     "legendFormat": "Lease Holders"
    },
    { "expr": "leasehol" }
   ]
  }
 ]
}