{
 "title": "CRDB Console: SQL",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "Cluster Name",
    "query": "sys_uptime{job=\"crdb\"}"
   },
   {
    "name": "node",
    "label": "Node",
    "query": "label_values(sys_uptime{job=\"crdb\",cluster=\"$cluster\"},instance)"
   },
   { "name": "rate_interval", "label": "Rate Interval", "query": "30s,1m,5m,10m,30m,1h,6h,12h,1d" }
  ]
 },
 "panels": [
  {
   "title": "Transaction latency: 90th Percentile",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "ns", "label": "Latency (ms)" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.90,rate(sql_txn_latency_bucket{job=\"crdb\",cluster=\"$cluster\"}[$__rate_interval]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Transaction latency :99th Percentile",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "µs", "label": "Latency (s)" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99,rate(sql_txn_latency_bucket{job=\"crdb\",cluster=\"$cluster\"}[5m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Schema Changes :$node",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(sql_ddl_count{job=\"crdb\",cluster=\"$cluster\",instance=~\"$node\"}[$rate_interval]))  ",
     "legendFormat": "DDL"
    }
   ]
  },
  {
   "title": "Transactions",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short", "label": "Latency (ms)" }
   ],
   "targets": [
    {
     "expr": "sum(rate(sql_txn_begin_count{job=\"crdb\",cluster=\"$cluster\",instance=~\"$node\"}[$rate_interval]))",
     "legendFormat": "Begin"
    },
    {
     "expr": "sum(rate(sql_txn_commit_count{job=\"crdb\",cluster=\"$cluster\",instance=~\"$node\"}[$rate_interval]))",
     "legendFormat": "Commit"
    },
    {
     "expr": "sum(rate(sql_txn_abort_count{job=\"crdb\",cluster=\"$cluster\",instance=~\"$node\"}[$rate_interval]))",
     "legendFormat": "Abort"
    },
    {
     "expr": "sum(rate( sql_txn_rollback_count{job=\"crdb\",cluster=\"$cluster\",instance=~\"$node\"}[$rate_interval]))",
     "legendFormat": "Rollback"
    }
   ]
  },
  {
   "title": "KV Execution latency: 90th Percentile",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "ns", "label": "Latency (ms)" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.90, rate(exec_latency_bucket{job=\"crdb\",instance=~\"$node\",cluster=\"$cluster\"}[$rate_interval]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "KV Execution latency: 99th Percentile",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "µs", "label": "Latency (s)" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99,rate(exec_latency_bucket{job=\"crdb\",instance=~\"$node\"}[$rate_interval]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Service Latency: SQL, 90th Percentile",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.90, rate(sql_service_latency_bucket{job=\"crdb\",instance=~\"$node\",cluster=\"$cluster\"}[$__rate_interval]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Service latency: SQL, 99th Percentile",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, rate(sql_service_latency_bucket{job=\"crdb\",instance=~\"$node\",cluster=\"$cluster\"}[$__rate_interval]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Active Flows for Distributed Queries",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
   "yaxes": [
    { "format": "short", "label": "flows" }
   ],
   "targets": [
    {
     "expr": "rate(sql_distsql_flows_active{jobs=\"crdb\",cluster=~\"$cluster\",instance=~\"$node\"}[$__rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Active distributed SQL queries",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 72 },
   "yaxes": [
    { "format": "short", "label": "queries" }
   ],
   "targets": [
    {
     "expr": "sum(sql_distsql_queries_active{job=\"crdb\", cluster=~\"$cluster\",instance=~\"$node\"})",
     "legendFormat": "Active Queries"
    }
   ]
  },
  {
   "title": "SQL Query Errors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 80 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(sql_failure_count{job=\"crdb\",cluster=~\"$cluster\"}[$__rate_interval]))",
     "legendFormat": "Errors"
    }
   ]
  },
  {
   "title": "SQL Queries",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 88 },
   "yaxes": [
    { "format": "short", "label": "queries" }
   ],
   "targets": [
    {
     "expr": "sum(rate(sql_select_count{job=\"crdb\",cluster=\"$cluster\",instance=~\"$node\"}[$rate_interval]))",
     "legendFormat": "Select"
    },
    {
     "expr": "sum(rate(sql_update_count{job=\"crdb\",cluster=\"$cluster\",instance=~\"$node\"}[$rate_interval]))",
     "legendFormat": "Update"
    },
    {
     "expr": "sum(rate(sql_insert_count{job=\"crdb\",cluster=\"$cluster\",instance=~\"$node\"}[$rate_interval]))",
     "legendFormat": "Insert"
    },
    {
     "expr": "sum(rate(sql_delete_count{job=\"crdb\",cluster=\"$cluster\",instance=~\"$node\"}[$rate_interval]))",
     "legendFormat": "Delete"
    }
   ]
  },
  {
   "title": "SQL Byte Traffic",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 96 },
   "yaxes": [
    { "format": "bytes", "label": "byte Traffic (MiB)" }
   ],
   "targets": [
    {
     "expr": "sum(rate(sql_bytesin{job=\"crdb\", cluster=\"$cluster\",instance=~\"$node\"}[$__rate_interval]))",
     "legendFormat": "Bytes in"
    },
    {
     "expr": "sum(rate(sql_bytesout{job=\"crdb\", cluster=\"$cluster\",instance=~\"$node\"}[$__rate_interval]))",
     "legendFormat": "Bytes Out"
    }
   ]
  },
  {
   "title": "SQL Connections",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 104 },
   "yaxes": [
    { "format": "short", "label": "connections" }
   ],
   "targets": [
    {
     "expr": "sql_conns{cluster=\"$cluster\",job=\"crdb\",instance=~\"$node\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}