{
 "title": "CBDB Console: Storage",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "Cluster Name",
    "query": "sys_uptime{job=\"crdb\"}"
   },
   {
    "name": "node",
    "label": "Node",
    "query": "label_values(sys_uptime{job=\"crdb\",cluster=\"$cluster\"},instance)"
   },
   { "name": "rate_interval", "label": "Rate Interval", "query": "30s,1m,5m,10m,30m,1h,6h,12h,1d" }
  ]
 },
 "panels": [
  {
   "title": "Time Series Write",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(timeseries_write_samples{job=\"crdb\",cluster=~\"$cluster\",instance=~\"$node\"}[$__rate_interval]))",
     "legendFormat": "Samples"
    },
    {
     "expr": "sum(rate(timeseries_write_errors{job=\"crdb\",cluster=~\"$cluster\",instance=~\"$node\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "Time Series Bytes Written",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "kbytes" }
   ],
   "targets": [
    {
     "expr": "count(timeseries_write_bytes{job=\"crdb\",cluster=~\"$cluster\",instance=~\"$node\"})",
     "legendFormat": "Bytes Written"
    }
   ]
  },
  {
   "title": "Read Amplification",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(avg(rocksdb_read_amplification{job=\"crdb\",cluster=\"$cluster\",instance=~\"$node\"}) by (instance))",
     "legendFormat": "Read Amplification"
    }
   ]
  },
  {
   "title": "Compactions/Flushes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(rocksdb_compactions{job=\"crdb\",cluster=\"$cluster\"}[$__rate_interval]))",
     "legendFormat": "Compactions"
    },
    {
     "expr": "sum(rate(rocksdb_flushes{job=\"crdb\",cluster=\"$cluster\"}[$__rate_interval]))",
     "legendFormat": "Flushes"
    }
   ]
  },
  {
   "title": "SStables",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rocksdb_num_sstables{job=\"crdb\",cluster=\"$cluster\",instance=~\"$node\"})",
     "legendFormat": "SS tables"
    }
   ]
  },
  {
   "title": "File Descriptors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(sum(sys_fd_open{job=\"crdb\",cluster=\"$cluster\",instance=~\"$node\"}) by (instance))",
     "legendFormat": "Open"
    },
    {
     "expr": "sum(sum(sys_fd_softlimit{job=\"crdb\",cluster=\"$cluster\",instance=~\"$node\"}) by (instance))",
     "legendFormat": "Limit"
    }
   ]
  },
  {
   "title": "Command Commit Latency: 50th percentile ",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "µs", "label": "Latency (us)" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.50,rate(raft_process_commandcommit_latency_bucket{job=\"crdb\", instance=~\"$node\", cluster=~\"$cluster\"}[$__rate_interval]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Command Commit Latency: 99th percentile ",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "ns", "label": "Latency (ms)" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99,rate(raft_process_commandcommit_latency_bucket{job=\"crdb\", instance=~\"$node\", cluster=~\"$cluster\"}[$__rate_interval]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Log Commit Latency: 50th Percentile",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 65 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.50,rate(raft_process_logcommit_latency_bucket{job=\"crdb\",cluster=\"$cluster\",instance=~\"$node\"}[$__rate_interval]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Log Commit LATENCY: 99th Percentile",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 71 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99,rate(raft_process_logcommit_latency_bucket{job=\"crdb\",cluster=\"$cluster\",instance=~\"$node\"}[$__rate_interval]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Live Bytes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 79 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(sum(livebytes{job=\"crdb\",cluster=\"$cluster\",instance=~\"$node\"}) by (instance))",
     "legendFormat": "Live"
    },
    {
     "expr": "sum(sum(sysbytes{job=\"crdb\",cluster=\"$cluster\",instance=~\"$node\"}) by (instance))",
     "legendFormat": "System"
    }
   ]
  },
  {
   "title": "Capacity",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 87 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(sum(capacity{job=\"crdb\",cluster=\"$cluster\",instance=~\"$node\"}) by (instance)) - sum(sum(capacity_available{job=\"crdb\",cluster=\"$cluster\",instance=~\"$node\"}) by (instance))",
     "legendFormat": "Used"
    },
    {
     "expr": "sum(sum(capacity{job=\"crdb\",cluster=\"$cluster\",instance=~\"$node\"}) by (instance))",
     "legendFormat": "Capacity"
    },
    {
     "expr": " sum(sum(capacity_available{job=\"crdb\",cluster=\"$cluster\",instance=~\"$node\"}) by (instance))",
     "legendFormat": "Available"
    }
   ]
  }
 ]
}