// Copyright 2017 The Cockroach Authors.
//
// Use of this software is governed by the Business Source License
// included in the file licenses/BSL.txt.
//
// As of the Change Date specified in that file, in accordance with
// the Business Source License, use of this software will be governed
// by the Apache License, Version 2.0, included in the file
// licenses/APL.txt.

package catconstants

import "math"

// ReportableAppNamePrefix indicates that the application name can be
// reported in telemetry without scrubbing. (Note this only applies to
// the application name itself. Query data is still scrubbed as
// usual.)
const ReportableAppNamePrefix = "$ "

// InternalAppNamePrefix indicates that the application name identifies
// an internal task / query / job to CockroachDB. Different application
// names are used to classify queries in different categories.
const InternalAppNamePrefix = ReportableAppNamePrefix + "internal"

// DelegatedAppNamePrefix is added to a regular client application
// name for SQL queries that are ran internally on behalf of other SQL
// queries inside that application. This is not the same as
// RepotableAppNamePrefix; in particular the application name with
// DelegatedAppNamePrefix should be scrubbed in reporting.
const DelegatedAppNamePrefix = "$$ "

// Oid for virtual database and table.
const (
	CrdbInternalID = math.MaxUint32 - iota
	CrdbInternalBackwardDependenciesTableID
	CrdbInternalBuildInfoTableID
	CrdbInternalBuiltinFunctionsTableID
	CrdbInternalClusterContentionEventsTableID
	CrdbInternalClusterQueriesTableID
	CrdbInternalClusterTransactionsTableID
	CrdbInternalClusterSessionsTableID
	CrdbInternalClusterSettingsTableID
	CrdbInternalCreateStmtsTableID
	CrdbInternalCreateTypeStmtsTableID
	CrdbInternalDatabasesTableID
	CrdbInternalFeatureUsageID
	CrdbInternalForwardDependenciesTableID
	CrdbInternalGossipNodesTableID
	CrdbInternalGossipAlertsTableID
	CrdbInternalGossipLivenessTableID
	CrdbInternalGossipNetworkTableID
	CrdbInternalIndexColumnsTableID
	CrdbInternalInflightTraceSpanTableID
	CrdbInternalJobsTableID
	CrdbInternalKVNodeStatusTableID
	CrdbInternalKVStoreStatusTableID
	CrdbInternalLeasesTableID
	CrdbInternalLocalContentionEventsTableID
	CrdbInternalLocalQueriesTableID
	CrdbInternalLocalTransactionsTableID
	CrdbInternalLocalSessionsTableID
	CrdbInternalLocalMetricsTableID
	CrdbInternalPartitionsTableID
	CrdbInternalPredefinedCommentsTableID
	CrdbInternalRangesNoLeasesTableID
	CrdbInternalRangesViewID
	CrdbInternalRuntimeInfoTableID
	CrdbInternalSchemaChangesTableID
	CrdbInternalSessionTraceTableID
	CrdbInternalSessionVariablesTableID
	CrdbInternalStmtStatsTableID
	CrdbInternalTableColumnsTableID
	CrdbInternalTableIndexesTableID
	CrdbInternalTablesTableID
	CrdbInternalTablesTableLastStatsID
	CrdbInternalTransactionStatsTableID
	CrdbInternalTxnStatsTableID
	CrdbInternalZonesTableID
	CrdbInternalInvalidDescriptorsTableID
	CrdbInternalClusterDatabasePrivilegesTableID
	InformationSchemaID
	InformationSchemaAdministrableRoleAuthorizationsID
	InformationSchemaApplicableRolesID
	InformationSchemaCharacterSets
	InformationSchemaCheckConstraints
	InformationSchemaCollationCharacterSetApplicability
	InformationSchemaCollations
	InformationSchemaColumnPrivilegesID
	InformationSchemaColumnsTableID
	InformationSchemaColumnUDTUsageID
	InformationSchemaConstraintColumnUsageTableID
	InformationSchemaEnabledRolesID
	InformationSchemaKeyColumnUsageTableID
	InformationSchemaParametersTableID
	InformationSchemaReferentialConstraintsTableID
	InformationSchemaRoleTableGrantsID
	InformationSchemaRoutineTableID
	InformationSchemaSchemataTableID
	InformationSchemaSchemataTablePrivilegesID
	InformationSchemaSessionVariables
	InformationSchemaSequencesID
	InformationSchemaStatisticsTableID
	InformationSchemaTableConstraintTableID
	InformationSchemaTablePrivilegesID
	InformationSchemaTablesTableID
	InformationSchemaTypePrivilegesID
	InformationSchemaViewsTableID
	InformationSchemaUserPrivilegesID
	PgCatalogID
	PgCatalogAggregateFnoidIndexTableID
	PgCatalogAggregateTableID
	PgCatalogAmOidIndexTableID
	PgCatalogAmTableID
	PgCatalogAmopFamStratIndexTableID
	PgCatalogAmopOidIndexTableID
	PgCatalogAmopOprFamIndexTableID
	PgCatalogAmopTableID
	PgCatalogAmprocFamProcIndexTableID
	PgCatalogAmprocOidIndexTableID
	PgCatalogAmprocTableID
	PgCatalogAttrDefTableID
	PgCatalogAttrdefAdrelidAdnumIndexTableID
	PgCatalogAttrdefOidIndexTableID
	PgCatalogAttributeRelidAttnumIndexTableID
	PgCatalogAttributeTableID
	PgCatalogAuthIDTableID
	PgCatalogAuthMembersMemberRoleIndexTableID
	PgCatalogAuthMembersRoleMemberIndexTableID
	PgCatalogAuthMembersTableID
	PgCatalogAuthidOidIndexTableID
	PgCatalogAvailableExtensionVersionsTableID
	PgCatalogAvailableExtensionsTableID
	PgCatalogCastOidIndexTableID
	PgCatalogCastSourceTargetIndexTableID
	PgCatalogCastTableID
	PgCatalogClassOidIndexTableID
	PgCatalogClassTableID
	PgCatalogClassTblspcRelfilenodeIndexTableID
	PgCatalogCollationOidIndexTableID
	PgCatalogCollationTableID
	PgCatalogConfigTableID
	PgCatalogConstraintConparentidIndexTableID
	PgCatalogConstraintContypidIndexTableID
	PgCatalogConstraintOidIndexTableID
	PgCatalogConstraintTableID
	PgCatalogConversionDefaultIndexTableID
	PgCatalogConversionOidIndexTableID
	PgCatalogConversionTableID
	PgCatalogCursorsTableID
	PgCatalogDatabaseOidIndexTableID
	PgCatalogDatabaseTableID
	PgCatalogDbRoleSettingDatabaseidRolIndexTableID
	PgCatalogDbRoleSettingTableID
	PgCatalogDefaultACLOidIndexTableID
	PgCatalogDefaultACLRoleNspObjIndexTableID
	PgCatalogDefaultACLTableID
	PgCatalogDependDependerIndexTableID
	PgCatalogDependReferenceIndexTableID
	PgCatalogDependTableID
	PgCatalogDescriptionOCOIndexTableID
	PgCatalogDescriptionTableID
	PgCatalogEnumOidIndexTableID
	PgCatalogEnumTableID
	PgCatalogEnumTypidSortorderIndexTableID
	PgCatalogEventTriggerOidIndexTableID
	PgCatalogEventTriggerTableID
	PgCatalogExtensionOidIndexTableID
	PgCatalogExtensionTableID
	PgCatalogFileSettingsTableID
	PgCatalogForeignDataWrapperOidIndexTableID
	PgCatalogForeignDataWrapperTableID
	PgCatalogForeignServerOidIndexTableID
	PgCatalogForeignServerTableID
	PgCatalogForeignTableRelidIndexTableID
	PgCatalogForeignTableTableID
	PgCatalogGroupTableID
	PgCatalogHbaFileRulesTableID
	PgCatalogIndexIndexrelidIndexTableID
	PgCatalogIndexIndrelidIndexTableID
	PgCatalogIndexTableID
	PgCatalogIndexesTableID
	PgCatalogInheritsParentIndexTableID
	PgCatalogInheritsRelidSeqnoIndexTableID
	PgCatalogInheritsTableID
	PgCatalogInitPrivsOCOIndexTableID
	PgCatalogLanguageOidIndexTableID
	PgCatalogLanguageTableID
	PgCatalogLargeobjectLoidPnIndexTableID
	PgCatalogLargeobjectMetadataOidIndexTableID
	PgCatalogLargeobjectTableID
	PgCatalogLocksTableID
	PgCatalogMatViewsTableID
	PgCatalogNamespaceOidIndexTableID
	PgCatalogNamespaceTableID
	PgCatalogOpclassOidIndexTableID
	PgCatalogOpclassTableID
	PgCatalogOperatorOidIndexTableID
	PgCatalogOperatorTableID
	PgCatalogOpfamilyOidIndexTableID
	PgCatalogOpfamilyTableID
	PgCatalogPartitionedTablePartrelidIndexTableID
	PgCatalogPoliciesTableID
	PgCatalogPolicyOidIndexTableID
	PgCatalogPreparedStatementsTableID
	PgCatalogPreparedXactsTableID
	PgCatalogProcOidIndexTableID
	PgCatalogProcTableID
	PgCatalogPublicationOidIndexTableID
	PgCatalogPublicationRelOidIndexTableID
	PgCatalogPublicationRelPrrelidPrpubidIndexTableID
	PgCatalogPublicationRelTableID
	PgCatalogPublicationTableID
	PgCatalogPublicationTablesTableID
	PgCatalogRangeRngtypidIndexTableID
	PgCatalogRangeTableID
	PgCatalogReplicationOriginRoiidentIndexTableID
	PgCatalogReplicationOriginRonameIndexTableID
	PgCatalogReplicationOriginTableID
	PgCatalogRewriteOidIndexTableID
	PgCatalogRewriteTableID
	PgCatalogRolesTableID
	PgCatalogRulesTableID
	PgCatalogSecLabelsTableID
	PgCatalogSeclabelObjectIndexTableID
	PgCatalogSecurityLabelTableID
	PgCatalogSequenceSeqrelidIndexTableID
	PgCatalogSequencesTableID
	PgCatalogSettingsTableID
	PgCatalogShadowTableID
	PgCatalogSharedDescriptionTableID
	PgCatalogSharedSecurityLabelTableID
	PgCatalogShdependDependerIndexTableID
	PgCatalogShdependReferenceIndexTableID
	PgCatalogShdependTableID
	PgCatalogShdescriptionOCIndexTableID
	PgCatalogShmemAllocationsTableID
	PgCatalogShseclabelObjectIndexTableID
	PgCatalogStatActivityTableID
	PgCatalogStatAllIndexesTableID
	PgCatalogStatAllTablesTableID
	PgCatalogStatArchiverTableID
	PgCatalogStatBgwriterTableID
	PgCatalogStatDatabaseConflictsTableID
	PgCatalogStatDatabaseTableID
	PgCatalogStatGssapiTableID
	PgCatalogStatProgressAnalyzeTableID
	PgCatalogStatProgressBasebackupTableID
	PgCatalogStatProgressClusterTableID
	PgCatalogStatProgressCreateIndexTableID
	PgCatalogStatProgressVacuumTableID
	PgCatalogStatSlruTableID
	PgCatalogStatSslTableID
	PgCatalogStatSysIndexesTableID
	PgCatalogStatSysTablesTableID
	PgCatalogStatUserFunctionsTableID
	PgCatalogStatUserIndexesTableID
	PgCatalogStatUserTablesTableID
	PgCatalogStatXactAllTablesTableID
	PgCatalogStatXactSysTablesTableID
	PgCatalogStatXactUserFunctionsTableID
	PgCatalogStatXactUserTablesTableID
	PgCatalogStatioAllIndexesTableID
	PgCatalogStatioAllSequencesTableID
	PgCatalogStatioAllTablesTableID
	PgCatalogStatioSysIndexesTableID
	PgCatalogStatioSysSequencesTableID
	PgCatalogStatioSysTablesTableID
	PgCatalogStatioUserIndexesTableID
	PgCatalogStatioUserSequencesTableID
	PgCatalogStatioUserTablesTableID
	PgCatalogStatisticExtDataStxoidIndexTableID
	PgCatalogStatisticExtOidIndexTableID
	PgCatalogStatisticExtRelidIndexTableID
	PgCatalogStatisticExtTableID
	PgCatalogStatisticRelidAttInhIndexTableID
	PgCatalogSubscriptionOidIndexTableID
	PgCatalogSubscriptionRelSrrelidSrsubidIndexTableID
	PgCatalogSubscriptionTableID
	PgCatalogTablesTableID
	PgCatalogTablespaceOidIndexTableID
	PgCatalogTablespaceTableID
	PgCatalogTimezoneAbbrevsTableID
	PgCatalogTimezoneNamesTableID
	PgCatalogTransformOidIndexTableID
	PgCatalogTransformTableID
	PgCatalogTransformTypeLangIndexTableID
	PgCatalogTriggerOidIndexTableID
	PgCatalogTriggerTableID
	PgCatalogTriggerTgconstraintIndexTableID
	PgCatalogTsConfigMapIndexTableID
	PgCatalogTsConfigMapTableID
	PgCatalogTsConfigOidIndexTableID
	PgCatalogTsConfigTableID
	PgCatalogTsDictOidIndexTableID
	PgCatalogTsDictTableID
	PgCatalogTsParserOidIndexTableID
	PgCatalogTsParserTableID
	PgCatalogTsTemplateOidIndexTableID
	PgCatalogTsTemplateTableID
	PgCatalogTypeOidIndexTableID
	PgCatalogTypeTableID
	PgCatalogUserMappingOidIndexTableID
	PgCatalogUserMappingTableID
	PgCatalogUserMappingUserServerIndexTableID
	PgCatalogUserMappingsTableID
	PgCatalogUserTableID
	PgCatalogViewsTableID
	PgExtensionSchemaID
	PgExtensionGeographyColumnsTableID
	PgExtensionGeometryColumnsTableID
	PgExtensionSpatialRefSysTableID
	MinVirtualID = PgExtensionSpatialRefSysTableID
)
