name: Static Analysis
on: [push, pull_request]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.22.1"
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v4
        with:
          version: v1.55.2
      - name: protoc
        uses: arduino/setup-protoc@v1
        with:
          version: '3.20.3'
      - run: make verify
