name: Workflow Test Template
on: 
  workflow_call:
    inputs:
      runs-on:
        required: false
        type: string
        default: ubuntu-latest
      targets:
        required: false
        type: string
        default: "[]"
permissions: read-all

jobs:
  run:
    runs-on: ${{ inputs.runs-on }}
    strategy:
      fail-fast: false
      matrix:
        target: ${{ fromJSON(inputs.targets) }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.22.1"
      - env: 
          TARGET: ${{ matrix.target }}
        run: |
          go clean -testcache
          case "${TARGET}" in
            linux-amd64-unit-4-cpu-race)
              GOARCH=amd64 PASSES='unit' RACE='true' CPU='4' ./scripts/test.sh -p=2
              ;;
            linux-386-unit-1-cpu)
              GOARCH=386 PASSES='unit' RACE='false' CPU='1' ./scripts/test.sh -p=4
              ;;
            linux-arm64-unit-4-cpu-race)
              GOARCH=arm64 PASSES='unit' RACE='true' CPU='4' ./scripts/test.sh -p=2
              ;;
            *)
              echo "Failed to find target"
              exit 1
              ;;
          esac
