benchmarks:
  - display_name: Sysbench
    labels: ["SQL", "3node", "oltp_read_write"]
    name: "BenchmarkSysbench/SQL/3node/oltp_read_write"
    package: "pkg/sql/tests"
    runner_group: 1
    count: 20
    iterations: 2000
    thresholds:
      "sec/op": .02
      "B/op": .01
      "allocs/op": .01

  - display_name: Sysbench
    labels: ["KV", "1node", "local", "oltp_read_only"]
    name: "BenchmarkSysbench/KV/1node_local/oltp_read_only"
    package: "pkg/sql/tests"
    runner_group: 2
    count: 20
    iterations: 10000
    thresholds:
      "sec/op": .01
      "B/op": .01
      "allocs/op": .01

  - display_name: Sysbench
    labels: ["KV", "1node", "local", "oltp_write_only"]
    name: "BenchmarkSysbench/KV/1node_local/oltp_write_only"
    package: "pkg/sql/tests"
    runner_group: 2
    count: 20
    iterations: 10000
    thresholds:
      "sec/op": .015
      "B/op": .01
      "allocs/op": .01
