name: Add issues to project boards

on:
  issues:
    types: [opened, labeled]

jobs:
  add-to-project:
    name: Add issues to project boards
    runs-on: ubuntu-latest
    steps:
      # NOTE: when adding a new mapping, clone the following block, and fill in
      # the blanks.
      #- uses: actions/add-to-project@v0.4.0
      #  with:
      #    # URL of the project to add issues to
      #    project-url: https://github.com/orgs/cockroachdb/projects/XXX
      #    github-token: ${{ secrets.ADD_TO_PROJECT_PAT }}
      #    # A comma-separated list of labels to use as a filter for issue to be added
      #    labeled: A-foo,T-bar
      - uses: actions/add-to-project@v0.4.0
        with:
          project-url: https://github.com/orgs/cockroachdb/projects/32
          github-token: ${{ secrets.ADD_TO_PROJECT_PAT }}
          labeled: A-admission-control,T-admission-control
      - uses: actions/add-to-project@v0.4.0
        with:
          project-url: https://github.com/orgs/cockroachdb/projects/38
          github-token: ${{ secrets.ADD_TO_PROJECT_PAT }}
          labeled: T-cdc
      - uses: actions/add-to-project@v0.4.0
        with:
          project-url: https://github.com/orgs/cockroachdb/projects/35
          github-token: ${{ secrets.ADD_TO_PROJECT_PAT }}
          labeled: T-jobs
      - uses: actions/add-to-project@v0.4.0
        with:
          project-url: https://github.com/orgs/cockroachdb/projects/45
          github-token: ${{ secrets.ADD_TO_PROJECT_PAT }}
          labeled: T-sql-queries
