name: bincheck

on:
  push:
    tags: [ v* ]

permissions:
  contents: read

jobs:

  linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: cd build/release/bincheck && ./test-linux ${{ github.ref_name }} ${{ github.sha }}

  darwin-amd64:
    runs-on: macos-13
    steps:
    - uses: actions/checkout@v3
    - run: cd build/release/bincheck && ./test-macos-amd64 ${{ github.ref_name }} ${{ github.sha }}

  darwin-arm64:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - run: cd build/release/bincheck && ./test-macos-arm64 ${{ github.ref_name }} ${{ github.sha }}

  windows:
    runs-on: windows-latest
    steps:
    - run: git config --system core.longpaths true
    - uses: actions/checkout@v3
    - run: cd build/release/bincheck && bash test-windows ${{ github.ref_name }} ${{ github.sha }}
