# For most projects, this workflow file will not need changing; you simply need
# to commit it to your repository.
#
# You may wish to alter this file to override the set of languages analyzed,
# or to provide custom queries or build logic.
#
# ******** NOTE ********
# We have attempted to detect the languages in your repository. Please check
# the `language` matrix defined below to confirm you have the correct set of
# supported CodeQL languages.
#
name: "Build"

on:
  workflow_dispatch:

jobs:
  analyze:
    name: make
    runs-on: ubuntu-latest

    steps:
    
    # https://www.cockroachlabs.com/docs/v21.1/install-cockroachdb-linux#build-from-source
    - name: fetch
      shell: bash
      run: |
          curl https://binaries.cockroachdb.com/cockroach-v21.1.19.src.tgz | tar -xz
          cd cockroach-v21.1.19
          ls -l
    
    # Autobuilder was built with Autobuilder was built with go1.17.9, environment has go1.17.9
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.17.9
        
    # GO env debugging
    - name: go info
      env:
        ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
      shell: bash
      run: |          
          echo $(go version) at $(which go)
          echo go version: $(go version)
          echo go env GOPATH: $(go env GOPATH) 
          echo go env GOROOT: $(go env GOROOT) 
          echo cache: $(ls $RUNNER_TOOL_CACHE/go)
    
     # GO env debugging
    - name: build
      shell: bash
      run: |   
          make build
