name: Build Bazel multi-platform docker image

on:
  pull_request_target

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Set TAG value
        id: vars
        run: echo "DOCKER_TAG=$(date +%Y%m%d-%H%M%S)" >> $GITHUB_OUTPUT

      -
        name: GCP Auth
        uses: 'google-github-actions/auth@v1'
        with:
          token_format: access_token
          workload_identity_provider: '${{ secrets.GCP_CRL_CI_IMAGES_WIF_PROVIDER }}'
          service_account: '${{ secrets.GCP_CRL_CI_IMAGES_SERVICE_ACCOUNT }}'
          access_token_lifetime: 5400s # 90 minutes
      -
        name: Login to Artifact Registry
        uses: docker/login-action@v1
        with:
          registry: us-east1-docker.pkg.dev 
          username: oauth2accesstoken
          password: ${{ steps.auth.outputs.access_token }}
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: |
            us-east1-docker.pkg.dev/crl-ci-images/cockroach/bazel-builder:latest-do-not-use
            us-east1-docker.pkg.dev/crl-ci-images/cockroach/bazel-builder:${{ steps.vars.outputs.DOCKER_TAG }}
          platforms: linux/amd64,linux/arm64
          file: build/bazelbuilder/Dockerfile
