name: Create doc issues on PR merge

# Action that creates issues in cockroachdb/docs when a PR is merged from
# cockroachdb/cockroach in the master or release-* branch and has a
# release note in the PR body.

on:
  pull_request:
    branches:
      - master
      - 'release-*'
    types: [closed]

jobs:
  create-doc-issue:
    name: Extract release notes 
    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request.merged == true }}
    steps:
      run: echo "I am merged."
