name: Epic + Issue Ref Linter for PR Body or Commit Messages

on:
  pull_request:
    types: [opened, reopened, synchronize, edited]

jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Bazel cache
        id: bazel-cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/bazel
          key: ${{ runner.os }}-bazel-cache

      - name: Install bazelisk
        run: |
          curl -fsSL https://github.com/bazelbuild/bazelisk/releases/download/v1.10.1/bazelisk-linux-amd64 > /tmp/bazelisk
          sha256sum -c - <<EOF
          4cb534c52cdd47a6223d4596d530e7c9c785438ab3b0a49ff347e991c210b2cd /tmp/bazelisk
          EOF
          mkdir -p "${GITHUB_WORKSPACE}/bin/"
          mv /tmp/bazelisk "${GITHUB_WORKSPACE}/bin/bazel"
          chmod +x "${GITHUB_WORKSPACE}/bin/bazel"

      - name: Run lint
        run: build/github/pr-epic-issue-ref-lint.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
